/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * DATE/TIME           | AUTHOR                                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 2026-07-17 20:30:00 | roger.murphy@emeraldcoastsystemsgroup.com   | EXACTLY 100 curated profiles (test-enforced), grouped: professional = Business Formal / Business Casual / Slice of Life / Work Environments / Occasion & Classic (55); character = The Classics / History / Working Legends / Fantasy & Fun (45). Every preset is just a combination of layer ids + a pose — all five layers remain overridable per generation, so these are entry points into millions of permutations, not a ceiling. All v1.1 preset ids preserved (gallery rows reference them).
 * 2026-08-29 10:00:00 | maintainer@emeraldcoastsystemsgroup.com     | Catalog v2: +25 professional (Sun & Travel, Sports & Fitness, Grand Occasion → 80), +60 character (Sun & Surf, Sports Legends, Sci-Fi, Warriors, Retro & Pop, World Travelers, Myth & Legend → 105), and the NEW GROUP_PRESETS list (40 scenes in Heroes & Sci-Fi, Crews & Bands, Teams, History & Fantasy, Life & Occasion) for group mode — 225 presets, every count test-enforced. No existing id changed.
 */

/** @description A preset = a named combination of layer ids + a pose (what the hands do). */
export interface PortraitPreset {
  id: string;
  label: string;
  icon: string;
  blurb: string;
  /** Picker chip group this preset renders under. */
  group: string;
  background: string;
  attire: string;
  headwear: string;
  finish: string;
  framing: string;
  /** What the hands/pose are doing (group presets: how the whole group is arranged) — a prop override replaces this. */
  pose: string;
}

/** @description 80 formal-people profiles (professional mode — the subject as themselves). */
export const PROFESSIONAL_PRESETS: readonly PortraitPreset[] = [
  // ── Business Formal (12) ─────────────────────────────────────────────────
  { id: 'linkedin', label: 'LinkedIn Classic', icon: '💼', blurb: 'Bright, friendly, hire-me', group: 'Business Formal', background: 'office-bokeh', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'executive', label: 'The Executive', icon: '🏛️', blurb: 'Navy backdrop, quiet power', group: 'Business Formal', background: 'corporate-navy', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms confidently crossed with both hands visible' },
  { id: 'board-chair', label: 'Board Chair', icon: '🪑', blurb: 'Corner office gravitas', group: 'Business Formal', background: 'corner-office', attire: 'three-piece', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a leather chair back' },
  { id: 'keynote', label: 'Keynote Speaker', icon: '🎤', blurb: 'On stage, mid-idea', group: 'Business Formal', background: 'conference-stage', attire: 'turtleneck-blazer', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'hands raised mid-gesture as if making a point' },
  { id: 'banker', label: 'The Banker', icon: '🏦', blurb: 'Marble-hall trust', group: 'Business Formal', background: 'bank-hall', attire: 'pinstripe', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands lightly clasped in front' },
  { id: 'consultant', label: 'The Consultant', icon: '📊', blurb: 'Glass lobby, brisk', group: 'Business Formal', background: 'glass-lobby', attire: 'navy-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand holding a slim portfolio at the side' },
  { id: 'attorney', label: 'The Attorney', icon: '⚖️', blurb: 'Law library, composed', group: 'Business Formal', background: 'law-library', attire: 'gray-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a stack of case reports' },
  { id: 'diplomat', label: 'The Diplomat', icon: '🌐', blurb: 'Measured, international', group: 'Business Formal', background: 'cream-studio', attire: 'overcoat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands gently folded' },
  { id: 'campaign', label: 'Campaign Portrait', icon: '🗳️', blurb: 'Approachable authority', group: 'Business Formal', background: 'clean-white', attire: 'power-blazer', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'annual-report', label: 'Annual Report', icon: '📈', blurb: 'Trading-floor energy', group: 'Business Formal', background: 'trading-floor', attire: 'silk-blouse', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms loosely crossed' },
  { id: 'skyline-exec', label: 'Skyline Executive', icon: '🌇', blurb: 'Rooftop at dusk', group: 'Business Formal', background: 'rooftop-terrace', attire: 'dark-suit', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'one hand in a trouser pocket' },
  { id: 'city-power', label: 'City Power Walk', icon: '🚕', blurb: 'Street-level confidence', group: 'Business Formal', background: 'city-street', attire: 'trench-coat', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'mid-stride, one hand holding a coat lapel' },
  // ── Business Casual (10) ─────────────────────────────────────────────────
  { id: 'startup-founder', label: 'Startup Founder', icon: '🚀', blurb: 'Loft, plants, hustle', group: 'Business Casual', background: 'coworking', attire: 'plain-tee', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms comfortably crossed' },
  { id: 'tech-lead', label: 'Tech Lead', icon: '💻', blurb: 'Server-room glow', group: 'Business Casual', background: 'server-room', attire: 'hoodie', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'one hand resting on a server rack' },
  { id: 'creative-director', label: 'Creative Director', icon: '🎨', blurb: 'Studio, opinionated', group: 'Business Casual', background: 'art-studio', attire: 'smart-creative', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand thoughtfully at the chin' },
  { id: 'architect', label: 'The Architect', icon: '📐', blurb: 'Site + rolled plans', group: 'Business Casual', background: 'construction-site', attire: 'turtleneck-blazer', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'a roll of blueprints tucked under one arm' },
  { id: 'creative', label: 'Creative Pro', icon: '🖌️', blurb: 'Smart-creative, approachable', group: 'Business Casual', background: 'studio-gray', attire: 'smart-creative', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'podcast-host', label: 'Podcast Host', icon: '🎙️', blurb: 'Mic + warm light', group: 'Business Casual', background: 'music-room', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a vintage microphone gripped in one hand' },
  { id: 'author-photo', label: 'Author Jacket', icon: '📖', blurb: 'Back-cover thoughtful', group: 'Business Casual', background: 'bookstore', attire: 'cozy-sweater', headwear: 'none', finish: 'bw', framing: 'half-body', pose: 'arms folded softly, head slightly tilted' },
  { id: 'professor', label: 'The Professor', icon: '🎓', blurb: 'Lecture-hall chalk dust', group: 'Business Casual', background: 'lecture-hall', attire: 'sweater-vest', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'an open book held in one hand' },
  { id: 'whiteboard', label: 'Whiteboard Session', icon: '🖊️', blurb: 'Mid-brainstorm', group: 'Business Casual', background: 'coworking', attire: 'oxford-chinos', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'one hand holding a marker mid-gesture' },
  { id: 'casual-friday', label: 'Casual Friday', icon: '🧢', blurb: 'Relaxed but sharp', group: 'Business Casual', background: 'office-bokeh', attire: 'denim-blazer', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  // ── Slice of Life (12) ───────────────────────────────────────────────────
  { id: 'coffee-morning', label: 'Coffee Shop Morning', icon: '☕', blurb: 'First-sip serenity', group: 'Slice of Life', background: 'cozy-cafe', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'both hands wrapped around a steaming mug' },
  { id: 'sunday-market', label: 'Sunday Market', icon: '🥕', blurb: 'Basket of good things', group: 'Slice of Life', background: 'farmers-market', attire: 'linen-shirt', headwear: 'sun-hat', finish: 'photo', framing: 'three-quarter', pose: 'a woven basket of produce on one arm' },
  { id: 'park-stroll', label: 'Autumn Stroll', icon: '🍁', blurb: 'Leaves + long light', group: 'Slice of Life', background: 'autumn-park', attire: 'parka', headwear: 'beanie', finish: 'photo', framing: 'three-quarter', pose: 'hands tucked warmly in pockets' },
  { id: 'home-cook', label: 'Home Cook', icon: '🍳', blurb: 'Kitchen at golden hour', group: 'Slice of Life', background: 'home-kitchen', attire: 'plain-tee', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a wooden spoon raised for a taste' },
  { id: 'bookworm', label: 'The Bookworm', icon: '📚', blurb: 'Window-seat afternoons', group: 'Slice of Life', background: 'reading-nook', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'an open book held in both hands' },
  { id: 'natural', label: 'Natural Light', icon: '🌤️', blurb: 'Golden-hour, relaxed', group: 'Slice of Life', background: 'outdoor-golden', attire: 'business-casual', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'beach-day', label: 'Beach Day', icon: '🏝️', blurb: 'Salt air, no meetings', group: 'Slice of Life', background: 'tropical-beach', attire: 'hawaiian-shirt', headwear: 'sun-hat', finish: 'photo', framing: 'half-body', pose: 'sunglasses dangling from one hand' },
  { id: 'trail-day', label: 'Trail Day', icon: '🥾', blurb: 'Summit-sized grin', group: 'Slice of Life', background: 'mountain-peak', attire: 'hiking-gear', headwear: 'baseball-cap', finish: 'photo', framing: 'three-quarter', pose: 'thumbs hooked in the pack straps' },
  { id: 'rainy-window', label: 'Rainy Day', icon: '🌧️', blurb: 'Cozy melancholy', group: 'Slice of Life', background: 'cozy-cafe', attire: 'raincoat', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'both hands cupping a warm drink' },
  { id: 'garden-hour', label: 'Garden Hour', icon: '🪴', blurb: 'Greenhouse warmth', group: 'Slice of Life', background: 'greenhouse', attire: 'flannel', headwear: 'sun-hat', finish: 'photo', framing: 'half-body', pose: 'a potted seedling cradled in both hands' },
  { id: 'porch-evening', label: 'Porch Evening', icon: '🏡', blurb: 'Lemonade light', group: 'Slice of Life', background: 'front-porch', attire: 'summer-dress', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on the porch rail' },
  { id: 'holiday-card', label: 'Holiday Card', icon: '🎄', blurb: 'Hearth + cheer', group: 'Slice of Life', background: 'holiday-hearth', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a mug of cocoa raised in a small toast' },
  // ── Work Environments (12) ───────────────────────────────────────────────
  { id: 'surgeon', label: 'The Surgeon', icon: '🩻', blurb: 'OR-ready calm', group: 'Work Environments', background: 'operating-room', attire: 'surgeon-gown', headwear: 'surgical-cap', finish: 'photo', framing: 'half-body', pose: 'gloved hands held raised and ready' },
  { id: 'er-nurse', label: 'The Nurse', icon: '🩺', blurb: 'Ward-shift backbone', group: 'Work Environments', background: 'hospital-ward', attire: 'scrubs', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a stethoscope held lightly in one hand' },
  { id: 'firefighter', label: 'The Firefighter', icon: '🚒', blurb: 'Turnout + engine bay', group: 'Work Environments', background: 'fire-station', attire: 'firefighter-turnout', headwear: 'firefighter-helmet', finish: 'photo', framing: 'half-body', pose: 'helmet strap loose, one gloved hand at the jacket clasp' },
  { id: 'officer-duty', label: 'The Officer', icon: '👮', blurb: 'Precinct portrait', group: 'Work Environments', background: 'police-precinct', attire: 'police-uniform', headwear: 'police-cap', finish: 'photo', framing: 'half-body', pose: 'hands clasped behind the back, shoulders square' },
  { id: 'captain-pilot', label: 'The Pilot', icon: '✈️', blurb: 'Four stripes, tarmac dawn', group: 'Work Environments', background: 'airport-tarmac', attire: 'pilot-uniform', headwear: 'peaked-cap', finish: 'photo', framing: 'half-body', pose: 'a flight case held in one hand' },
  { id: 'teacher', label: 'The Teacher', icon: '🏫', blurb: 'Chalkboard hero', group: 'Work Environments', background: 'classroom', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a piece of chalk raised mid-lesson' },
  { id: 'scientist', label: 'The Scientist', icon: '🧪', blurb: 'Lab-light focus', group: 'Work Environments', background: 'laboratory', attire: 'lab-coat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a flask of colored liquid raised for inspection' },
  { id: 'site-engineer', label: 'Site Engineer', icon: '🏗️', blurb: 'Crane-line horizon', group: 'Work Environments', background: 'construction-site', attire: 'hi-vis', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'a rolled drawing tucked under one arm' },
  { id: 'chef-de-cuisine', label: 'Chef de Cuisine', icon: '👨‍🍳', blurb: 'Pass-side command', group: 'Work Environments', background: 'kitchen', attire: 'chef-whites', headwear: 'chef-toque', finish: 'photo', framing: 'half-body', pose: 'arms crossed while holding a wooden spoon' },
  { id: 'barista-craft', label: 'The Barista', icon: '☕', blurb: 'Latte-art pride', group: 'Work Environments', background: 'cozy-cafe', attire: 'barista-apron', headwear: 'flat-cap', finish: 'photo', framing: 'half-body', pose: 'a finished latte presented in both hands' },
  { id: 'modern-farmer', label: 'Modern Farmer', icon: '🚜', blurb: 'Barn-door morning', group: 'Work Environments', background: 'farm-barn', attire: 'farmer-overalls', headwear: 'baseball-cap', finish: 'photo', framing: 'half-body', pose: 'thumbs hooked in the overall straps' },
  { id: 'master-mechanic', label: 'The Mechanic', icon: '🔧', blurb: 'Lift-bay confidence', group: 'Work Environments', background: 'auto-garage', attire: 'coveralls', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a wrench resting across one shoulder' },
  // ── Occasion & Classic (9) ───────────────────────────────────────────────
  { id: 'classic-studio', label: 'Classic Studio', icon: '🎞️', blurb: 'Timeless gray, your clothes', group: 'Occasion & Classic', background: 'studio-gray', attire: 'keep', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'editorial-bw', label: 'Editorial B&W', icon: '⬛', blurb: 'Dramatic black & white', group: 'Occasion & Classic', background: 'studio-gray', attire: 'keep', headwear: 'none', finish: 'bw', framing: 'headshot', pose: '' },
  { id: 'black-tie', label: 'Black Tie', icon: '🥂', blurb: 'Tuxedo, gala-ready', group: 'Occasion & Classic', background: 'corporate-navy', attire: 'tuxedo', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'graduate', label: 'The Graduate', icon: '🎓', blurb: 'Gown, cap, diploma in hand', group: 'Occasion & Classic', background: 'library', attire: 'academic-gown', headwear: 'graduation-cap', finish: 'photo', framing: 'half-body', pose: 'holding a rolled diploma in both hands' },
  { id: 'doctor', label: 'The Doctor', icon: '🩺', blurb: 'White coat, trusted', group: 'Occasion & Classic', background: 'clean-white', attire: 'doctor-coat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'judge', label: 'The Judge', icon: '⚖️', blurb: 'Robes, gravitas', group: 'Occasion & Classic', background: 'courtroom', attire: 'judge-robe', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands gently folded' },
  { id: 'officer', label: 'Dress Uniform', icon: '🎖️', blurb: 'Medals, formal military', group: 'Occasion & Classic', background: 'studio-gray', attire: 'dress-uniform', headwear: 'peaked-cap', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'vintage', label: 'Vintage Tintype', icon: '🎩', blurb: 'Sepia, top hat, 1890s', group: 'Occasion & Classic', background: 'studio-gray', attire: 'dark-suit', headwear: 'top-hat', finish: 'tintype', framing: 'half-body', pose: '' },
  { id: 'gallery-opening', label: 'Gallery Opening', icon: '🖼️', blurb: 'Noir evening elegance', group: 'Occasion & Classic', background: 'spotlight-black', attire: 'evening-gown', headwear: 'none', finish: 'noir', framing: 'three-quarter', pose: 'a champagne flute held lightly in one hand' },
  // ── Sun & Travel (10) ────────────────────────────────────────────────────
  { id: 'boardwalk-summer', label: 'Boardwalk Summer', icon: '🌞', blurb: 'Sunny, breezy, effortless', group: 'Sun & Travel', background: 'sunny-boardwalk', attire: 'linen-shirt', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand in a pocket, relaxed' },
  { id: 'sailing-day', label: 'Sailing Day', icon: '⛵', blurb: 'Deck, wind, horizon', group: 'Sun & Travel', background: 'sailboat-deck', attire: 'sailing-jacket', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand on a rigging line' },
  { id: 'poolside', label: 'Poolside', icon: '🏊', blurb: 'Resort-bright and relaxed', group: 'Sun & Travel', background: 'pool-deck', attire: 'linen-open-shirt', headwear: 'panama-hat', finish: 'photo', framing: 'half-body', pose: 'sunglasses held in one hand' },
  { id: 'tokyo-nights', label: 'Tokyo Nights', icon: '🗼', blurb: 'Neon-city energy', group: 'Sun & Travel', background: 'tokyo-crossing', attire: 'turtleneck-blazer', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: '' },
  { id: 'paris-terrace', label: 'Paris Terrace', icon: '🥐', blurb: 'Café-society calm', group: 'Sun & Travel', background: 'paris-cafe', attire: 'trench-coat', headwear: 'beret', finish: 'photo', framing: 'half-body', pose: 'an espresso cup held in one hand' },
  { id: 'santorini-blue', label: 'Santorini Blue', icon: '🇬🇷', blurb: 'Whitewash and sea light', group: 'Sun & Travel', background: 'santorini-terrace', attire: 'summer-dress', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'one hand resting on the terrace wall' },
  { id: 'highland-walk', label: 'Highland Walk', icon: '🏴', blurb: 'Heather and mist', group: 'Sun & Travel', background: 'highland-glen', attire: 'parka', headwear: 'flat-cap', finish: 'photo', framing: 'half-body', pose: 'hands in coat pockets' },
  { id: 'safari-dusk', label: 'Safari Dusk', icon: '🦁', blurb: 'Golden-hour expedition', group: 'Sun & Travel', background: 'safari-savanna', attire: 'safari-khakis', headwear: 'pith-helmet', finish: 'photo', framing: 'half-body', pose: 'binoculars held in one hand' },
  { id: 'alpine-morning', label: 'Alpine Morning', icon: '🏔️', blurb: 'Crisp mountain light', group: 'Sun & Travel', background: 'alpine-village', attire: 'ski-jacket', headwear: 'beanie', finish: 'photo', framing: 'half-body', pose: 'a thermos cup held in both hands' },
  { id: 'coastal-walk', label: 'Coastal Walk', icon: '🌊', blurb: 'Sea air and sunshine', group: 'Sun & Travel', background: 'lighthouse-point', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  // ── Sports & Fitness (8) ─────────────────────────────────────────────────
  { id: 'court-side', label: 'Court Side', icon: '🏀', blurb: 'Arena-ready', group: 'Sports & Fitness', background: 'basketball-court', attire: 'basketball-jersey', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a basketball held at the hip' },
  { id: 'tennis-pro', label: 'Tennis Pro', icon: '🎾', blurb: 'Match-point poise', group: 'Sports & Fitness', background: 'tennis-court', attire: 'tennis-whites', headwear: 'visor', finish: 'photo', framing: 'half-body', pose: 'a tennis racket resting on one shoulder' },
  { id: 'fairway', label: 'On the Fairway', icon: '⛳', blurb: 'Golden-hour golf', group: 'Sports & Fitness', background: 'golf-fairway', attire: 'knit-polo', headwear: 'baseball-cap', finish: 'photo', framing: 'half-body', pose: 'a golf club planted like a cane under both hands' },
  { id: 'ski-day', label: 'Ski Day', icon: '⛷️', blurb: 'Powder-day grin', group: 'Sports & Fitness', background: 'ski-slope', attire: 'ski-jacket', headwear: 'ski-goggles', finish: 'photo', framing: 'half-body', pose: 'ski poles planted in both hands' },
  { id: 'gym-strong', label: 'Gym Strong', icon: '🏋️', blurb: 'Chalk and iron', group: 'Sports & Fitness', background: 'iron-gym', attire: 'plain-tee', headwear: 'none', finish: 'bw', framing: 'half-body', pose: 'arms crossed with chalked hands' },
  { id: 'race-ready', label: 'Race Ready', icon: '🏁', blurb: 'Pit-lane focus', group: 'Sports & Fitness', background: 'pit-lane', attire: 'racing-suit', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a racing helmet held under one arm' },
  { id: 'marathoner', label: 'The Marathoner', icon: '🏃', blurb: 'Finish-line triumph', group: 'Sports & Fitness', background: 'marathon-finish', attire: 'tracksuit', headwear: 'headband', finish: 'photo', framing: 'half-body', pose: 'both arms raised in triumph' },
  { id: 'surf-morning', label: 'Surf Morning', icon: '🏄', blurb: 'Dawn-patrol salt', group: 'Sports & Fitness', background: 'surf-break', attire: 'rash-guard', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'a surfboard tucked under one arm' },
  // ── Grand Occasion (7) ───────────────────────────────────────────────────
  { id: 'opera-night', label: 'Opera Night', icon: '🎭', blurb: 'Gilded box seats', group: 'Grand Occasion', background: 'opera-box', attire: 'tuxedo', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'ballroom-portrait', label: 'Ballroom Portrait', icon: '💃', blurb: 'Chandelier glamour', group: 'Grand Occasion', background: 'ballroom', attire: 'ballgown', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'one hand lifting the skirt hem slightly' },
  { id: 'white-tie', label: 'White Tie', icon: '🎩', blurb: 'Tailcoat and wing collar', group: 'Grand Occasion', background: 'grand-staircase', attire: 'tailcoat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'museum-patron', label: 'Museum Patron', icon: '🖼️', blurb: 'Marble and masterpieces', group: 'Grand Occasion', background: 'museum-hall', attire: 'power-blazer', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'garden-party', label: 'Garden Party', icon: '🌹', blurb: 'Hedge-lined elegance', group: 'Grand Occasion', background: 'palace-garden', attire: 'summer-dress', headwear: 'sun-hat', finish: 'photo', framing: 'three-quarter', pose: '' },
  { id: 'wine-collector', label: 'The Collector', icon: '🍷', blurb: 'Cellar candlelight', group: 'Grand Occasion', background: 'wine-cellar', attire: 'turtleneck-blazer', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a wine glass held in one hand' },
  { id: 'rooftop-toast', label: 'Rooftop Toast', icon: '🥂', blurb: 'Skyline celebration', group: 'Grand Occasion', background: 'rooftop-gala', attire: 'tuxedo', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a champagne flute raised in one hand' },
];

/** @description 105 character presets (face on a human-type body, hands in frame). */
export const CHARACTER_PRESETS: readonly PortraitPreset[] = [
  // ── The Classics (12) ────────────────────────────────────────────────────
  { id: 'american-gothic', label: 'American Gothic', icon: '🌾', blurb: 'Stern farmer, pitchfork in hand', group: 'The Classics', background: 'farmhouse', attire: 'farmer-overalls', headwear: 'none', finish: 'regionalist', framing: 'half-body', pose: 'one hand gripping a pitchfork upright, the other at the lapel, with a stern expression' },
  { id: 'steel-mill', label: 'Steel Mill', icon: '🏭', blurb: 'Sparks, gloves, hard hat', group: 'The Classics', background: 'steel-mill', attire: 'work-canvas', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'one gloved hand gripping a glowing steel rod' },
  { id: 'renaissance', label: 'Renaissance Noble', icon: '👑', blurb: 'Velvet, ruff collar, oil paint', group: 'The Classics', background: 'castle-hall', attire: 'renaissance-doublet', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'hands gently folded at the waist' },
  { id: 'astronaut', label: 'Astronaut', icon: '🚀', blurb: 'Official crew portrait', group: 'The Classics', background: 'starfield', attire: 'spacesuit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a space helmet held under one arm, the other gloved hand resting at the chest' },
  { id: 'sea-captain', label: 'Sea Captain', icon: '⚓', blurb: 'Peacoat, wheel, stormy sea', group: 'The Classics', background: 'stormy-harbor', attire: 'peacoat', headwear: 'captains-cap', finish: 'oil', framing: 'half-body', pose: "one weathered hand resting on a ship's wheel" },
  { id: 'victorian-general', label: 'Victorian General', icon: '🎖️', blurb: 'Medals, epaulettes, sword', group: 'The Classics', background: 'studio-gray', attire: 'dress-uniform', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'one gloved hand resting on a sword hilt' },
  { id: 'ceo', label: 'The CEO', icon: '💼', blurb: 'Boardroom, arms crossed', group: 'The Classics', background: 'boardroom', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms confidently crossed with both hands visible' },
  { id: 'chef', label: 'Head Chef', icon: '👨‍🍳', blurb: 'Whites, toque, kitchen', group: 'The Classics', background: 'kitchen', attire: 'chef-whites', headwear: 'chef-toque', finish: 'photo', framing: 'half-body', pose: 'arms crossed while holding a wooden spoon' },
  { id: 'wizard', label: 'Archmage', icon: '🧙', blurb: 'Robes, staff, candlelight', group: 'The Classics', background: 'fireside-study', attire: 'wizard-robes', headwear: 'wizard-hat', finish: 'oil', framing: 'half-body', pose: 'one hand holding a carved wooden staff, the other cradling a faintly glowing orb' },
  { id: 'rockstar', label: 'Rock Star', icon: '🎸', blurb: '80s album cover energy', group: 'The Classics', background: 'stage', attire: 'leather-jacket', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'holding an electric guitar with both hands' },
  { id: 'cowboy', label: 'Cowboy', icon: '🤠', blurb: 'Duster, lasso, dusk prairie', group: 'The Classics', background: 'prairie-dusk', attire: 'duster-coat', headwear: 'cowboy-hat', finish: 'photo', framing: 'half-body', pose: 'one gloved hand holding a coiled lasso' },
  { id: 'knight', label: 'Knight', icon: '⚔️', blurb: 'Plate armor, castle hall', group: 'The Classics', background: 'castle-hall', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a plumed helmet held under one arm, the gauntleted hand resting on a sword pommel' },
  // ── History (10) ─────────────────────────────────────────────────────────
  { id: 'pharaoh', label: 'Pharaoh', icon: '𓂀', blurb: 'Nemes, temple gold', group: 'History', background: 'egyptian-temple', attire: 'toga', headwear: 'nemes', finish: 'oil', framing: 'half-body', pose: 'arms crossed holding a crook and flail' },
  { id: 'roman-senator', label: 'Roman Senator', icon: '🏺', blurb: 'Toga, forum, laurels', group: 'History', background: 'roman-forum', attire: 'toga', headwear: 'laurel-wreath', finish: 'oil', framing: 'half-body', pose: 'one arm raised in oration' },
  { id: 'viking', label: 'Viking Jarl', icon: '🛡️', blurb: 'Longhouse firelight', group: 'History', background: 'viking-longhouse', attire: 'work-canvas', headwear: 'viking-helm', finish: 'oil', framing: 'half-body', pose: 'both hands resting on the haft of a broad axe' },
  { id: 'samurai', label: 'Samurai', icon: '🏯', blurb: 'Dojo stillness', group: 'History', background: 'samurai-dojo', attire: 'kimono', headwear: 'kabuto', finish: 'oil', framing: 'half-body', pose: 'one hand resting on the katana at the waist' },
  { id: 'musketeer', label: 'Musketeer', icon: '🤺', blurb: 'Plume + panache', group: 'History', background: 'castle-hall', attire: 'pirate-coat', headwear: 'tricorn', finish: 'oil', framing: 'three-quarter', pose: 'one hand on a rapier hilt, the other sweeping the hat brim' },
  { id: 'detective', label: 'Victorian Detective', icon: '🔎', blurb: 'Deerstalker deduction', group: 'History', background: 'fireside-study', attire: 'trench-coat', headwear: 'deerstalker', finish: 'noir', framing: 'half-body', pose: 'a brass magnifying glass raised in one hand' },
  { id: 'gangster', label: '1920s Boss', icon: '🥃', blurb: 'Speakeasy shadows', group: 'History', background: 'speakeasy', attire: 'gatsby-tux', headwear: 'fedora', finish: 'noir', framing: 'half-body', pose: 'one hand adjusting a cufflink' },
  { id: 'aviator', label: 'WWI Aviator', icon: '🛩️', blurb: 'Goggles + grit', group: 'History', background: 'airport-tarmac', attire: 'flight-suit', headwear: 'aviator-cap', finish: 'tintype', framing: 'half-body', pose: 'leather gloves clasped in one hand' },
  { id: 'monk', label: 'Medieval Scribe', icon: '📜', blurb: 'Candlelit devotion', group: 'History', background: 'cathedral', attire: 'wizard-robes', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a feather quill poised in one hand over parchment' },
  { id: 'tudor-monarch', label: 'Tudor Monarch', icon: '👑', blurb: 'Throne-room command', group: 'History', background: 'throne-room', attire: 'renaissance-doublet', headwear: 'crown', finish: 'oil', framing: 'three-quarter', pose: 'one hand bearing a golden scepter' },
  // ── Working Legends (10) ─────────────────────────────────────────────────
  { id: 'lumberjack', label: 'Lumberjack', icon: '🪓', blurb: 'Flannel + felling axe', group: 'Working Legends', background: 'snowy-pines', attire: 'flannel', headwear: 'beanie', finish: 'photo', framing: 'half-body', pose: 'a felling axe resting across one shoulder' },
  { id: 'blacksmith', label: 'Blacksmith', icon: '🔨', blurb: 'Forge-glow muscle', group: 'Working Legends', background: 'steel-mill', attire: 'leather-apron', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a blacksmith hammer resting head-down under one hand' },
  { id: 'fisherman', label: 'The Fisherman', icon: '🎣', blurb: 'Slicker + sea spray', group: 'Working Legends', background: 'fishing-harbor', attire: 'fisherman-slicker', headwear: 'captains-cap', finish: 'photo', framing: 'half-body', pose: 'a fishing rod shouldered in one hand' },
  { id: 'conductor', label: 'Train Conductor', icon: '🚂', blurb: 'Brass buttons, right on time', group: 'Working Legends', background: 'metro-platform', attire: 'conductor-uniform', headwear: 'peaked-cap', finish: 'tintype', framing: 'half-body', pose: 'one hand consulting a gold pocket watch on a chain' },
  { id: 'mad-scientist', label: 'Mad Scientist', icon: '⚗️', blurb: 'Eureka at midnight', group: 'Working Legends', background: 'laboratory', attire: 'lab-coat', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a bubbling flask raised triumphantly in one hand, hair slightly wild' },
  { id: 'librarian', label: 'Grand Librarian', icon: '📚', blurb: 'Keeper of the stacks', group: 'Working Legends', background: 'library', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a tall stack of books balanced in both arms' },
  { id: 'ringmaster', label: 'Ringmaster', icon: '🎪', blurb: 'Big-top showmanship', group: 'Working Legends', background: 'circus-ring', attire: 'gatsby-tux', headwear: 'top-hat', finish: 'cinematic', framing: 'three-quarter', pose: 'one arm flung wide in welcome, the other tipping the hat' },
  { id: 'astronomer', label: 'Astronomer', icon: '🔭', blurb: 'Charting the heavens', group: 'Working Legends', background: 'moon-base', attire: 'cozy-sweater', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a brass spyglass telescope held in both hands' },
  { id: 'explorer', label: 'The Explorer', icon: '🧭', blurb: 'Uncharted-map energy', group: 'Working Legends', background: 'desert-dunes', attire: 'park-ranger', headwear: 'pith-helmet', finish: 'tintype', framing: 'half-body', pose: 'an unrolled map held in both hands' },
  { id: 'park-warden', label: 'Park Warden', icon: '🌲', blurb: 'Trailhead steward', group: 'Working Legends', background: 'forest-path', attire: 'park-ranger', headwear: 'flat-cap', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a wooden trail sign' },
  // ── Fantasy & Fun (13) ───────────────────────────────────────────────────
  { id: 'pirate-captain', label: 'Pirate Captain', icon: '🏴‍☠️', blurb: 'Deck, cutlass, horizon', group: 'Fantasy & Fun', background: 'pirate-deck', attire: 'pirate-coat', headwear: 'tricorn', finish: 'oil', framing: 'half-body', pose: 'one boot up on a cannon, hand resting on a cutlass hilt' },
  { id: 'superhero', label: 'Superhero', icon: '🦸', blurb: 'Cape-flare skyline', group: 'Fantasy & Fun', background: 'rooftop-terrace', attire: 'tracksuit', headwear: 'none', finish: 'pop-art', framing: 'three-quarter', pose: 'fists planted on hips, cape rippling' },
  { id: 'vampire-count', label: 'Vampire Count', icon: '🦇', blurb: 'Gothic-manor menace', group: 'Fantasy & Fun', background: 'victorian-parlor', attire: 'gatsby-tux', headwear: 'none', finish: 'noir', framing: 'half-body', pose: 'a candelabra raised in one pale hand' },
  { id: 'steampunk', label: 'Steampunk Inventor', icon: '⚙️', blurb: 'Brass, gears, altitude', group: 'Fantasy & Fun', background: 'airship-deck', attire: 'leather-apron', headwear: 'aviator-cap', finish: 'tintype', framing: 'half-body', pose: 'a wrench in one hand, the other on a brass valve wheel' },
  { id: 'elf-ranger', label: 'Elf Ranger', icon: '🏹', blurb: 'Enchanted-forest watch', group: 'Fantasy & Fun', background: 'enchanted-forest', attire: 'hiking-gear', headwear: 'none', finish: 'oil', framing: 'three-quarter', pose: 'a longbow held at the side, one hand at the quiver' },
  { id: 'dragon-keeper', label: 'Dragon Keeper', icon: '🐉', blurb: 'Hoard-light bravado', group: 'Fantasy & Fun', background: 'dragon-lair', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a lantern raised in one gauntleted hand' },
  { id: 'royal-portrait', label: 'Royal Portrait', icon: '👑', blurb: 'Crown + gilded frame', group: 'Fantasy & Fun', background: 'throne-room', attire: 'evening-gown', headwear: 'crown', finish: 'oil', framing: 'three-quarter', pose: 'hands composed regally in the lap' },
  { id: 'jazz-legend', label: 'Jazz Legend', icon: '🎷', blurb: 'Smoky-club cool', group: 'Fantasy & Fun', background: 'speakeasy', attire: 'gatsby-tux', headwear: 'fedora', finish: 'bw', framing: 'half-body', pose: 'a vintage microphone gripped in one hand' },
  { id: 'disco-star', label: 'Disco Star', icon: '🪩', blurb: 'Saturday-night shimmer', group: 'Fantasy & Fun', background: 'neon-arcade', attire: 'tracksuit', headwear: 'none', finish: 'pop-art', framing: 'three-quarter', pose: 'one arm pointed skyward in the classic disco pose' },
  { id: 'surf-legend', label: 'Surf Legend', icon: '🏄', blurb: 'Endless-summer salt', group: 'Fantasy & Fun', background: 'ocean-cliff', attire: 'hawaiian-shirt', headwear: 'none', finish: 'polaroid', framing: 'three-quarter', pose: 'a surfboard tucked under one arm' },
  { id: 'race-driver', label: 'Race Driver', icon: '🏎️', blurb: 'Podium champagne', group: 'Fantasy & Fun', background: 'auto-garage', attire: 'coveralls', headwear: 'baseball-cap', finish: 'cinematic', framing: 'half-body', pose: 'a racing helmet held under one arm' },
  { id: 'opera-diva', label: 'Opera Star', icon: '🎭', blurb: 'Aria mid-flight', group: 'Fantasy & Fun', background: 'spotlight-black', attire: 'evening-gown', headwear: 'none', finish: 'oil', framing: 'three-quarter', pose: 'both arms lifted mid-aria' },
  { id: 'deep-diver', label: 'Reef Explorer', icon: '🐠', blurb: 'Sunbeam shallows', group: 'Fantasy & Fun', background: 'underwater-reef', attire: 'spacesuit', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'an old brass diving helmet held under one arm' },
  // ── Sun & Surf (10) ──────────────────────────────────────────────────────
  { id: 'beach-lifeguard', label: 'Lifeguard', icon: '🛟', blurb: 'Tower, whistle, sun', group: 'Sun & Surf', background: 'surf-break', attire: 'rash-guard', headwear: 'visor', finish: 'photo', framing: 'half-body', pose: 'a red rescue float tucked under one arm' },
  { id: 'island-castaway', label: 'Island Castaway', icon: '🏝️', blurb: 'Coconut-radio survivor', group: 'Sun & Surf', background: 'snorkel-lagoon', attire: 'linen-open-shirt', headwear: 'bucket-hat', finish: 'photo', framing: 'half-body', pose: 'a coconut with a straw held in one hand' },
  { id: 'yacht-captain', label: 'Yacht Captain', icon: '🛥️', blurb: 'Marina-money swagger', group: 'Sun & Surf', background: 'marina-sunset', attire: 'sailing-jacket', headwear: 'captains-cap', finish: 'photo', framing: 'half-body', pose: 'one hand on the wheel, the other holding sunglasses' },
  { id: 'tiki-host', label: 'Tiki Host', icon: '🍹', blurb: 'Umbrella-drink ambassador', group: 'Sun & Surf', background: 'tiki-bar', attire: 'hawaiian-shirt', headwear: 'none', finish: 'film-70s', framing: 'half-body', pose: 'a tall tropical drink with a paper umbrella raised in one hand' },
  { id: 'pearl-diver', label: 'Pearl Diver', icon: '🐚', blurb: 'Lagoon treasure', group: 'Sun & Surf', background: 'catamaran-bow', attire: 'wetsuit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a snorkel mask and fins held in one hand' },
  { id: 'boardwalk-champ', label: 'Boardwalk Champ', icon: '🧸', blurb: 'Arcade-prize legend', group: 'Sun & Surf', background: 'boardwalk-arcade', attire: 'denim-jacket', headwear: 'snapback', finish: 'pop-art', framing: 'half-body', pose: 'a giant plush prize held in both arms' },
  { id: 'beach-volleyballer', label: 'Beach Volleyballer', icon: '🏐', blurb: 'Sand-court star', group: 'Sun & Surf', background: 'sunny-boardwalk', attire: 'rash-guard', headwear: 'visor', finish: 'photo', framing: 'half-body', pose: 'a striped beach ball held on one hip' },
  { id: 'lighthouse-keeper', label: 'Lighthouse Keeper', icon: '🏮', blurb: 'Storm-lamp steward', group: 'Sun & Surf', background: 'lighthouse-point', attire: 'fisherman-slicker', headwear: 'sailor-cap', finish: 'oil', framing: 'half-body', pose: 'a brass lantern raised in one hand' },
  { id: 'bonfire-bard', label: 'Bonfire Bard', icon: '🔥', blurb: 'Sunset sing-along', group: 'Sun & Surf', background: 'beach-bonfire', attire: 'flannel', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'an acoustic guitar held across the body' },
  { id: 'ice-cream-mogul', label: 'Ice Cream Mogul', icon: '🍦', blurb: 'Soft-serve royalty', group: 'Sun & Surf', background: 'soda-fountain', attire: 'barista-apron', headwear: 'none', finish: 'pop-art', framing: 'half-body', pose: 'an ice cream cone held in one hand' },
  // ── Sports Legends (10) ──────────────────────────────────────────────────
  { id: 'heavyweight', label: 'Heavyweight Champ', icon: '🥊', blurb: 'Belt-night bravado', group: 'Sports Legends', background: 'boxing-ring', attire: 'boxing-robe', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'gloved fists raised in a boxing guard' },
  { id: 'slam-dunk', label: 'Slam Dunk', icon: '🏀', blurb: 'Arena MVP', group: 'Sports Legends', background: 'stadium-lights', attire: 'basketball-jersey', headwear: 'headband', finish: 'photo', framing: 'three-quarter', pose: 'a basketball spun on one fingertip' },
  { id: 'slugger', label: 'The Slugger', icon: '⚾', blurb: 'Dugout legend', group: 'Sports Legends', background: 'baseball-dugout', attire: 'baseball-uniform', headwear: 'baseball-cap', finish: 'tintype', framing: 'half-body', pose: 'a baseball bat resting across the shoulders' },
  { id: 'enforcer', label: 'The Enforcer', icon: '🏒', blurb: 'Ice-cold hockey grit', group: 'Sports Legends', background: 'hockey-rink', attire: 'hockey-jersey', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a hockey stick held upright in both hands' },
  { id: 'grand-prix', label: 'Grand Prix Ace', icon: '🏎️', blurb: 'Podium spray', group: 'Sports Legends', background: 'pit-lane', attire: 'racing-suit', headwear: 'racing-helmet', finish: 'cinematic', framing: 'half-body', pose: 'a champagne bottle raised in one hand' },
  { id: 'downhill-racer', label: 'Downhill Racer', icon: '⛷️', blurb: 'Powder-day speed', group: 'Sports Legends', background: 'ski-slope', attire: 'ski-jacket', headwear: 'ski-goggles', finish: 'photo', framing: 'half-body', pose: 'ski poles planted in both hands' },
  { id: 'skate-legend', label: 'Skate Legend', icon: '🛹', blurb: 'Bowl-riding cool', group: 'Sports Legends', background: 'skate-park', attire: 'hoodie', headwear: 'snapback', finish: 'film-70s', framing: 'three-quarter', pose: 'a skateboard held upright at the side' },
  { id: 'summit-climber', label: 'Summit Climber', icon: '🧗', blurb: 'Chalk-hand grit', group: 'Sports Legends', background: 'climbing-wall', attire: 'tracksuit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'chalked hands clapped together' },
  { id: 'kung-fu-master', label: 'Kung Fu Master', icon: '🥋', blurb: 'Silent-mountain focus', group: 'Sports Legends', background: 'sky-temple', attire: 'kung-fu-silk', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'one palm raised in salute over a fist' },
  { id: 'jockey', label: 'The Jockey', icon: '🏇', blurb: 'Silks and stirrups', group: 'Sports Legends', background: 'prairie-dusk', attire: 'jockey-silks', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a riding crop held in one hand' },
  // ── Sci-Fi (10) ──────────────────────────────────────────────────────────
  { id: 'starship-captain', label: 'Starship Captain', icon: '🖖', blurb: 'Bridge command', group: 'Sci-Fi', background: 'starship-bridge', attire: 'starfleet-tunic', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'one hand resting on the captain’s chair' },
  { id: 'cyber-runner', label: 'Cyber Runner', icon: '🌆', blurb: 'Neon-rain outlaw', group: 'Sci-Fi', background: 'cyberpunk-alley', attire: 'cyberpunk-jacket', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a glowing holographic device held in one hand' },
  { id: 'mech-pilot', label: 'Mech Pilot', icon: '🤖', blurb: 'Hangar-bay hero', group: 'Sci-Fi', background: 'mech-hangar', attire: 'flight-suit', headwear: 'none', finish: 'comic-ink', framing: 'half-body', pose: 'a pilot helmet held under one arm' },
  { id: 'space-marine-hero', label: 'Space Marine', icon: '🛡️', blurb: 'Power-armor resolve', group: 'Sci-Fi', background: 'hangar-bay', attire: 'space-marine', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a heavy helmet held under one arm' },
  { id: 'mars-colonist', label: 'Mars Colonist', icon: '🔴', blurb: 'Red-planet pioneer', group: 'Sci-Fi', background: 'mars-dome', attire: 'spacesuit', headwear: 'space-helmet-open', finish: 'photo', framing: 'half-body', pose: 'a sample case held in one hand' },
  { id: 'alien-botanist', label: 'Alien Botanist', icon: '🌱', blurb: 'Twin-moon fieldwork', group: 'Sci-Fi', background: 'alien-jungle', attire: 'lab-coat', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a glowing alien flower cradled in both hands' },
  { id: 'asteroid-miner', label: 'Asteroid Miner', icon: '⛏️', blurb: 'Deep-void grit', group: 'Sci-Fi', background: 'asteroid-outpost', attire: 'coveralls', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'a plasma drill held in both hands' },
  { id: 'retro-spaceman', label: 'Retro Spaceman', icon: '🚀', blurb: '1950s serial hero', group: 'Sci-Fi', background: 'desert-planet', attire: 'spacesuit', headwear: 'space-helmet-open', finish: 'graphic-poster', framing: 'half-body', pose: 'a chrome retro toy ray gun held at the hip' },
  { id: 'android-detective', label: 'Android Detective', icon: '🔍', blurb: 'Chrome-noir sleuth', group: 'Sci-Fi', background: 'neo-tokyo', attire: 'trench-coat', headwear: 'fedora', finish: 'noir', framing: 'half-body', pose: 'a holographic case file held in one hand' },
  { id: 'holo-gamer', label: 'Holo Gamer', icon: '🎮', blurb: 'Grid-room champion', group: 'Sci-Fi', background: 'holodeck-grid', attire: 'neon-windbreaker', headwear: 'none', finish: 'anime-cel', framing: 'half-body', pose: 'a glowing controller held in both hands' },
  // ── Warriors (8) ─────────────────────────────────────────────────────────
  { id: 'ronin', label: 'Rōnin', icon: '🗡️', blurb: 'Masterless wanderer', group: 'Warriors', background: 'kyoto-gate', attire: 'kimono', headwear: 'conical-hat', finish: 'oil', framing: 'three-quarter', pose: 'a sheathed katana held at the side in one hand' },
  { id: 'samurai-lord', label: 'Samurai Daimyō', icon: '🏯', blurb: 'Armored clan lord', group: 'Warriors', background: 'samurai-dojo', attire: 'samurai-armor', headwear: 'kabuto', finish: 'oil', framing: 'half-body', pose: 'both hands resting on the hilt of a katana, tip down' },
  { id: 'ninja', label: 'Shadow Ninja', icon: '🥷', blurb: 'Rooftop silence', group: 'Warriors', background: 'kyoto-gate', attire: 'ninja-shozoku', headwear: 'ninja-hood', finish: 'cinematic', framing: 'half-body', pose: 'one hand raised in a focus sign' },
  { id: 'shieldmaiden', label: 'Shieldmaiden', icon: '🛡️', blurb: 'Northern steel', group: 'Warriors', background: 'black-sand-beach', attire: 'work-canvas', headwear: 'viking-helm', finish: 'oil', framing: 'half-body', pose: 'a painted round shield on one arm' },
  { id: 'gladiator', label: 'Gladiator', icon: '🏟️', blurb: 'Arena thunder', group: 'Warriors', background: 'roman-forum', attire: 'toga', headwear: 'laurel-wreath', finish: 'oil', framing: 'half-body', pose: 'a short sword raised in salute' },
  { id: 'paladin', label: 'Paladin', icon: '✨', blurb: 'Radiant oath-keeper', group: 'Warriors', background: 'cathedral', attire: 'paladin-armor', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'both hands resting on the pommel of a point-down longsword' },
  { id: 'kendo-master', label: 'Kendo Master', icon: '🎋', blurb: 'Dojo thunder', group: 'Warriors', background: 'samurai-dojo', attire: 'karate-gi', headwear: 'none', finish: 'bw', framing: 'half-body', pose: 'a bamboo shinai held upright in both hands' },
  { id: 'monk-warrior', label: 'Warrior Monk', icon: '☯️', blurb: 'Mountain-temple calm', group: 'Warriors', background: 'sky-temple', attire: 'kung-fu-silk', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a wooden bo staff held upright in one hand' },
  // ── Retro & Pop (8) ──────────────────────────────────────────────────────
  { id: 'diner-idol', label: 'Diner Idol', icon: '🎙️', blurb: 'Jukebox heartthrob', group: 'Retro & Pop', background: 'fifties-diner', attire: 'letterman-jacket', headwear: 'none', finish: 'film-70s', framing: 'half-body', pose: 'a milkshake held in one hand' },
  { id: 'disco-king', label: 'Disco Royalty', icon: '🕺', blurb: 'Mirror-ball majesty', group: 'Retro & Pop', background: 'disco-floor', attire: 'disco-suit', headwear: 'none', finish: 'film-70s', framing: 'three-quarter', pose: 'one arm pointed skyward in the classic disco pose' },
  { id: 'mall-rat', label: '80s Mall Star', icon: '📼', blurb: 'Neon and hairspray', group: 'Retro & Pop', background: 'eighties-mall', attire: 'neon-windbreaker', headwear: 'visor', finish: 'pop-art', framing: 'half-body', pose: 'a boombox held on one shoulder' },
  { id: 'grunge-icon', label: '90s Grunge Icon', icon: '🎸', blurb: 'Flannel and feedback', group: 'Retro & Pop', background: 'record-store', attire: 'grunge-denim', headwear: 'beanie', finish: 'film-70s', framing: 'half-body', pose: 'an electric guitar held across the body' },
  { id: 'drive-in-date', label: 'Drive-In Night', icon: '🚗', blurb: 'Big screen, bench seat', group: 'Retro & Pop', background: 'drive-in', attire: 'letterman-jacket', headwear: 'none', finish: 'film-70s', framing: 'half-body', pose: 'a bucket of popcorn held in one hand' },
  { id: 'roller-queen', label: 'Roller Rink Star', icon: '🛼', blurb: 'Four-wheel glide', group: 'Retro & Pop', background: 'roller-rink', attire: 'tracksuit', headwear: 'headband', finish: 'pop-art', framing: 'three-quarter', pose: 'roller skates slung over one shoulder' },
  { id: 'flapper', label: 'Jazz-Age Flapper', icon: '💃', blurb: 'Gin-fizz sparkle', group: 'Retro & Pop', background: 'speakeasy', attire: 'flapper-dress', headwear: 'none', finish: 'bw', framing: 'half-body', pose: 'a feathered fan held in one hand' },
  { id: 'soda-jerk', label: 'Soda Jerk', icon: '🥤', blurb: 'Chrome-counter charm', group: 'Retro & Pop', background: 'soda-fountain', attire: 'barista-apron', headwear: 'boater', finish: 'tintype', framing: 'half-body', pose: 'a tall soda glass held in one hand' },
  // ── World Travelers (8) ──────────────────────────────────────────────────
  { id: 'mariachi', label: 'Mariachi', icon: '🎺', blurb: 'Serenade in silver', group: 'World Travelers', background: 'old-town-square', attire: 'mariachi-suit', headwear: 'sombrero', finish: 'photo', framing: 'half-body', pose: 'a trumpet held in both hands' },
  { id: 'matador', label: 'Matador', icon: '🌹', blurb: 'Traje de luces', group: 'World Travelers', background: 'terracotta-studio', attire: 'matador-suit', headwear: 'none', finish: 'oil', framing: 'three-quarter', pose: 'a red cape draped over one arm' },
  { id: 'venetian-noble', label: 'Venetian Noble', icon: '🎭', blurb: 'Carnival masquerade', group: 'World Travelers', background: 'venice-canal', attire: 'renaissance-doublet', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'an ornate carnival mask held in one hand' },
  { id: 'souk-merchant', label: 'Souk Merchant', icon: '🏺', blurb: 'Lantern-lit bargainer', group: 'World Travelers', background: 'moroccan-souk', attire: 'linen-shirt', headwear: 'fez', finish: 'oil', framing: 'half-body', pose: 'a brass lamp held in one hand' },
  { id: 'highland-chief', label: 'Highland Chief', icon: '🏴', blurb: 'Clan and claymore', group: 'World Travelers', background: 'highland-glen', attire: 'kilt', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'both hands resting on the pommel of a point-down longsword' },
  { id: 'havana-crooner', label: 'Havana Crooner', icon: '🎶', blurb: 'Pastel-street serenade', group: 'World Travelers', background: 'havana-street', attire: 'linen-shirt', headwear: 'panama-hat', finish: 'film-70s', framing: 'half-body', pose: 'a vintage microphone gripped in one hand' },
  { id: 'safari-guide', label: 'Safari Guide', icon: '🐘', blurb: 'Savanna tracker', group: 'World Travelers', background: 'safari-savanna', attire: 'safari-khakis', headwear: 'pith-helmet', finish: 'photo', framing: 'half-body', pose: 'binoculars held in one hand' },
  { id: 'arctic-explorer', label: 'Arctic Explorer', icon: '🧊', blurb: 'Aurora expedition', group: 'World Travelers', background: 'aurora-sky', attire: 'expedition-parka', headwear: 'ushanka', finish: 'photo', framing: 'half-body', pose: 'an ice axe held in one hand' },
  // ── Myth & Legend (6) ────────────────────────────────────────────────────
  { id: 'ice-queen', label: 'Ice Sovereign', icon: '❄️', blurb: 'Frozen-palace majesty', group: 'Myth & Legend', background: 'ice-palace', attire: 'ballgown', headwear: 'ice-crown', finish: 'oil', framing: 'three-quarter', pose: 'one hand raised with frost swirling from the fingertips' },
  { id: 'forest-druid', label: 'Forest Druid', icon: '🌿', blurb: 'Mushroom-glow wisdom', group: 'Myth & Legend', background: 'mushroom-forest', attire: 'wizard-robes', headwear: 'flower-crown', finish: 'oil', framing: 'half-body', pose: 'a gnarled wooden staff held in one hand' },
  { id: 'dwarven-smith', label: 'Dwarven Smith', icon: '⚒️', blurb: 'Forge-hall mastery', group: 'Myth & Legend', background: 'dwarven-forge', attire: 'leather-apron', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a great hammer resting head-down under one hand' },
  { id: 'elven-noble', label: 'Elven Noble', icon: '🧝', blurb: 'Silver-glade grace', group: 'Myth & Legend', background: 'elven-glade', attire: 'elven-leathers', headwear: 'laurel-wreath', finish: 'oil', framing: 'half-body', pose: 'a longbow held at the side, one hand at the quiver' },
  { id: 'sky-monk', label: 'Cloud Monk', icon: '☁️', blurb: 'Temple above the clouds', group: 'Myth & Legend', background: 'sky-temple', attire: 'kung-fu-silk', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'hands pressed together in greeting' },
  { id: 'ferryman', label: 'The Ferryman', icon: '🕯️', blurb: 'Lantern on dark water', group: 'Myth & Legend', background: 'underworld-river', attire: 'wizard-robes', headwear: 'hooded-cloak', finish: 'oil', framing: 'half-body', pose: 'a lantern raised in one hand' },
];

/**
 * @description 40 GROUP scenes (group mode — every face from the reference sheet placed in ONE scene).
 * Same shape as a solo preset; `pose` describes the ARRANGEMENT of the whole group instead of one pair of hands.
 */
export const GROUP_PRESETS: readonly PortraitPreset[] = [
  // ── Heroes & Sci-Fi (8) ──────────────────────────────────────────────────
  { id: 'superhero-team', label: 'Superhero Team', icon: '🦸', blurb: 'Cape-flare skyline squad', group: 'Heroes & Sci-Fi', background: 'rooftop-terrace', attire: 'team-supersuit', headwear: 'none', finish: 'comic-ink', framing: 'three-quarter', pose: 'standing shoulder to shoulder in a heroic power stance, capes rippling, each with a distinct color accent on the matching uniform' },
  { id: 'starship-crew', label: 'Starship Crew', icon: '🖖', blurb: 'Bridge-crew formation', group: 'Heroes & Sci-Fi', background: 'starship-bridge', attire: 'starfleet-tunic', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'arranged around the captain’s chair, one seated and the others standing at the consoles' },
  { id: 'mech-squadron', label: 'Mech Squadron', icon: '🤖', blurb: 'Hangar-bay pilots', group: 'Heroes & Sci-Fi', background: 'mech-hangar', attire: 'flight-suit', headwear: 'none', finish: 'comic-ink', framing: 'three-quarter', pose: 'lined up in front of a towering mech with helmets under their arms' },
  { id: 'cyber-runners', label: 'Cyber Runners', icon: '🌆', blurb: 'Neon-alley crew', group: 'Heroes & Sci-Fi', background: 'cyberpunk-alley', attire: 'cyberpunk-jacket', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'loosely grouped in the rain-lit alley, each lit by a different neon color' },
  { id: 'mars-expedition', label: 'Mars Expedition', icon: '🔴', blurb: 'First-footprint crew', group: 'Heroes & Sci-Fi', background: 'mars-dome', attire: 'spacesuit', headwear: 'space-helmet-open', finish: 'photo', framing: 'three-quarter', pose: 'posed as an official mission crew portrait with helmets open' },
  { id: 'retro-space-patrol', label: 'Retro Space Patrol', icon: '🚀', blurb: '1950s serial squad', group: 'Heroes & Sci-Fi', background: 'desert-planet', attire: 'spacesuit', headwear: 'space-helmet-open', finish: 'graphic-poster', framing: 'three-quarter', pose: 'posed dramatically like a pulp serial poster with chrome toy ray guns at the hip' },
  { id: 'space-marines', label: 'Space Marine Squad', icon: '🛡️', blurb: 'Power-armor fireteam', group: 'Heroes & Sci-Fi', background: 'hangar-bay', attire: 'space-marine', headwear: 'none', finish: 'cinematic', framing: 'wide', pose: 'standing in a tight V formation with helmets under their arms' },
  { id: 'hero-academy', label: 'Hero Academy Class', icon: '🎓', blurb: 'Class-photo capes', group: 'Heroes & Sci-Fi', background: 'stadium-lights', attire: 'team-supersuit', headwear: 'domino-mask', finish: 'anime-cel', framing: 'three-quarter', pose: 'arranged like a class photo, the front row kneeling and the back row standing' },
  // ── Crews & Bands (8) ────────────────────────────────────────────────────
  { id: 'pirate-crew', label: 'Pirate Crew', icon: '🏴‍☠️', blurb: 'Deck, cutlasses, grins', group: 'Crews & Bands', background: 'pirate-deck', attire: 'pirate-coat', headwear: 'tricorn', finish: 'oil', framing: 'wide', pose: 'gathered on the deck around a treasure chest, one boot up on the chest' },
  { id: 'rock-band', label: 'Rock Band', icon: '🎸', blurb: 'Album-cover attitude', group: 'Crews & Bands', background: 'stage', attire: 'leather-jacket', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'posed like a band album cover with guitars, a bass and drumsticks in hand' },
  { id: 'jazz-quartet', label: 'Jazz Quartet', icon: '🎷', blurb: 'Smoky-club ensemble', group: 'Crews & Bands', background: 'speakeasy', attire: 'gatsby-tux', headwear: 'fedora', finish: 'bw', framing: 'three-quarter', pose: 'gathered around a vintage microphone with a saxophone, a trumpet and an upright bass' },
  { id: 'heist-crew', label: 'Heist Crew', icon: '🕶️', blurb: 'Slow-walk swagger', group: 'Crews & Bands', background: 'glass-lobby', attire: 'dark-suit', headwear: 'none', finish: 'cinematic', framing: 'wide', pose: 'walking toward the camera in a line with slow-motion swagger, sunglasses on' },
  { id: 'boy-band', label: 'Band Cover Shoot', icon: '🎤', blurb: 'Coordinated cool', group: 'Crews & Bands', background: 'clean-white', attire: 'denim-blazer', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'posed in coordinated outfits with a hand on a neighbor’s shoulder, album-cover style' },
  { id: 'punk-band', label: 'Punk Band', icon: '🤘', blurb: 'Graffiti-wall snarl', group: 'Crews & Bands', background: 'graffiti-wall', attire: 'grunge-denim', headwear: 'beanie', finish: 'film-70s', framing: 'three-quarter', pose: 'leaning against the wall with crossed arms and guitar cases' },
  { id: 'mariachi-band', label: 'Mariachi Band', icon: '🎺', blurb: 'Plaza serenade', group: 'Crews & Bands', background: 'old-town-square', attire: 'mariachi-suit', headwear: 'sombrero', finish: 'photo', framing: 'three-quarter', pose: 'playing trumpet, guitarrón and violin in a semicircle' },
  { id: 'disco-squad', label: 'Disco Squad', icon: '🪩', blurb: 'Saturday-night lineup', group: 'Crews & Bands', background: 'disco-floor', attire: 'disco-suit', headwear: 'none', finish: 'film-70s', framing: 'three-quarter', pose: 'striking synchronized disco poses under the mirror ball' },
  // ── Teams (8) ────────────────────────────────────────────────────────────
  { id: 'championship-team', label: 'Championship Team', icon: '🏆', blurb: 'Trophy-lift roar', group: 'Teams', background: 'stadium-lights', attire: 'basketball-jersey', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'crowded around a raised trophy with arms up in celebration' },
  { id: 'baseball-nine', label: 'Baseball Nine', icon: '⚾', blurb: 'Dugout team photo', group: 'Teams', background: 'baseball-dugout', attire: 'baseball-uniform', headwear: 'baseball-cap', finish: 'tintype', framing: 'three-quarter', pose: 'arranged as a vintage team photo with bats crossed in front' },
  { id: 'hockey-line', label: 'Hockey Line', icon: '🏒', blurb: 'Ice-cold lineup', group: 'Teams', background: 'hockey-rink', attire: 'hockey-jersey', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'lined up on the ice with sticks held upright' },
  { id: 'racing-team', label: 'Racing Team', icon: '🏁', blurb: 'Pit-wall crew', group: 'Teams', background: 'pit-lane', attire: 'racing-suit', headwear: 'none', finish: 'cinematic', framing: 'wide', pose: 'standing in front of the pit garage with helmets held under their arms' },
  { id: 'ski-squad', label: 'Ski Squad', icon: '⛷️', blurb: 'Summit-selfie energy', group: 'Teams', background: 'ski-slope', attire: 'ski-jacket', headwear: 'ski-goggles', finish: 'photo', framing: 'three-quarter', pose: 'shoulder to shoulder on the summit with poles planted' },
  { id: 'surf-crew', label: 'Surf Crew', icon: '🏄', blurb: 'Dawn-patrol lineup', group: 'Teams', background: 'surf-break', attire: 'rash-guard', headwear: 'none', finish: 'film-70s', framing: 'three-quarter', pose: 'standing in a row with surfboards upright beside them' },
  { id: 'volleyball-team', label: 'Beach Volleyball Team', icon: '🏐', blurb: 'Sand-court champions', group: 'Teams', background: 'sunny-boardwalk', attire: 'rash-guard', headwear: 'visor', finish: 'photo', framing: 'three-quarter', pose: 'huddled around a beach ball, sun-lit and grinning' },
  { id: 'boxing-stable', label: 'Boxing Stable', icon: '🥊', blurb: 'Ringside fighters', group: 'Teams', background: 'boxing-ring', attire: 'boxing-robe', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'posed in the ring with gloved fists raised' },
  // ── History & Fantasy (10) ───────────────────────────────────────────────
  { id: 'samurai-clan', label: 'Samurai Clan', icon: '🏯', blurb: 'Armored clan portrait', group: 'History & Fantasy', background: 'samurai-dojo', attire: 'samurai-armor', headwear: 'kabuto', finish: 'oil', framing: 'three-quarter', pose: 'arranged in formal rank, the leader seated and the others standing with sheathed katanas' },
  { id: 'ninja-clan', label: 'Ninja Clan', icon: '🥷', blurb: 'Shadow-gate silence', group: 'History & Fantasy', background: 'kyoto-gate', attire: 'ninja-shozoku', headwear: 'ninja-hood', finish: 'cinematic', framing: 'three-quarter', pose: 'crouched and standing in a staggered formation in the torii tunnel' },
  { id: 'viking-raiders', label: 'Viking Raiders', icon: '🛡️', blurb: 'Longhouse war band', group: 'History & Fantasy', background: 'viking-longhouse', attire: 'work-canvas', headwear: 'viking-helm', finish: 'oil', framing: 'three-quarter', pose: 'gathered around the fire with axes and round shields' },
  { id: 'round-table', label: 'Knights of the Round Table', icon: '⚔️', blurb: 'Castle-hall oath', group: 'History & Fantasy', background: 'castle-hall', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'wide', pose: 'standing around a great round table with swords point-down' },
  { id: 'wizard-council', label: 'Wizard Council', icon: '🧙', blurb: 'Robed conclave', group: 'History & Fantasy', background: 'wizard-tower', attire: 'wizard-robes', headwear: 'wizard-hat', finish: 'oil', framing: 'three-quarter', pose: 'gathered around a glowing orrery with staffs in hand' },
  { id: 'adventure-party', label: 'Adventuring Party', icon: '🐉', blurb: 'Tabletop-campaign crew', group: 'History & Fantasy', background: 'dragon-lair', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'wide', pose: 'posed as a fantasy adventuring party, each in a different role: a knight, a ranger with a bow, a mage with a staff, a rogue with a lantern' },
  { id: 'royal-court', label: 'Royal Court', icon: '👑', blurb: 'Throne-room dynasty', group: 'History & Fantasy', background: 'throne-room', attire: 'royal-robes', headwear: 'crown', finish: 'oil', framing: 'wide', pose: 'arranged with the monarchs seated on thrones and the rest of the court standing around them' },
  { id: 'pharaoh-dynasty', label: 'Pharaoh Dynasty', icon: '𓂀', blurb: 'Temple-gold lineage', group: 'History & Fantasy', background: 'egyptian-temple', attire: 'toga', headwear: 'nemes', finish: 'oil', framing: 'three-quarter', pose: 'arranged in a formal frontal row with crooks and flails crossed' },
  { id: 'roman-senate', label: 'Roman Senate', icon: '🏺', blurb: 'Forum assembly', group: 'History & Fantasy', background: 'roman-forum', attire: 'toga', headwear: 'laurel-wreath', finish: 'oil', framing: 'three-quarter', pose: 'gathered on the forum steps mid-oration' },
  { id: 'elven-court', label: 'Elven Court', icon: '🧝', blurb: 'Silver-glade assembly', group: 'History & Fantasy', background: 'elven-glade', attire: 'elven-leathers', headwear: 'laurel-wreath', finish: 'oil', framing: 'three-quarter', pose: 'standing among the silver trees with longbows at their sides' },
  // ── Life & Occasion (6) ──────────────────────────────────────────────────
  { id: 'family-holiday', label: 'Holiday Card', icon: '🎄', blurb: 'Hearth-side family', group: 'Life & Occasion', background: 'holiday-hearth', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'gathered by the fireplace in matching cozy sweaters' },
  { id: 'wedding-party', label: 'Wedding Party', icon: '💍', blurb: 'Garden-aisle elegance', group: 'Life & Occasion', background: 'palace-garden', attire: 'tuxedo', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'arranged as a formal wedding party portrait with bouquets and boutonnieres' },
  { id: 'graduation-class', label: 'Graduation Class', icon: '🎓', blurb: 'Caps in the air', group: 'Life & Occasion', background: 'lecture-hall', attire: 'academic-gown', headwear: 'graduation-cap', finish: 'photo', framing: 'three-quarter', pose: 'tossing graduation caps into the air together' },
  { id: 'board-of-directors', label: 'Board of Directors', icon: '🏛️', blurb: 'Annual-report lineup', group: 'Life & Occasion', background: 'boardroom', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'seated and standing around the boardroom table in an annual-report portrait' },
  { id: 'founding-team', label: 'Founding Team', icon: '🚀', blurb: 'Whiteboard-launch crew', group: 'Life & Occasion', background: 'coworking', attire: 'smart-creative', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'gathered around a whiteboard with laptops and coffee' },
  { id: 'firehouse-crew', label: 'Firehouse Crew', icon: '🚒', blurb: 'Engine-bay lineup', group: 'Life & Occasion', background: 'fire-station', attire: 'firefighter-turnout', headwear: 'firefighter-helmet', finish: 'photo', framing: 'wide', pose: 'lined up in front of the engine with helmets under their arms' },
];
