/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * DATE/TIME           | AUTHOR                                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 2026-07-17 20:30:00 | roger.murphy@emeraldcoastsystemsgroup.com   | EXACTLY 100 curated profiles (test-enforced), grouped: professional = Business Formal / Business Casual / Slice of Life / Work Environments / Occasion & Classic (55); character = The Classics / History / Working Legends / Fantasy & Fun (45). Every preset is just a combination of layer ids + a pose — all five layers remain overridable per generation, so these are entry points into millions of permutations, not a ceiling. All v1.1 preset ids preserved (gallery rows reference them).
 */

/** @description A preset = a named combination of layer ids + a pose (what the hands do). */
export interface PortraitPreset {
  id: string;
  label: string;
  icon: string;
  blurb: string;
  /** Picker chip group this preset renders under. */
  group: string;
  background: string;
  attire: string;
  headwear: string;
  finish: string;
  framing: string;
  /** What the hands/pose are doing — a prop override replaces this. */
  pose: string;
}

/** @description 55 formal-people profiles (professional mode — the subject as themselves). */
export const PROFESSIONAL_PRESETS: readonly PortraitPreset[] = [
  // ── Business Formal (12) ─────────────────────────────────────────────────
  { id: 'linkedin', label: 'LinkedIn Classic', icon: '💼', blurb: 'Bright, friendly, hire-me', group: 'Business Formal', background: 'office-bokeh', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'executive', label: 'The Executive', icon: '🏛️', blurb: 'Navy backdrop, quiet power', group: 'Business Formal', background: 'corporate-navy', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms confidently crossed with both hands visible' },
  { id: 'board-chair', label: 'Board Chair', icon: '🪑', blurb: 'Corner office gravitas', group: 'Business Formal', background: 'corner-office', attire: 'three-piece', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a leather chair back' },
  { id: 'keynote', label: 'Keynote Speaker', icon: '🎤', blurb: 'On stage, mid-idea', group: 'Business Formal', background: 'conference-stage', attire: 'turtleneck-blazer', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'hands raised mid-gesture as if making a point' },
  { id: 'banker', label: 'The Banker', icon: '🏦', blurb: 'Marble-hall trust', group: 'Business Formal', background: 'bank-hall', attire: 'pinstripe', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands lightly clasped in front' },
  { id: 'consultant', label: 'The Consultant', icon: '📊', blurb: 'Glass lobby, brisk', group: 'Business Formal', background: 'glass-lobby', attire: 'navy-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand holding a slim portfolio at the side' },
  { id: 'attorney', label: 'The Attorney', icon: '⚖️', blurb: 'Law library, composed', group: 'Business Formal', background: 'law-library', attire: 'gray-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a stack of case reports' },
  { id: 'diplomat', label: 'The Diplomat', icon: '🌐', blurb: 'Measured, international', group: 'Business Formal', background: 'cream-studio', attire: 'overcoat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands gently folded' },
  { id: 'campaign', label: 'Campaign Portrait', icon: '🗳️', blurb: 'Approachable authority', group: 'Business Formal', background: 'clean-white', attire: 'power-blazer', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'annual-report', label: 'Annual Report', icon: '📈', blurb: 'Trading-floor energy', group: 'Business Formal', background: 'trading-floor', attire: 'silk-blouse', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms loosely crossed' },
  { id: 'skyline-exec', label: 'Skyline Executive', icon: '🌇', blurb: 'Rooftop at dusk', group: 'Business Formal', background: 'rooftop-terrace', attire: 'dark-suit', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'one hand in a trouser pocket' },
  { id: 'city-power', label: 'City Power Walk', icon: '🚕', blurb: 'Street-level confidence', group: 'Business Formal', background: 'city-street', attire: 'trench-coat', headwear: 'none', finish: 'cinematic', framing: 'three-quarter', pose: 'mid-stride, one hand holding a coat lapel' },
  // ── Business Casual (10) ─────────────────────────────────────────────────
  { id: 'startup-founder', label: 'Startup Founder', icon: '🚀', blurb: 'Loft, plants, hustle', group: 'Business Casual', background: 'coworking', attire: 'plain-tee', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms comfortably crossed' },
  { id: 'tech-lead', label: 'Tech Lead', icon: '💻', blurb: 'Server-room glow', group: 'Business Casual', background: 'server-room', attire: 'hoodie', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'one hand resting on a server rack' },
  { id: 'creative-director', label: 'Creative Director', icon: '🎨', blurb: 'Studio, opinionated', group: 'Business Casual', background: 'art-studio', attire: 'smart-creative', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand thoughtfully at the chin' },
  { id: 'architect', label: 'The Architect', icon: '📐', blurb: 'Site + rolled plans', group: 'Business Casual', background: 'construction-site', attire: 'turtleneck-blazer', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'a roll of blueprints tucked under one arm' },
  { id: 'creative', label: 'Creative Pro', icon: '🖌️', blurb: 'Smart-creative, approachable', group: 'Business Casual', background: 'studio-gray', attire: 'smart-creative', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'podcast-host', label: 'Podcast Host', icon: '🎙️', blurb: 'Mic + warm light', group: 'Business Casual', background: 'music-room', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a vintage microphone gripped in one hand' },
  { id: 'author-photo', label: 'Author Jacket', icon: '📖', blurb: 'Back-cover thoughtful', group: 'Business Casual', background: 'bookstore', attire: 'cozy-sweater', headwear: 'none', finish: 'bw', framing: 'half-body', pose: 'arms folded softly, head slightly tilted' },
  { id: 'professor', label: 'The Professor', icon: '🎓', blurb: 'Lecture-hall chalk dust', group: 'Business Casual', background: 'lecture-hall', attire: 'sweater-vest', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'an open book held in one hand' },
  { id: 'whiteboard', label: 'Whiteboard Session', icon: '🖊️', blurb: 'Mid-brainstorm', group: 'Business Casual', background: 'coworking', attire: 'oxford-chinos', headwear: 'none', finish: 'photo', framing: 'three-quarter', pose: 'one hand holding a marker mid-gesture' },
  { id: 'casual-friday', label: 'Casual Friday', icon: '🧢', blurb: 'Relaxed but sharp', group: 'Business Casual', background: 'office-bokeh', attire: 'denim-blazer', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  // ── Slice of Life (12) ───────────────────────────────────────────────────
  { id: 'coffee-morning', label: 'Coffee Shop Morning', icon: '☕', blurb: 'First-sip serenity', group: 'Slice of Life', background: 'cozy-cafe', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'both hands wrapped around a steaming mug' },
  { id: 'sunday-market', label: 'Sunday Market', icon: '🥕', blurb: 'Basket of good things', group: 'Slice of Life', background: 'farmers-market', attire: 'linen-shirt', headwear: 'sun-hat', finish: 'photo', framing: 'three-quarter', pose: 'a woven basket of produce on one arm' },
  { id: 'park-stroll', label: 'Autumn Stroll', icon: '🍁', blurb: 'Leaves + long light', group: 'Slice of Life', background: 'autumn-park', attire: 'parka', headwear: 'beanie', finish: 'photo', framing: 'three-quarter', pose: 'hands tucked warmly in pockets' },
  { id: 'home-cook', label: 'Home Cook', icon: '🍳', blurb: 'Kitchen at golden hour', group: 'Slice of Life', background: 'home-kitchen', attire: 'plain-tee', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a wooden spoon raised for a taste' },
  { id: 'bookworm', label: 'The Bookworm', icon: '📚', blurb: 'Window-seat afternoons', group: 'Slice of Life', background: 'reading-nook', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'an open book held in both hands' },
  { id: 'natural', label: 'Natural Light', icon: '🌤️', blurb: 'Golden-hour, relaxed', group: 'Slice of Life', background: 'outdoor-golden', attire: 'business-casual', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'beach-day', label: 'Beach Day', icon: '🏝️', blurb: 'Salt air, no meetings', group: 'Slice of Life', background: 'tropical-beach', attire: 'hawaiian-shirt', headwear: 'sun-hat', finish: 'photo', framing: 'half-body', pose: 'sunglasses dangling from one hand' },
  { id: 'trail-day', label: 'Trail Day', icon: '🥾', blurb: 'Summit-sized grin', group: 'Slice of Life', background: 'mountain-peak', attire: 'hiking-gear', headwear: 'baseball-cap', finish: 'photo', framing: 'three-quarter', pose: 'thumbs hooked in the pack straps' },
  { id: 'rainy-window', label: 'Rainy Day', icon: '🌧️', blurb: 'Cozy melancholy', group: 'Slice of Life', background: 'cozy-cafe', attire: 'raincoat', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'both hands cupping a warm drink' },
  { id: 'garden-hour', label: 'Garden Hour', icon: '🪴', blurb: 'Greenhouse warmth', group: 'Slice of Life', background: 'greenhouse', attire: 'flannel', headwear: 'sun-hat', finish: 'photo', framing: 'half-body', pose: 'a potted seedling cradled in both hands' },
  { id: 'porch-evening', label: 'Porch Evening', icon: '🏡', blurb: 'Lemonade light', group: 'Slice of Life', background: 'front-porch', attire: 'summer-dress', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'one hand resting on the porch rail' },
  { id: 'holiday-card', label: 'Holiday Card', icon: '🎄', blurb: 'Hearth + cheer', group: 'Slice of Life', background: 'holiday-hearth', attire: 'cozy-sweater', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a mug of cocoa raised in a small toast' },
  // ── Work Environments (12) ───────────────────────────────────────────────
  { id: 'surgeon', label: 'The Surgeon', icon: '🩻', blurb: 'OR-ready calm', group: 'Work Environments', background: 'operating-room', attire: 'surgeon-gown', headwear: 'surgical-cap', finish: 'photo', framing: 'half-body', pose: 'gloved hands held raised and ready' },
  { id: 'er-nurse', label: 'The Nurse', icon: '🩺', blurb: 'Ward-shift backbone', group: 'Work Environments', background: 'hospital-ward', attire: 'scrubs', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a stethoscope held lightly in one hand' },
  { id: 'firefighter', label: 'The Firefighter', icon: '🚒', blurb: 'Turnout + engine bay', group: 'Work Environments', background: 'fire-station', attire: 'firefighter-turnout', headwear: 'firefighter-helmet', finish: 'photo', framing: 'half-body', pose: 'helmet strap loose, one gloved hand at the jacket clasp' },
  { id: 'officer-duty', label: 'The Officer', icon: '👮', blurb: 'Precinct portrait', group: 'Work Environments', background: 'police-precinct', attire: 'police-uniform', headwear: 'police-cap', finish: 'photo', framing: 'half-body', pose: 'hands clasped behind the back, shoulders square' },
  { id: 'captain-pilot', label: 'The Pilot', icon: '✈️', blurb: 'Four stripes, tarmac dawn', group: 'Work Environments', background: 'airport-tarmac', attire: 'pilot-uniform', headwear: 'peaked-cap', finish: 'photo', framing: 'half-body', pose: 'a flight case held in one hand' },
  { id: 'teacher', label: 'The Teacher', icon: '🏫', blurb: 'Chalkboard hero', group: 'Work Environments', background: 'classroom', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a piece of chalk raised mid-lesson' },
  { id: 'scientist', label: 'The Scientist', icon: '🧪', blurb: 'Lab-light focus', group: 'Work Environments', background: 'laboratory', attire: 'lab-coat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a flask of colored liquid raised for inspection' },
  { id: 'site-engineer', label: 'Site Engineer', icon: '🏗️', blurb: 'Crane-line horizon', group: 'Work Environments', background: 'construction-site', attire: 'hi-vis', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'a rolled drawing tucked under one arm' },
  { id: 'chef-de-cuisine', label: 'Chef de Cuisine', icon: '👨‍🍳', blurb: 'Pass-side command', group: 'Work Environments', background: 'kitchen', attire: 'chef-whites', headwear: 'chef-toque', finish: 'photo', framing: 'half-body', pose: 'arms crossed while holding a wooden spoon' },
  { id: 'barista-craft', label: 'The Barista', icon: '☕', blurb: 'Latte-art pride', group: 'Work Environments', background: 'cozy-cafe', attire: 'barista-apron', headwear: 'flat-cap', finish: 'photo', framing: 'half-body', pose: 'a finished latte presented in both hands' },
  { id: 'modern-farmer', label: 'Modern Farmer', icon: '🚜', blurb: 'Barn-door morning', group: 'Work Environments', background: 'farm-barn', attire: 'farmer-overalls', headwear: 'baseball-cap', finish: 'photo', framing: 'half-body', pose: 'thumbs hooked in the overall straps' },
  { id: 'master-mechanic', label: 'The Mechanic', icon: '🔧', blurb: 'Lift-bay confidence', group: 'Work Environments', background: 'auto-garage', attire: 'coveralls', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a wrench resting across one shoulder' },
  // ── Occasion & Classic (9) ───────────────────────────────────────────────
  { id: 'classic-studio', label: 'Classic Studio', icon: '🎞️', blurb: 'Timeless gray, your clothes', group: 'Occasion & Classic', background: 'studio-gray', attire: 'keep', headwear: 'none', finish: 'photo', framing: 'headshot', pose: '' },
  { id: 'editorial-bw', label: 'Editorial B&W', icon: '⬛', blurb: 'Dramatic black & white', group: 'Occasion & Classic', background: 'studio-gray', attire: 'keep', headwear: 'none', finish: 'bw', framing: 'headshot', pose: '' },
  { id: 'black-tie', label: 'Black Tie', icon: '🥂', blurb: 'Tuxedo, gala-ready', group: 'Occasion & Classic', background: 'corporate-navy', attire: 'tuxedo', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'graduate', label: 'The Graduate', icon: '🎓', blurb: 'Gown, cap, diploma in hand', group: 'Occasion & Classic', background: 'library', attire: 'academic-gown', headwear: 'graduation-cap', finish: 'photo', framing: 'half-body', pose: 'holding a rolled diploma in both hands' },
  { id: 'doctor', label: 'The Doctor', icon: '🩺', blurb: 'White coat, trusted', group: 'Occasion & Classic', background: 'clean-white', attire: 'doctor-coat', headwear: 'none', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'judge', label: 'The Judge', icon: '⚖️', blurb: 'Robes, gravitas', group: 'Occasion & Classic', background: 'courtroom', attire: 'judge-robe', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'hands gently folded' },
  { id: 'officer', label: 'Dress Uniform', icon: '🎖️', blurb: 'Medals, formal military', group: 'Occasion & Classic', background: 'studio-gray', attire: 'dress-uniform', headwear: 'peaked-cap', finish: 'photo', framing: 'half-body', pose: '' },
  { id: 'vintage', label: 'Vintage Tintype', icon: '🎩', blurb: 'Sepia, top hat, 1890s', group: 'Occasion & Classic', background: 'studio-gray', attire: 'dark-suit', headwear: 'top-hat', finish: 'tintype', framing: 'half-body', pose: '' },
  { id: 'gallery-opening', label: 'Gallery Opening', icon: '🖼️', blurb: 'Noir evening elegance', group: 'Occasion & Classic', background: 'spotlight-black', attire: 'evening-gown', headwear: 'none', finish: 'noir', framing: 'three-quarter', pose: 'a champagne flute held lightly in one hand' },
];

/** @description 45 character presets (face on a human-type body, hands in frame). */
export const CHARACTER_PRESETS: readonly PortraitPreset[] = [
  // ── The Classics (12) ────────────────────────────────────────────────────
  { id: 'american-gothic', label: 'American Gothic', icon: '🌾', blurb: 'Stern farmer, pitchfork in hand', group: 'The Classics', background: 'farmhouse', attire: 'farmer-overalls', headwear: 'none', finish: 'regionalist', framing: 'half-body', pose: 'one hand gripping a pitchfork upright, the other at the lapel, with a stern expression' },
  { id: 'steel-mill', label: 'Steel Mill', icon: '🏭', blurb: 'Sparks, gloves, hard hat', group: 'The Classics', background: 'steel-mill', attire: 'work-canvas', headwear: 'hard-hat', finish: 'photo', framing: 'half-body', pose: 'one gloved hand gripping a glowing steel rod' },
  { id: 'renaissance', label: 'Renaissance Noble', icon: '👑', blurb: 'Velvet, ruff collar, oil paint', group: 'The Classics', background: 'castle-hall', attire: 'renaissance-doublet', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'hands gently folded at the waist' },
  { id: 'astronaut', label: 'Astronaut', icon: '🚀', blurb: 'Official crew portrait', group: 'The Classics', background: 'starfield', attire: 'spacesuit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a space helmet held under one arm, the other gloved hand resting at the chest' },
  { id: 'sea-captain', label: 'Sea Captain', icon: '⚓', blurb: 'Peacoat, wheel, stormy sea', group: 'The Classics', background: 'stormy-harbor', attire: 'peacoat', headwear: 'captains-cap', finish: 'oil', framing: 'half-body', pose: "one weathered hand resting on a ship's wheel" },
  { id: 'victorian-general', label: 'Victorian General', icon: '🎖️', blurb: 'Medals, epaulettes, sword', group: 'The Classics', background: 'studio-gray', attire: 'dress-uniform', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'one gloved hand resting on a sword hilt' },
  { id: 'ceo', label: 'The CEO', icon: '💼', blurb: 'Boardroom, arms crossed', group: 'The Classics', background: 'boardroom', attire: 'dark-suit', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'arms confidently crossed with both hands visible' },
  { id: 'chef', label: 'Head Chef', icon: '👨‍🍳', blurb: 'Whites, toque, kitchen', group: 'The Classics', background: 'kitchen', attire: 'chef-whites', headwear: 'chef-toque', finish: 'photo', framing: 'half-body', pose: 'arms crossed while holding a wooden spoon' },
  { id: 'wizard', label: 'Archmage', icon: '🧙', blurb: 'Robes, staff, candlelight', group: 'The Classics', background: 'fireside-study', attire: 'wizard-robes', headwear: 'wizard-hat', finish: 'oil', framing: 'half-body', pose: 'one hand holding a carved wooden staff, the other cradling a faintly glowing orb' },
  { id: 'rockstar', label: 'Rock Star', icon: '🎸', blurb: '80s album cover energy', group: 'The Classics', background: 'stage', attire: 'leather-jacket', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'holding an electric guitar with both hands' },
  { id: 'cowboy', label: 'Cowboy', icon: '🤠', blurb: 'Duster, lasso, dusk prairie', group: 'The Classics', background: 'prairie-dusk', attire: 'duster-coat', headwear: 'cowboy-hat', finish: 'photo', framing: 'half-body', pose: 'one gloved hand holding a coiled lasso' },
  { id: 'knight', label: 'Knight', icon: '⚔️', blurb: 'Plate armor, castle hall', group: 'The Classics', background: 'castle-hall', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a plumed helmet held under one arm, the gauntleted hand resting on a sword pommel' },
  // ── History (10) ─────────────────────────────────────────────────────────
  { id: 'pharaoh', label: 'Pharaoh', icon: '𓂀', blurb: 'Nemes, temple gold', group: 'History', background: 'egyptian-temple', attire: 'toga', headwear: 'nemes', finish: 'oil', framing: 'half-body', pose: 'arms crossed holding a crook and flail' },
  { id: 'roman-senator', label: 'Roman Senator', icon: '🏺', blurb: 'Toga, forum, laurels', group: 'History', background: 'roman-forum', attire: 'toga', headwear: 'laurel-wreath', finish: 'oil', framing: 'half-body', pose: 'one arm raised in oration' },
  { id: 'viking', label: 'Viking Jarl', icon: '🛡️', blurb: 'Longhouse firelight', group: 'History', background: 'viking-longhouse', attire: 'work-canvas', headwear: 'viking-helm', finish: 'oil', framing: 'half-body', pose: 'both hands resting on the haft of a broad axe' },
  { id: 'samurai', label: 'Samurai', icon: '🏯', blurb: 'Dojo stillness', group: 'History', background: 'samurai-dojo', attire: 'kimono', headwear: 'kabuto', finish: 'oil', framing: 'half-body', pose: 'one hand resting on the katana at the waist' },
  { id: 'musketeer', label: 'Musketeer', icon: '🤺', blurb: 'Plume + panache', group: 'History', background: 'castle-hall', attire: 'pirate-coat', headwear: 'tricorn', finish: 'oil', framing: 'three-quarter', pose: 'one hand on a rapier hilt, the other sweeping the hat brim' },
  { id: 'detective', label: 'Victorian Detective', icon: '🔎', blurb: 'Deerstalker deduction', group: 'History', background: 'fireside-study', attire: 'trench-coat', headwear: 'deerstalker', finish: 'noir', framing: 'half-body', pose: 'a brass magnifying glass raised in one hand' },
  { id: 'gangster', label: '1920s Boss', icon: '🥃', blurb: 'Speakeasy shadows', group: 'History', background: 'speakeasy', attire: 'gatsby-tux', headwear: 'fedora', finish: 'noir', framing: 'half-body', pose: 'one hand adjusting a cufflink' },
  { id: 'aviator', label: 'WWI Aviator', icon: '🛩️', blurb: 'Goggles + grit', group: 'History', background: 'airport-tarmac', attire: 'flight-suit', headwear: 'aviator-cap', finish: 'tintype', framing: 'half-body', pose: 'leather gloves clasped in one hand' },
  { id: 'monk', label: 'Medieval Scribe', icon: '📜', blurb: 'Candlelit devotion', group: 'History', background: 'cathedral', attire: 'wizard-robes', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a feather quill poised in one hand over parchment' },
  { id: 'tudor-monarch', label: 'Tudor Monarch', icon: '👑', blurb: 'Throne-room command', group: 'History', background: 'throne-room', attire: 'renaissance-doublet', headwear: 'crown', finish: 'oil', framing: 'three-quarter', pose: 'one hand bearing a golden scepter' },
  // ── Working Legends (10) ─────────────────────────────────────────────────
  { id: 'lumberjack', label: 'Lumberjack', icon: '🪓', blurb: 'Flannel + felling axe', group: 'Working Legends', background: 'snowy-pines', attire: 'flannel', headwear: 'beanie', finish: 'photo', framing: 'half-body', pose: 'a felling axe resting across one shoulder' },
  { id: 'blacksmith', label: 'Blacksmith', icon: '🔨', blurb: 'Forge-glow muscle', group: 'Working Legends', background: 'steel-mill', attire: 'leather-apron', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a blacksmith hammer resting head-down under one hand' },
  { id: 'fisherman', label: 'The Fisherman', icon: '🎣', blurb: 'Slicker + sea spray', group: 'Working Legends', background: 'fishing-harbor', attire: 'fisherman-slicker', headwear: 'captains-cap', finish: 'photo', framing: 'half-body', pose: 'a fishing rod shouldered in one hand' },
  { id: 'conductor', label: 'Train Conductor', icon: '🚂', blurb: 'Brass buttons, right on time', group: 'Working Legends', background: 'metro-platform', attire: 'conductor-uniform', headwear: 'peaked-cap', finish: 'tintype', framing: 'half-body', pose: 'one hand consulting a gold pocket watch on a chain' },
  { id: 'mad-scientist', label: 'Mad Scientist', icon: '⚗️', blurb: 'Eureka at midnight', group: 'Working Legends', background: 'laboratory', attire: 'lab-coat', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a bubbling flask raised triumphantly in one hand, hair slightly wild' },
  { id: 'librarian', label: 'Grand Librarian', icon: '📚', blurb: 'Keeper of the stacks', group: 'Working Legends', background: 'library', attire: 'cardigan', headwear: 'none', finish: 'photo', framing: 'half-body', pose: 'a tall stack of books balanced in both arms' },
  { id: 'ringmaster', label: 'Ringmaster', icon: '🎪', blurb: 'Big-top showmanship', group: 'Working Legends', background: 'circus-ring', attire: 'gatsby-tux', headwear: 'top-hat', finish: 'cinematic', framing: 'three-quarter', pose: 'one arm flung wide in welcome, the other tipping the hat' },
  { id: 'astronomer', label: 'Astronomer', icon: '🔭', blurb: 'Charting the heavens', group: 'Working Legends', background: 'moon-base', attire: 'cozy-sweater', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'a brass spyglass telescope held in both hands' },
  { id: 'explorer', label: 'The Explorer', icon: '🧭', blurb: 'Uncharted-map energy', group: 'Working Legends', background: 'desert-dunes', attire: 'park-ranger', headwear: 'pith-helmet', finish: 'tintype', framing: 'half-body', pose: 'an unrolled map held in both hands' },
  { id: 'park-warden', label: 'Park Warden', icon: '🌲', blurb: 'Trailhead steward', group: 'Working Legends', background: 'forest-path', attire: 'park-ranger', headwear: 'flat-cap', finish: 'photo', framing: 'half-body', pose: 'one hand resting on a wooden trail sign' },
  // ── Fantasy & Fun (13) ───────────────────────────────────────────────────
  { id: 'pirate-captain', label: 'Pirate Captain', icon: '🏴‍☠️', blurb: 'Deck, cutlass, horizon', group: 'Fantasy & Fun', background: 'pirate-deck', attire: 'pirate-coat', headwear: 'tricorn', finish: 'oil', framing: 'half-body', pose: 'one boot up on a cannon, hand resting on a cutlass hilt' },
  { id: 'superhero', label: 'Superhero', icon: '🦸', blurb: 'Cape-flare skyline', group: 'Fantasy & Fun', background: 'rooftop-terrace', attire: 'tracksuit', headwear: 'none', finish: 'pop-art', framing: 'three-quarter', pose: 'fists planted on hips, cape rippling' },
  { id: 'vampire-count', label: 'Vampire Count', icon: '🦇', blurb: 'Gothic-manor menace', group: 'Fantasy & Fun', background: 'victorian-parlor', attire: 'gatsby-tux', headwear: 'none', finish: 'noir', framing: 'half-body', pose: 'a candelabra raised in one pale hand' },
  { id: 'steampunk', label: 'Steampunk Inventor', icon: '⚙️', blurb: 'Brass, gears, altitude', group: 'Fantasy & Fun', background: 'airship-deck', attire: 'leather-apron', headwear: 'aviator-cap', finish: 'tintype', framing: 'half-body', pose: 'a wrench in one hand, the other on a brass valve wheel' },
  { id: 'elf-ranger', label: 'Elf Ranger', icon: '🏹', blurb: 'Enchanted-forest watch', group: 'Fantasy & Fun', background: 'enchanted-forest', attire: 'hiking-gear', headwear: 'none', finish: 'oil', framing: 'three-quarter', pose: 'a longbow held at the side, one hand at the quiver' },
  { id: 'dragon-keeper', label: 'Dragon Keeper', icon: '🐉', blurb: 'Hoard-light bravado', group: 'Fantasy & Fun', background: 'dragon-lair', attire: 'plate-armor', headwear: 'none', finish: 'oil', framing: 'half-body', pose: 'a lantern raised in one gauntleted hand' },
  { id: 'royal-portrait', label: 'Royal Portrait', icon: '👑', blurb: 'Crown + gilded frame', group: 'Fantasy & Fun', background: 'throne-room', attire: 'evening-gown', headwear: 'crown', finish: 'oil', framing: 'three-quarter', pose: 'hands composed regally in the lap' },
  { id: 'jazz-legend', label: 'Jazz Legend', icon: '🎷', blurb: 'Smoky-club cool', group: 'Fantasy & Fun', background: 'speakeasy', attire: 'gatsby-tux', headwear: 'fedora', finish: 'bw', framing: 'half-body', pose: 'a vintage microphone gripped in one hand' },
  { id: 'disco-star', label: 'Disco Star', icon: '🪩', blurb: 'Saturday-night shimmer', group: 'Fantasy & Fun', background: 'neon-arcade', attire: 'tracksuit', headwear: 'none', finish: 'pop-art', framing: 'three-quarter', pose: 'one arm pointed skyward in the classic disco pose' },
  { id: 'surf-legend', label: 'Surf Legend', icon: '🏄', blurb: 'Endless-summer salt', group: 'Fantasy & Fun', background: 'ocean-cliff', attire: 'hawaiian-shirt', headwear: 'none', finish: 'polaroid', framing: 'three-quarter', pose: 'a surfboard tucked under one arm' },
  { id: 'race-driver', label: 'Race Driver', icon: '🏎️', blurb: 'Podium champagne', group: 'Fantasy & Fun', background: 'auto-garage', attire: 'coveralls', headwear: 'baseball-cap', finish: 'cinematic', framing: 'half-body', pose: 'a racing helmet held under one arm' },
  { id: 'opera-diva', label: 'Opera Star', icon: '🎭', blurb: 'Aria mid-flight', group: 'Fantasy & Fun', background: 'spotlight-black', attire: 'evening-gown', headwear: 'none', finish: 'oil', framing: 'three-quarter', pose: 'both arms lifted mid-aria' },
  { id: 'deep-diver', label: 'Reef Explorer', icon: '🐠', blurb: 'Sunbeam shallows', group: 'Fantasy & Fun', background: 'underwater-reef', attire: 'spacesuit', headwear: 'none', finish: 'cinematic', framing: 'half-body', pose: 'an old brass diving helmet held under one arm' },
];
