/** Actual app screens and cockpit relay; fixture records, no provider calls or business writes. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const core=path.resolve(__dirname,'../../oshal'),store=path.resolve(__dirname,'..');
const express=require(path.join(core,'node_modules/express')),yaml=require(path.join(core,'node_modules/js-yaml'));
const {chromium}=require(path.join(core,'node_modules/playwright'));
const files={presentations:'presentations.html','marketing-engine':'marketing-engine.html','venture-plan':'venture.html',travel:'travel-app.html',purchasing:'shopping-chat.html',eats:'eats-app.html',rides:'rides-app.html',switchboard:'switchboard-compose.html',social:'social-composer.html',video:'video.html',vids:null,movies:'movies-app.html',spotify:'spotify-app.html',finance:'finance.html',payments:'payments.html',payroll:'payroll.html'};
for(const name of ['youtube-kids','dnd','game-show','pumpkin','bake-off','sports-edge','little-monsters','calendar','capability-ideator'])files[name]='review.html';
files['career-hunter']='review.html';files['job-apply']='review.html';
files.camera='camera-ops.html';files['aero-lab']='aero-lab.html';
files['brand-graphics']='review.html';files['creative-studio']='review.html';files['daily-trade-recap']='review.html';
files.kalshi='kalshi.html';files['intelligent-trades']='trading.html';
const folder=name=>name==='intelligent-trades'?'trading':name;
const manifests=[...Object.keys(files),'world'].map(name=>yaml.load(fs.readFileSync(path.join(store,folder(name),'oshal-app.yaml'),'utf8')));
// Each fixture screen uses the same declared URL as its real receiving surface.
for(const m of manifests) if(m.name==='switchboard') m.ui.static.sort((a,b)=>Number(b.toolName==='switchboard-compose')-Number(a.toolName==='switchboard-compose'));
const offers=m=>(m.integrations?.offers||[]).map(o=>{const target=manifests.find(a=>a.name===o.targetApp),receiver=target?.integrations?.accepts?.find(r=>r.id===o.targetAction&&r.version===o.version&&r.contextType===o.contextType);return {...o,sourceApp:m.name,state:receiver?'available':'unavailable',surface:receiver?.surface,surfaceUrl:target?.ui.static.find(s=>s.toolName===receiver?.surface)?.iframeUrl,fields:receiver?.fields};});
const entries=manifests.map(m=>({name:m.name,displayName:m.displayName,suite:m.suite,kind:'app',members:[m.name],firstSurface:m.ui.static[0].toolName,firstSurfaceUrl:m.ui.static[0].iframeUrl,todos:[],integrationSources:[{app:m.name,surfaces:m.ui.static.map(s=>({name:s.toolName,url:s.iframeUrl})),offers:offers(m)}],summary:m.name==='world'?[{app:'world',path:'/summary',itemsPointer:'/items',surfaces:['world-dashboard'],integrations:offers(m)}]:[]}));
const app=express();let writes=[];
app.get('/api/social/signals/ui',(_req,res)=>res.sendFile(path.join(store,'social/tools/social-signals.html')));
app.get('/api/social/signals',(_req,res)=>res.json({signals:[{subject:'Selected social notification',snippet:'Selected notification evidence',receivedAt:'2026-09-10',from:'source@example.test'}]}));
for(const appName of ['career-hunter','job-apply','youtube-kids','dnd','game-show','pumpkin','bake-off','sports-edge','little-monsters','calendar','capability-ideator'])app.get('/api/'+appName+'/home-summary',(_req,res)=>res.json({metrics:[],partial:false,items:[{text:'Selected career evidence',actions:[{integration:'prepare-document',context:{title:'Selected application',notes:'Verified fixture submission; review before following up.'}}]}]}));
app.get('/api/aero-lab/app.js',(_req,res)=>res.sendFile(path.join(store,'aero-lab/tools/aero-lab.js')));
app.get('/api/aero-lab/geometry.js',(_req,res)=>res.sendFile(path.join(store,'aero-lab/tools/aero-lab-geometry.js')));
app.get('/api/camera/home-summary',(_req,res)=>res.json({partial:false,items:[{text:'Selected camera',actions:[{integration:'prepare-document',context:{title:'Selected camera',notes:'Selected rejected command; no physical result is established.'}}]}]}));

let stockReads=0;
app.get('/api/kalshi/alerts',(_req,res)=>res.json({alerts:[{ticker:'SELECTED-MARKET',strength:'playable',delivered:false,created_at:'2026-09-01',detail:{title:'Selected market evidence'}}]}));
for(const suffix of ['scan','settings','trends'])app.get('/api/kalshi/'+suffix,(_req,res)=>res.status(503).json({error:'Fixture source unavailable'}));
app.get('/api/trading/research/:symbol',(req,res)=>{stockReads++;res.json({symbol:req.params.symbol,sections:{news:'ok'},news:[{headline:'Reviewed stock evidence',source:'fixture'}]});});
app.use('/api/trading/ui',express.static(path.join(store,'trading/tools/ui')));
app.use('/api/trading-charts/vendor',express.static(path.join(store,'trading/tools/vendor')));
app.get('/api/finance/status',(_req,res)=>res.json({connected:1,hasData:true}));
app.get('/api/finance/summary',(_req,res)=>res.json({aggregate:{currency:'USD',netWorth:{net:1,assets:1,liabilities:0},accounts:[],holdings:[],topSpending:[]},syncedAt:'2026-09-01'}));
app.get('/api/finance/brief',(req,res)=>{assert.equal(req.query.cached,'1');res.status(404).json({error:'no_saved_brief'});});
app.get('/api/payments/providers',(_req,res)=>res.json({providers:[{provider:'square',connected:true,testMode:true}]}));
app.get('/api/payments/history',(_req,res)=>res.json({charges:[{charge_id:'selected-charge',provider:'square',amount_cents:'1234',currency:'USD',status:'completed',test_mode:true,note:'Selected payment evidence',created_at:'2026-09-01',updated_at:'2026-09-02'}]}));
const payrollRun={run_id:'selected-run',period_start:'2026-09-01',period_end:'2026-09-14',pay_date:'2026-09-15',status:'draft',updated_at:'2026-09-02',line_count:0};
app.get('/api/payroll/company',(_req,res)=>res.json({company:{company_name:'Fixture',pay_frequency:'biweekly',state_code:'FL'},taxYear:2026}));
app.get('/api/payroll/employees',(_req,res)=>res.json({employees:[]}));
app.get('/api/payroll/runs',(_req,res)=>res.json({runs:[payrollRun]}));
app.get('/api/payroll/runs/:id',(_req,res)=>res.json({run:payrollRun,lines:[]}));
let mediaConnected=false;
app.use((req,res,next)=>{if(req.method!=='GET'){writes.push(req.method+' '+req.path);return res.status(405).end();}next();});
app.use('/cockpit',express.static(path.join(core,'src/pages/cockpit')));
app.use('/shared',express.static(path.join(core,'src/pages/shared')));
app.use('/shared/ui',express.static(path.join(core,'src/shared/ui')));
app.use('/api/rides/vendor',express.static(path.join(store,'rides/tools/vendor')));
app.get('/api/artifacts/send-to.js',(_req,res)=>res.sendFile(path.join(core,'src/pages/cockpit/js/components/send-to.js')));
for(const m of manifests.filter(m=>files[m.name])) app.get(new URL(m.ui.static[0].iframeUrl,'http://local').pathname,(_req,res)=>res.sendFile(path.join(store,folder(m.name),'tools',files[m.name])));
const vidsModule=fs.readFileSync(path.join(store,'vids/routes/vids-routes.js'),'utf8');
const vidsTemplate=vidsModule.match(/`(<!DOCTYPE html>[\s\S]*?<\/html>)`/i);
assert.ok(vidsTemplate,'Use the actual compiled Vids HTML');
const vidsHtml=new Function('return `'+vidsTemplate[1]+'`;')();
app.get('/api/vids/app',(_req,res)=>res.type('html').send(vidsHtml));
app.get('/api/swarm/apps/home-plan',(_req,res)=>res.json({apps:entries}));
app.get('/api/home/preferences',(_req,res)=>res.json({preferences:{version:1},revision:0}));
for(const media of ['movies','spotify'])app.get('/api/'+media+'/config',(_req,res)=>res.json({connected:mediaConnected,status:mediaConnected?'ok':'not_connected'}));
const campaign=id=>({campaign_id:id,name:id,product:id+' product',status:'draft',stage:0,channels:[],icp:{audience:id+' audience'},message_map:{brief:id+' evidence'}});
app.get('/api/marketing/overview',(_req,res)=>res.json({campaigns:[campaign('unselected-campaign'),campaign('selected-campaign')]}));
const venture={id:'selected-venture',name:'Selected venture',ideaText:'Saved venture evidence'};
app.get('/api/venture/ventures',(_req,res)=>res.json({ventures:[venture]}));
app.get('/api/venture/ventures/:id',(_req,res)=>res.json({venture}));
app.get('/api/venture/ventures/:id/model',(_req,res)=>res.json({model:null}));
app.get('/api/venture/ventures/:id/assumptions',(_req,res)=>res.json({assumptions:[]}));
app.get('/api/venture/ventures/:id/documents',(_req,res)=>res.json({documents:[],catalog:[]}));
app.get('/summary',(_req,res)=>res.json({items:[{text:'Fixture research finding',detail:'Saved research evidence for review.',actions:['prepare-document','explore-venture','prepare-campaign'].map(integration=>({integration,context:{title:'Research finding',notes:'Evidence for review',sourceUrl:'https://news.example/story'}}))}]}));
app.get('/',(_req,res)=>res.send(`<!doctype html><html><head><link rel="stylesheet" href="/cockpit/css/apps-home.css"><style>body{margin:0;font-family:system-ui}#root{height:100vh}iframe{width:100%;height:100vh;border:0}</style></head><body><main id="root"></main><script type="module">import {CockpitViewController} from '/cockpit/js/cockpit-view-controller.js';let controller;const root=document.querySelector('#root');const ribbon={views:[],setActive:id=>controller.renderToolView(root,id)};controller=new CockpitViewController({getRibbon:()=>ribbon});await controller.renderAppsHomeView(root);</script></body></html>`));
app.use((req,res)=>res.json({tasks:[],items:[],campaigns:[],channels:[],scorecard:[],pendingProposals:[],experiments:[],recentRuns:[],ventures:[],trips:[],lists:[],deals:[],history:[],themes:[],layouts:[],files:[],profile:{},cart:{items:[]},source:'demo',mode:'demo'}));
(async()=>{
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 console.log('Fixture ready');const browser=await chromium.launch({timeout:30000});console.log('Browser ready');
 try{
  const page=await browser.newPage({viewport:{width:1400,height:1000}});
  page.setDefaultTimeout(20000);
  await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const frame=()=>page.frameLocator('iframe');
  const open=async name=>{await page.goto(base);await page.locator(`.apps-home-card[data-card="${name}"]`).getByRole('button',{name:'Open',exact:true}).first().click();};
  const filled=async (id,target)=>{const expectedPath=new URL(manifests.find(m=>m.name===target).ui.static[0].iframeUrl,base).pathname;await page.waitForFunction(({id,expectedPath})=>{const doc=document.querySelector('iframe')?.contentDocument;return doc?.location.pathname===expectedPath&&!!doc.getElementById(id)?.value;},{id,expectedPath});};
  const reachable=async selector=>{assert.equal(await frame().locator('.connected-app-actions').evaluate((el,selector)=>el.parentElement.matches(selector),selector),true);assert.ok(await frame().locator('.connected-app-actions button.btn').count());};
  await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');
  assert.match(await frame().locator('#outline').inputValue(),/Evidence for review/);
  await frame().getByRole('button',{name:'Prepare a campaign',exact:true}).click();await filled('ncBrief','marketing-engine');
  assert.match(await frame().locator('#ncBrief').inputValue(),/https:\/\/news.example\/story/);
  assert.equal(await frame().locator('#ncProduct').inputValue(),'');
  console.log('PASS World → Office → Marketing native draft controls');
  await open('marketing-engine');await frame().locator('[data-camp="selected-campaign"] [data-toggle]').click();
  await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');
  assert.match(await frame().locator('#outline').inputValue(),/selected-campaign evidence/);
  assert.doesNotMatch(await frame().locator('#outline').inputValue(),/unselected-campaign/);
  await open('venture-plan');await frame().locator('#vIdea').filter({hasText:'Saved venture evidence'}).waitFor();
  await frame().getByRole('button',{name:'Prepare a campaign',exact:true}).click();await filled('ncBrief','marketing-engine');
  assert.match(await frame().locator('#ncBrief').inputValue(),/Saved venture evidence/);
  console.log('PASS Marketing and Venture send the selected record context');
  await open('presentations');await frame().locator('#wzSkip').click();await frame().locator('#title').fill('Launch announcement');await frame().locator('#outline').fill('Reviewed launch notes');
  await frame().getByRole('button',{name:'Prepare a post',exact:true}).click();await filled('src','switchboard');
  assert.match(await frame().locator('#src').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a social draft',exact:true}).click();await filled('text','social');
  assert.match(await frame().locator('#text').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');
  assert.match(await frame().locator('#outline').inputValue(),/Reviewed launch notes/);
  console.log('PASS Office → Switchboard → Social → Office without drafting or publishing');
  await frame().getByRole('button',{name:'Prepare a video clip',exact:true}).click();await filled('prompt','vids');
  assert.match(await frame().locator('#prompt').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a video episode',exact:true}).click();await filled('idea','video');
  assert.match(await frame().locator('#idea').inputValue(),/Reviewed launch notes/);
  console.log('PASS Office → Vids → Video drafts without dispatching a render');
  await open('travel');await frame().locator('#f_dest').fill('SEA');await frame().locator('#searchForm').evaluate(form=>form.requestSubmit());
  await frame().getByRole('button',{name:'Plan a ride',exact:true}).click();await filled('chatInput','rides');
  assert.match(await frame().locator('#chatInput').inputValue(),/SEA/);
  await reachable('.search-stack');
  await frame().locator('#dropoff').fill('Conference center');await frame().getByRole('button',{name:'Plan a meal',exact:true}).click();await filled('chatInput','eats');
  assert.match(await frame().locator('#chatInput').inputValue(),/Conference center/);
  await reachable('.results');
  await frame().getByRole('button',{name:'Plan shopping',exact:true}).click();await filled('chatInput','purchasing');
  assert.match(await frame().locator('#chatInput').inputValue(),/Conference center/);
  await reachable('.results');
  console.log('PASS Travel → Rides → Eats → Shopping native planning drafts');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await frame().locator('body').evaluate(el=>el.scrollWidth<=el.ownerDocument.documentElement.clientWidth),true);
  await open('rides');await frame().locator('#dropoff').fill('Airport');await frame().getByRole('button',{name:'Plan a trip',exact:true}).click();await filled('chatbox','travel');
  assert.match(await frame().locator('#chatbox').inputValue(),/Airport/);
  await frame().locator('#f_dest').fill('BOS');await frame().locator('#searchForm').evaluate(form=>form.requestSubmit());
  await frame().getByRole('button',{name:'Plan a movie night',exact:true}).click();await filled('planningDraft','movies');
  assert.equal(await frame().locator('#planningDraft').isVisible(),true);
  assert.match(await frame().locator('#planningDraft').inputValue(),/BOS/);
  await frame().getByRole('button',{name:'Use in concierge',exact:true}).click();
  assert.equal(await frame().locator('#chatq').inputValue(),'');
  await frame().getByRole('button',{name:'Plan music',exact:true}).click();await filled('planningDraft','spotify');
  assert.equal(await frame().locator('#planningDraft').isVisible(),true);
  assert.match(await frame().locator('#planningDraft').inputValue(),/BOS/);
  mediaConnected=true;await frame().locator('#recheck').click();await frame().locator('#appWrap').waitFor({state:'visible'});
  await frame().locator('#planningDraft').fill('Reviewed music plan for Boston');
  await frame().getByRole('button',{name:'Use in concierge',exact:true}).click();
  assert.equal(await frame().locator('#chatq').inputValue(),'Reviewed music plan for Boston');
  assert.equal(await frame().locator('body').evaluate(el=>el.scrollWidth<=el.ownerDocument.documentElement.clientWidth),true);
  console.log('PASS Travel → Movies → Spotify preserves visible drafts through connection gates');
  console.log('Checking Payments selection');await open('payments');await frame().getByRole('button',{name:'Review',exact:true}).click();
  await frame().getByRole('button',{name:'Review with Finance',exact:true}).click();await filled('reviewNotes','finance');
  assert.match(await frame().locator('#reviewNotes').inputValue(),/selected-charge/);
  assert.match(await frame().locator('#reviewNotes').inputValue(),/TEST charge/);
  assert.equal(await frame().locator('#payAmt').inputValue(),'');assert.equal(await frame().locator('#payMemo').inputValue(),'');
  await frame().locator('#reviewNotes').fill('Edited selected payment evidence');
  assert.equal(await frame().locator('body').evaluate(el=>el.scrollWidth<=el.ownerDocument.documentElement.clientWidth),true);
  await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');assert.match(await frame().locator('#outline').inputValue(),/Edited selected payment evidence/);
  await open('payroll');await frame().locator('[data-tab="runs"]').click();await frame().getByText('open',{exact:true}).click();
  await frame().getByRole('button',{name:'Review with Finance',exact:true}).click();await filled('reviewNotes','finance');
  assert.match(await frame().locator('#reviewNotes').inputValue(),/selected-run/);assert.match(await frame().locator('#reviewNotes').inputValue(),/does not prove bank settlement/);
  console.log('PASS selected Payment → Finance → Office and Payroll → Finance; no automatic analysis, sync or money movement');
  await open('kalshi');await frame().locator('[data-tab="alerts"]').click();await frame().getByRole('button',{name:'Review',exact:true}).click();
  await frame().getByRole('button',{name:'Research with Trading',exact:true}).click();await filled('researchDraft','intelligent-trades');
  assert.match(await frame().locator('#researchDraft').inputValue(),/SELECTED-MARKET/);assert.equal(await frame().locator('#researchTicker').inputValue(),'');assert.equal(stockReads,0);
  await frame().locator('#researchDraft').fill('Edited market evidence');await frame().locator('#researchTicker').fill('AAPL');await frame().getByRole('button',{name:'Research this stock',exact:true}).click();
  await frame().getByText('Reviewed stock evidence',{exact:true}).waitFor();assert.equal(stockReads,1);
  await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');assert.match(await frame().locator('#outline').inputValue(),/Edited market evidence/);
  console.log('PASS Kalshi selected alert → Trading editable research → Office; stock fetch requires explicit Research');
  assert.deepEqual(writes,[]);
  assert.deepEqual(errors,[]);
  await open('presentations');if(await frame().locator('#wzSkip').isVisible())await frame().locator('#wzSkip').click();await frame().locator('#title').fill('Campaign launch');await frame().locator('#outline').fill('Selected brand evidence');
  await frame().getByRole('button',{name:'Prepare a brand graphic',exact:true}).click();await filled('notes','brand-graphics');
  assert.match(await frame().locator('#notes').inputValue(),/Selected brand evidence/);
  await frame().locator('#notes').fill('Edited brand brief');
  assert.equal(await frame().locator('body').evaluate(el=>el.scrollWidth<=el.ownerDocument.documentElement.clientWidth),true);
  await frame().getByRole('button',{name:'Prepare a video episode',exact:true}).click();await filled('idea','video');assert.match(await frame().locator('#idea').inputValue(),/Edited brand brief/);
  await open('kalshi');await frame().locator('[data-tab="alerts"]').click();await frame().getByRole('button',{name:'Review',exact:true}).click();await frame().getByRole('button',{name:'Prepare a trade recap',exact:true}).click();await filled('notes','daily-trade-recap');assert.match(await frame().locator('#notes').inputValue(),/Selected market evidence/);
  await frame().locator('#notes').fill('Edited recap production brief');await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');assert.match(await frame().locator('#outline').inputValue(),/Edited recap production brief/);
  console.log('PASS Office → Brand → Video and Kalshi → Recap → Office, editable drafts without generation or delivery');
  assert.deepEqual(writes,[]);
  assert.deepEqual(errors,[]);
  await open('camera');await frame().locator('#evidenceReview summary').click();await filled('evidenceNotes','camera');assert.match(await frame().locator('#evidenceNotes').inputValue(),/Selected rejected command/);
  await frame().locator('#evidenceNotes').fill('Edited diagnostic evidence');await frame().getByRole('button',{name:'Prepare a diagnostic brief',exact:true}).click();await filled('outline','presentations');assert.match(await frame().locator('#outline').inputValue(),/Edited diagnostic evidence/);
  await open('aero-lab');await frame().locator('#labReview summary').click();await frame().locator('#verdictCard').evaluate(el=>{el.textContent='Synthetic simulation verdict for transport acceptance';});await frame().locator('#captureLabEvidence').click();assert.match(await frame().locator('#labNotes').inputValue(),/Synthetic simulation verdict/);assert.match(await frame().locator('#labNotes').inputValue(),/SIMULATION/);await frame().getByRole('button',{name:'Prepare an analysis document',exact:true}).click();await filled('outline','presentations');assert.match(await frame().locator('#outline').inputValue(),/SIMULATION/);
  assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);
  console.log('PASS Camera selected evidence and Aero visible simulation verdict to Office; editable context and no actuation or solver execution');
  await open('job-apply');await frame().getByRole('button',{name:'Use this evidence',exact:true}).click();await frame().getByRole('button',{name:'Review in Career',exact:true}).click();await filled('notes','career-hunter');assert.match(await frame().locator('#notes').inputValue(),/Verified fixture submission/);await frame().locator('#notes').fill('Reviewed networking question');await frame().getByRole('button',{name:'Prepare a networking draft',exact:true}).click();await filled('text','social');assert.match(await frame().locator('#text').inputValue(),/Reviewed networking question/);
  assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);console.log('PASS Apply evidence to Career to Social draft; no submission or publication');
  await open('social');await page.locator('iframe').evaluate(frame=>{frame.src='/api/social/signals/ui';});await frame().getByRole('button',{name:'Review this signal',exact:true}).click();assert.match(await frame().locator('#signalDraft').inputValue(),/Selected notification evidence/);await frame().locator('#signalDraft').fill('Edited notification response');await frame().getByRole('button',{name:'Prepare a post',exact:true}).click();await filled('src','switchboard');assert.match(await frame().locator('#src').inputValue(),/Edited notification response/);assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);console.log('PASS selected Social signal opens edited Switchboard draft without organization or publication');
  for(const name of ['youtube-kids','dnd','game-show','pumpkin','bake-off','sports-edge','little-monsters','calendar','capability-ideator']){
 await open(name);await frame().getByRole('button',{name:'Use this evidence',exact:true}).click();await frame().locator('#notes').fill('Reviewed learning evidence '+name);
 const m=manifests.find(m=>m.name===name),offer=m.integrations.offers.find(o=>o.targetApp==='presentations')||m.integrations.offers[0];
 await frame().getByRole('button',{name:offer.label,exact:true}).click();const field={presentations:'outline',vids:'prompt',eats:'chatInput',purchasing:'chatInput',travel:'chatbox'}[offer.targetApp];await filled(field,offer.targetApp);assert.match(await frame().locator('#'+field).inputValue(),/Reviewed learning evidence/);
 }assert.deepEqual(writes,[]);console.log('PASS learning, Calendar and Discovery review screens carry edited evidence to native destinations');
 await open('calendar');await frame().getByRole('button',{name:'Use this evidence',exact:true}).click();await frame().locator('#notes').fill('Birthday gift for a friend; discuss preferences and budget');await frame().getByRole('button',{name:'Discuss gift ideas',exact:true}).click();await filled('chatInput','purchasing');assert.match(await frame().locator('#chatInput').inputValue(),/Birthday gift/);assert.deepEqual(writes,[]);
  console.log('PASS mobile receiver has no horizontal overflow; zero business writes');
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
