/** Actual app screens and cockpit relay; fixture records, no provider calls or business writes. */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const core=path.resolve(__dirname,'../../oshal'),store=path.resolve(__dirname,'..');
const express=require(path.join(core,'node_modules/express')),yaml=require(path.join(core,'node_modules/js-yaml'));
const {chromium}=require(path.join(core,'node_modules/playwright'));
const files={presentations:'presentations.html','marketing-engine':'marketing-engine.html','venture-plan':'venture.html',travel:'travel-app.html',purchasing:'shopping-chat.html',eats:'eats-app.html',rides:'rides-app.html',switchboard:'switchboard-compose.html',social:'social-composer.html',video:'video.html',vids:null};
const manifests=[...Object.keys(files),'world'].map(name=>yaml.load(fs.readFileSync(path.join(store,name,'oshal-app.yaml'),'utf8')));
// Each fixture screen uses the same declared URL as its real receiving surface.
for(const m of manifests) if(m.name==='switchboard') m.ui.static.sort((a,b)=>Number(b.toolName==='switchboard-compose')-Number(a.toolName==='switchboard-compose'));
const offers=m=>(m.integrations?.offers||[]).map(o=>{const target=manifests.find(a=>a.name===o.targetApp),receiver=target?.integrations?.accepts?.find(r=>r.id===o.targetAction&&r.version===o.version&&r.contextType===o.contextType);return {...o,sourceApp:m.name,state:receiver?'available':'unavailable',surface:receiver?.surface,surfaceUrl:target?.ui.static.find(s=>s.toolName===receiver?.surface)?.iframeUrl,fields:receiver?.fields};});
const entries=manifests.map(m=>({name:m.name,displayName:m.displayName,suite:m.suite,kind:'app',members:[m.name],firstSurface:m.ui.static[0].toolName,firstSurfaceUrl:m.ui.static[0].iframeUrl,todos:[],integrationSources:[{app:m.name,surfaces:m.ui.static.map(s=>({name:s.toolName,url:s.iframeUrl})),offers:offers(m)}],summary:m.name==='world'?[{app:'world',path:'/summary',itemsPointer:'/items',surfaces:['world-dashboard'],integrations:offers(m)}]:[]}));
const app=express();let writes=[];
app.use((req,res,next)=>{if(req.method!=='GET'){writes.push(req.method+' '+req.path);return res.status(405).end();}next();});
app.use('/cockpit',express.static(path.join(core,'src/pages/cockpit')));
app.use('/shared',express.static(path.join(core,'src/pages/shared')));
app.use('/shared/ui',express.static(path.join(core,'src/shared/ui')));
app.use('/api/rides/vendor',express.static(path.join(store,'rides/tools/vendor')));
app.get('/api/artifacts/send-to.js',(_req,res)=>res.sendFile(path.join(core,'src/pages/cockpit/js/components/send-to.js')));
for(const m of manifests.filter(m=>files[m.name])) app.get(new URL(m.ui.static[0].iframeUrl,'http://local').pathname,(_req,res)=>res.sendFile(path.join(store,m.name,'tools',files[m.name])));
const vidsModule=fs.readFileSync(path.join(store,'vids/routes/vids-routes.js'),'utf8');
const vidsTemplate=vidsModule.match(/`(<!DOCTYPE html>[\s\S]*?<\/html>)`/i);
assert.ok(vidsTemplate,'Use the actual compiled Vids HTML');
const vidsHtml=new Function('return `'+vidsTemplate[1]+'`;')();
app.get('/api/vids/app',(_req,res)=>res.type('html').send(vidsHtml));
app.get('/api/swarm/apps/home-plan',(_req,res)=>res.json({apps:entries}));
app.get('/api/home/preferences',(_req,res)=>res.json({preferences:{version:1},revision:0}));
app.get('/summary',(_req,res)=>res.json({items:[{text:'Fixture research finding',detail:'Saved research evidence for review.',actions:['prepare-document','explore-venture','prepare-campaign'].map(integration=>({integration,context:{title:'Research finding',notes:'Evidence for review',sourceUrl:'https://news.example/story'}}))}]}));
app.get('/',(_req,res)=>res.send(`<!doctype html><html><head><link rel="stylesheet" href="/cockpit/css/apps-home.css"><style>body{margin:0;font-family:system-ui}#root{height:100vh}iframe{width:100%;height:100vh;border:0}</style></head><body><main id="root"></main><script type="module">import {CockpitViewController} from '/cockpit/js/cockpit-view-controller.js';let controller;const root=document.querySelector('#root');const ribbon={views:[],setActive:id=>controller.renderToolView(root,id)};controller=new CockpitViewController({getRibbon:()=>ribbon});await controller.renderAppsHomeView(root);</script></body></html>`));
app.use((req,res)=>res.json({tasks:[],items:[],campaigns:[],channels:[],scorecard:[],pendingProposals:[],experiments:[],recentRuns:[],ventures:[],trips:[],lists:[],deals:[],history:[],themes:[],layouts:[],files:[],profile:{},cart:{items:[]},source:'demo',mode:'demo'}));
(async()=>{
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 console.log('Fixture ready');const browser=await chromium.launch({timeout:30000});console.log('Browser ready');
 try{
  const page=await browser.newPage({viewport:{width:1400,height:1000}});
  await page.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const frame=()=>page.frameLocator('iframe');
  const open=async name=>{await page.goto(base);await page.locator(`.apps-home-card[data-card="${name}"]`).getByRole('button',{name:'Open',exact:true}).first().click();};
  const filled=async (id,target)=>{const expectedPath=new URL(manifests.find(m=>m.name===target).ui.static[0].iframeUrl,base).pathname;await page.waitForFunction(({id,expectedPath})=>{const doc=document.querySelector('iframe')?.contentDocument;return doc?.location.pathname===expectedPath&&!!doc.getElementById(id)?.value;},{id,expectedPath});};
  await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');
  assert.match(await frame().locator('#outline').inputValue(),/Evidence for review/);
  await frame().getByRole('button',{name:'Prepare a campaign',exact:true}).click();await filled('ncBrief','marketing-engine');
  assert.match(await frame().locator('#ncBrief').inputValue(),/https:\/\/news.example\/story/);
  assert.equal(await frame().locator('#ncProduct').inputValue(),'');
  console.log('PASS World → Office → Marketing native draft controls');
  await open('presentations');await frame().locator('#wzSkip').click();await frame().locator('#title').fill('Launch announcement');await frame().locator('#outline').fill('Reviewed launch notes');
  await frame().getByRole('button',{name:'Prepare a post',exact:true}).click();await filled('src','switchboard');
  assert.match(await frame().locator('#src').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a social draft',exact:true}).click();await filled('text','social');
  assert.match(await frame().locator('#text').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a document',exact:true}).click();await filled('outline','presentations');
  assert.match(await frame().locator('#outline').inputValue(),/Reviewed launch notes/);
  console.log('PASS Office → Switchboard → Social → Office without drafting or publishing');
  await frame().getByRole('button',{name:'Prepare a video clip',exact:true}).click();await filled('prompt','vids');
  assert.match(await frame().locator('#prompt').inputValue(),/Reviewed launch notes/);
  await frame().getByRole('button',{name:'Prepare a video episode',exact:true}).click();await filled('idea','video');
  assert.match(await frame().locator('#idea').inputValue(),/Reviewed launch notes/);
  console.log('PASS Office → Vids → Video drafts without dispatching a render');
  await open('travel');await frame().locator('#f_dest').fill('SEA');await frame().locator('#searchForm').evaluate(form=>form.requestSubmit());
  await frame().getByRole('button',{name:'Plan a ride',exact:true}).click();await filled('chatInput','rides');
  assert.match(await frame().locator('#chatInput').inputValue(),/SEA/);
  await frame().locator('#dropoff').fill('Conference center');await frame().getByRole('button',{name:'Plan a meal',exact:true}).click();await filled('chatInput','eats');
  assert.match(await frame().locator('#chatInput').inputValue(),/Conference center/);
  await frame().getByRole('button',{name:'Plan shopping',exact:true}).click();await filled('chatInput','purchasing');
  assert.match(await frame().locator('#chatInput').inputValue(),/Conference center/);
  console.log('PASS Travel → Rides → Eats → Shopping native planning drafts');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await frame().locator('body').evaluate(el=>el.scrollWidth<=el.ownerDocument.documentElement.clientWidth),true);
  await open('rides');await frame().locator('#dropoff').fill('Airport');await frame().getByRole('button',{name:'Plan a trip',exact:true}).click();await filled('chatbox','travel');
  assert.match(await frame().locator('#chatbox').inputValue(),/Airport/);
  assert.deepEqual(writes,[]);
  assert.deepEqual(errors,[]);
  console.log('PASS mobile receiver has no horizontal overflow; zero business writes');
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
