const fs=require('fs'),path=require('path'),test=require('node:test'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
function load(app,file,deps={}){const m={exports:{}};new Function('require','module','exports',fs.readFileSync(path.join(root,app,'routes',file+'.js'),'utf8'))(name=>{if(name in deps)return deps[name];throw Error('Unexpected dependency '+name);},m,m.exports);return m.exports;}
const req=(extra={})=>({oidc:{user:{sub:'alice'},isAuthenticated:()=>true},...extra});
const res=()=>({statusCode:200,setHeader(){},status(n){this.statusCode=n;return this;},json(body){this.body=body;}});
test('school setup gaps do not turn a valid framework login into a Home-wide login redirect',async()=>{
 const education=load('little-monsters','education-access',{'node:crypto':require('node:crypto'),'@/shared/logger':{createChildLogger:()=>({error(){},info(){}})}});
 const saved=process.env.MOCK_OIDC;delete process.env.MOCK_OIDC;
 try{const {get}=route('little-monsters','home-summary','createHomeSummaryRoutes',{query:()=>assert.fail('identity is not school-bound')},{'./education-access':education});let r=res();await get(req(),r);assert.equal(r.statusCode,403);r=res();await get(req({oidc:null}),r);assert.equal(r.statusCode,401);}finally{if(saved===undefined)delete process.env.MOCK_OIDC;else process.env.MOCK_OIDC=saved;}
});
function route(app,file,factory,pool,imports={}){let get,post;load(app,file,{'express':{Router:()=>({get:(_,f)=>get=f,post:(_,f)=>post=f})},...imports})[factory]({pool});return {get,post};}
test('calendar evidence distinguishes no sync, empty sync, future events, and all-day dates',()=>{
 const {calendarEvidence}=load('calendar','home-summary',{'express':{}}),now=new Date('2026-09-10T12:00:00Z');
 assert.equal(calendarEvidence(null,now).metrics[0].value,'Not synced');assert.equal(calendarEvidence({synced_at:now,events:[]},now).metrics[0].value,'0');
 const r=calendarEvidence({synced_at:now,events:[{title:'Past',start:'2026-09-10T01:00:00Z'},{title:'Birthday',start:'2026-09-10',allDay:true,url:'javascript:alert(1)',attendees:['PRIVATE']},{title:'Meeting',start:'2026-09-11T14:00:00Z',description:'PRIVATE'},{title:'Later',start:'2026-10-20'},null]},now);
 assert.equal(r.metrics[0].value,'2');assert.equal(r.items[0].text,'Birthday');assert.ok(!JSON.stringify(r).includes('PRIVATE'));assert.ok(!JSON.stringify(r).includes('javascript:'));assert.ok(!JSON.stringify(r).includes('Past'));assert.equal(r.items[0].actions.length,4);
});
test('calendar GET is owner-scoped SELECT only and authenticates before reading',async()=>{let reads=0;const {get}=route('calendar','home-summary','createHomeSummaryRoutes',{query:async q=>{reads++;assert.equal(q.values[0],'alice');assert.match(q.text,/^SELECT .*WHERE user_sub = \$1$/);return {rows:[]};}});let r=res();await get(req({oidc:null}),r);assert.equal(r.statusCode,401);assert.equal(reads,0);r=res();await get(req({query:{user_sub:'bob'}}),r);assert.equal(reads,1);assert.equal(r.body.metrics[0].value,'Not synced');});
test('calendar sync requires confirmation and caller credentials, minimizes data, and uses fixed primary-calendar bounds',async()=>{let calls=0,writes=0;const {post}=route('calendar','sync','createCalendarSyncRoutes',{query:async(text,values)=>{writes++;assert.match(text,/^INSERT INTO calendar_preparation_snapshots/);assert.equal(values[0],'alice');assert.ok(!values[1].includes('PRIVATE'));}}, {'@/app/routes/connectors-routes':{getValidAccessToken:async(_pool,sub,provider)=>{assert.equal(sub,'alice');assert.equal(provider,'google');return 'fixture-token';}},'@/features/google-calendar':{GoogleCalendarService:class{constructor(provider){this.provider=provider;}async listUpcoming(options){calls++;assert.equal(await this.provider(),'fixture-token');assert.equal(options.calendarId,'primary');assert.equal(options.maxResults,250);return [{id:'event',summary:'Birthday',start:'2026-09-11',allDay:true,description:'PRIVATE',attendees:['PRIVATE']}];}}}});let r=res();await post(req({body:{}}),r);assert.equal(r.statusCode,400);assert.equal(calls,0);await post(req({body:{confirm:true,owner:'bob',calendarId:'other'}}),res());assert.equal(calls,1);assert.equal(writes,1);});
test('calendar disconnected and failed sync retain the prior snapshot',async()=>{for(const token of [null,'token']){const {post}=route('calendar','sync','createCalendarSyncRoutes',{query:()=>assert.fail('write')},{'@/app/routes/connectors-routes':{getValidAccessToken:async()=>token},'@/features/google-calendar':{GoogleCalendarService:class{async listUpcoming(){throw Error('SECRET');}}}});const r=res();await post(req({body:{confirm:true}}),r);assert.equal(r.statusCode,token?502:409);assert.ok(!JSON.stringify(r.body).includes('SECRET'));}});
test('discovery is operator-gated but remains caller-owned, read-only and partial-aware',async()=>{let operator=false,reads=0;const {get}=route('capability-ideator','home-summary','createHomeSummaryRoutes',{query:async q=>{reads++;assert.match(q.text,/^SELECT /);assert.match(q.text,/owner_sub = \$1/);assert.equal(q.values[0],'alice');if(reads===2)throw Error('PRIVATE');return {rows:[]};}},{'@/shared/middleware/authz':{isOperator:()=>operator}});let r=res();await get(req(),r);assert.equal(r.statusCode,403);assert.equal(reads,0);operator=true;r=res();await get(req(),r);assert.equal(r.statusCode,200);assert.equal(r.body.partial,true);assert.ok(!JSON.stringify(r.body).includes('PRIVATE'));});
