/** Compiled household summary boundaries; database semantics run in household-home.integration.cjs. */
const fs=require('fs'),path=require('path'),test=require('node:test'),assert=require('node:assert/strict');
const apps=['movies','spotify','travel','rides','eats','purchasing'];
function route(app,query){let handler;const module={exports:{}};new Function('require','module','exports',fs.readFileSync(path.join(__dirname,'..',app,'routes/home-summary.js'),'utf8'))(name=>{assert.equal(name,'express');return {Router:()=>({get:(_,fn)=>handler=fn})};},module,module.exports);module.exports.createHomeSummaryRoutes({pool:{query}});return async(oidc={user:{sub:'alice'},isAuthenticated:()=>true})=>{const res={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.statusCode=s;return this;},json(body){this.body=body;}};await handler({oidc,query:{user_sub:'bob'}},res);return res;};}
for(const app of apps){
 test(app+' rejects absent or unverified sessions without a database read',async()=>{const call=route(app,()=>assert.fail('must not read'));for(const oidc of [null,{user:{sub:'alice'}},{user:{sub:'alice'},isAuthenticated:()=>false}])assert.equal((await call(oidc)).statusCode,401);});
 test(app+' keeps repeated reads owner-scoped, bounded and side-effect free',async()=>{let reads=0;const call=route(app,async q=>{reads++;assert.match(q.text,/^SELECT /);assert.match(q.text,/user_sub = \$1/);assert.equal(q.values[0],'alice');assert.ok(q.values[1] instanceof Date);assert.equal(q.query_timeout,1800);return {rows:[]};});for(let i=0;i<2;i++){const res=await call();assert.equal(res.statusCode,200);assert.equal(res.body.partial,false);assert.equal(res.headers['Cache-Control'],'no-store');assert.ok(res.body.items.some(x=>/No saved/.test(x.text)));}assert.ok(reads>=2);});
 test(app+' reports unavailable sources without leaking errors or zeroing counts',async()=>{const res=await route(app,async()=>{throw Error('secret database detail');})();assert.equal(res.statusCode,503);assert.equal(res.body.partial,true);assert.ok(res.body.metrics.every(m=>m.value==='Unavailable'));assert.ok(!JSON.stringify(res.body).includes('secret database detail'));});
}
test('partial shopping counts preserve successful sources and expose the missing source',async()=>{const res=await route('purchasing',async q=>{if(q.text.includes('shop_purchase_history'))throw Error('offline');return {rows:q.text.includes('AS lists')?[{lists:'2'}]:[]};})();assert.equal(res.statusCode,200);assert.equal(res.body.partial,true);assert.equal(res.body.metrics[0].value,'2');assert.equal(res.body.metrics[2].value,'Unavailable');});
test('music preference context is bounded and carries no unrelated profile fields',async()=>{const res=await route('spotify',async()=>({rows:[{favorite_genres:['jazz'],favorite_artists:['A'.repeat(5000)],notes:'PRIVATE-NOTE',user_sub:'DO-NOT-SEND',updated_at:new Date()}]}))();const item=res.body.items.find(i=>i.actions);assert.ok(item);assert.ok(item.detail.length<=500);assert.ok(item.actions.every(a=>a.context.notes.length<=400));assert.ok(!JSON.stringify(res.body).includes('PRIVATE-NOTE'));assert.ok(!JSON.stringify(res.body).includes('DO-NOT-SEND'));});
