/** Compiled creative summaries: authenticated saved evidence and bounded draft actions. */
const fs=require('fs'),path=require('path'),test=require('node:test'),assert=require('node:assert/strict');
const apps=['brand-graphics','creative-studio','daily-trade-recap','lora','portrait-studio','print-ingest','storage'];
function route(app,query){let handler;const module={exports:{}};new Function('require','module','exports',fs.readFileSync(path.join(__dirname,'..',app,'routes/home-summary.js'),'utf8'))(name=>{assert.equal(name,'express');return {Router:()=>({get:(_,fn)=>handler=fn})};},module,module.exports);module.exports.createHomeSummaryRoutes({pool:{query}});return async(oidc={user:{sub:'alice'},isAuthenticated:()=>true})=>{const res={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(s){this.statusCode=s;return this;},json(body){this.body=body;}};await handler({oidc,query:{user_sub:'bob'}},res);return res;};}
for(const app of apps){
 test(app+' authenticates before reading',async()=>{const call=route(app,()=>assert.fail('read'));for(const oidc of [null,{user:{sub:'alice'}},{user:{sub:'alice'},isAuthenticated:()=>false}])assert.equal((await call(oidc)).statusCode,401);});
 test(app+' uses repeated bounded owner SELECTs only',async()=>{const call=route(app,async q=>{assert.match(q.text,/^SELECT /);assert.match(q.text,/(user_sub|owner_sub) = \$1/);assert.equal(q.values[0],'alice');assert.ok(q.values[1] instanceof Date);assert.equal(q.query_timeout,1800);return {rows:[]};});for(let i=0;i<2;i++){const r=await call();assert.equal(r.statusCode,200);assert.equal(r.body.partial,false);assert.equal(r.headers['Cache-Control'],'no-store');assert.ok(r.body.metrics.every(m=>m.value===(app==='storage'?'Automatic':'0')));}});
 test(app+' reports unavailable sources without inventing zero',async()=>{const r=await route(app,async()=>{throw Error('PRIVATE');})();assert.equal(r.statusCode,503);assert.ok(r.body.metrics.every(m=>m.value==='Unavailable'));assert.ok(!JSON.stringify(r.body).includes('PRIVATE'));});
 test(app+' isolates partial failures and bounds transferred context',async()=>{let n=0;const r=await route(app,async()=>{if(n++===0)throw Error('missing');return {rows:[{title:'Title',name:'Plan',idea:'A'.repeat(5000),body:'B'.repeat(6000),idea_text:'C'.repeat(6000),premise:'D'.repeat(6000),created_at:'2026-09-01',updated_at:'2026-09-01',outline:[{title:'Slide',content:'E'.repeat(5000)}]}]};})();assert.equal(r.statusCode,app==='storage'?503:200);assert.equal(r.body.partial,true);assert.equal(r.body.metrics[0].value,'Unavailable');for(const i of r.body.items){assert.ok((i.actions||[]).length<=4);for(const a of i.actions||[]){assert.ok(a.context.notes.length<=2000);assert.ok(a.context.title.length<=120);}}});
}
const vm=require('node:vm');
async function brandCli(env,input={brief:'Reviewed brief'}){const calls=[],output=[],fakeProcess={env,argv:['node','brand','graphic',JSON.stringify(input)],stdout:{write:s=>output.push(s)},exitCode:0};await vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../brand-graphics/tools/oshal-brand.js'),'utf8'),{process:fakeProcess,Buffer,fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({job_id:'saved-brand'})};}});return {calls,output,exitCode:fakeProcess.exitCode};}
test('Brand CLI sends the approved brief through the attributed brand dispatch door',async()=>{const r=await brandCli({SWARM_SERVICE_SECRET:'fixture-secret',OSHAL_USER_SUB:'owner@example.test'});assert.equal(r.exitCode,0);assert.equal(r.calls.length,1);assert.match(r.calls[0].url,/\/api\/vids\/brand$/);assert.equal(Buffer.from(r.calls[0].options.headers['X-Oshal-User-Sub-B64'],'base64url').toString(),'owner@example.test');assert.equal(JSON.parse(r.calls[0].options.body).confirm,true);assert.equal(JSON.parse(r.calls[0].options.body).brandMode,'graphic');});
test('Brand CLI refuses missing attribution before network calls',async()=>{const r=await brandCli({SWARM_SERVICE_SECRET:'fixture-secret'});assert.equal(r.exitCode,1);assert.equal(r.calls.length,0);assert.ok(!r.output.join('').includes('fixture-secret'));});
