"use strict";
/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * DATE/TIME           | AUTHOR                                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 2026-07-17 20:10:00 | roger.murphy@emeraldcoastsystemsgroup.com   | The big catalog (operator request: "100 profiles, 100 backdrops, 10000 permutations"): EXACTLY 100 backgrounds across 8 groups (studio, corporate, city, nature, home & life, work environments, historical, fantasy), 70 clothing styles, 30 headwear, 26 props (NEW interchangeable layer — pitchfork to espresso cup), 12 finishes, 4 framings. Every entry grouped for optgroup pickers. Counts are ENFORCED by the package test suite so the catalog can't silently decay.
 * 2026-08-29 10:00:00 | maintainer@emeraldcoastsystemsgroup.com     | Catalog v2 (operator: "lots of different backdrops … a lot more options"): +100 backgrounds (Sun & Sea, Sports & Action, World & Travel, Season & Weather, Sci-Fi & Space, Fantasy Realms, Retro & Pop, Grand & Formal → 200), +40 clothing (→110), +20 headwear (→50), +34 props (→60), +8 finishes (→20) and a `wide` scene framing (→5). Every prior id untouched (gallery rows reference them); the new counts are the test-enforced contract.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FRAMINGS = exports.FINISHES = exports.PROPS = exports.HEADWEAR = exports.CLOTHING = exports.BACKGROUNDS = void 0;
/** @description EXACTLY 200 interchangeable backgrounds (test-enforced). */
exports.BACKGROUNDS = [
    // ── Studio (10) ──────────────────────────────────────────────────────────
    { id: 'studio-gray', label: 'Studio Gray', icon: '🎞️', group: 'Studio', prompt: 'a seamless neutral gray studio backdrop with a soft vignette' },
    { id: 'corporate-navy', label: 'Corporate Navy', icon: '🏛️', group: 'Studio', prompt: 'a deep navy studio backdrop with a subtle rim light' },
    { id: 'clean-white', label: 'Clean White', icon: '⬜', group: 'Studio', prompt: 'a bright clean white backdrop with high-key lighting' },
    { id: 'charcoal-studio', label: 'Charcoal', icon: '⬛', group: 'Studio', prompt: 'a near-black charcoal studio backdrop with a single dramatic key light' },
    { id: 'cream-studio', label: 'Warm Cream', icon: '🤍', group: 'Studio', prompt: 'a warm cream seamless backdrop with soft window-style light' },
    { id: 'gradient-blue', label: 'Blue Gradient', icon: '🌀', group: 'Studio', prompt: 'a smooth blue-to-teal gradient studio backdrop' },
    { id: 'brick-studio', label: 'Exposed Brick', icon: '🧱', group: 'Studio', prompt: 'a warmly lit exposed-brick studio wall' },
    { id: 'spotlight-black', label: 'Spotlight', icon: '🔦', group: 'Studio', prompt: 'a black void with a single theatrical spotlight from above' },
    { id: 'sage-studio', label: 'Sage Green', icon: '🌿', group: 'Studio', prompt: 'a muted sage-green seamless backdrop with gentle diffusion' },
    { id: 'terracotta-studio', label: 'Terracotta', icon: '🧡', group: 'Studio', prompt: 'a sun-washed terracotta plaster wall with Mediterranean light' },
    // ── Corporate (10) ───────────────────────────────────────────────────────
    { id: 'office-bokeh', label: 'Modern Office', icon: '🏢', group: 'Corporate', prompt: 'a modern bright office background, softly blurred with creamy bokeh' },
    { id: 'boardroom', label: 'Boardroom', icon: '🌆', group: 'Corporate', prompt: 'floor-to-ceiling boardroom windows with a city skyline behind' },
    { id: 'glass-lobby', label: 'Glass Lobby', icon: '🏬', group: 'Corporate', prompt: 'a soaring corporate glass lobby with polished stone floors, softly blurred' },
    { id: 'corner-office', label: 'Corner Office', icon: '🪟', group: 'Corporate', prompt: 'a corner office with two window walls and warm late-afternoon light' },
    { id: 'conference-stage', label: 'Keynote Stage', icon: '🎤', group: 'Corporate', prompt: 'a conference keynote stage with a large blurred presentation screen behind' },
    { id: 'trading-floor', label: 'Trading Floor', icon: '📈', group: 'Corporate', prompt: 'a busy trading floor of glowing market screens, softly out of focus' },
    { id: 'law-library', label: 'Law Library', icon: '⚖️', group: 'Corporate', prompt: 'a stately law library with leather-bound case reports and green desk lamps' },
    { id: 'bank-hall', label: 'Bank Hall', icon: '🏦', group: 'Corporate', prompt: 'a grand marble bank hall with brass fixtures, softly blurred' },
    { id: 'rooftop-terrace', label: 'Rooftop Terrace', icon: '🌇', group: 'Corporate', prompt: 'a skyscraper rooftop terrace at dusk with city lights below' },
    { id: 'coworking', label: 'Co-working Loft', icon: '💻', group: 'Corporate', prompt: 'a bright co-working loft with plants, whiteboards and Edison bulbs, softly blurred' },
    // ── City (10) ────────────────────────────────────────────────────────────
    { id: 'city-street', label: 'City Street', icon: '🚕', group: 'City', prompt: 'a lively downtown street with softly blurred traffic and storefronts' },
    { id: 'cobblestone-alley', label: 'Cobblestone Alley', icon: '🏘️', group: 'City', prompt: 'an old-world cobblestone alley with ivy and iron lanterns' },
    { id: 'neon-night', label: 'Neon Night', icon: '🌃', group: 'City', prompt: 'a rain-slicked night street glowing with colorful neon signs' },
    { id: 'cafe-terrace', label: 'Café Terrace', icon: '☕', group: 'City', prompt: 'a Parisian-style café terrace with woven chairs and striped awning' },
    { id: 'metro-platform', label: 'Metro Platform', icon: '🚇', group: 'City', prompt: 'a tiled metro platform with a motion-blurred train passing' },
    { id: 'market-street', label: 'Market Street', icon: '🍎', group: 'City', prompt: 'a bustling open-air market street with colorful produce stalls' },
    { id: 'riverside', label: 'Riverside Walk', icon: '🌉', group: 'City', prompt: 'a riverside promenade with a grand bridge softly blurred behind' },
    { id: 'old-town-square', label: 'Old Town Square', icon: '⛲', group: 'City', prompt: 'a historic town square with a fountain and pastel facades' },
    { id: 'industrial-loft', label: 'Industrial Loft', icon: '🏭', group: 'City', prompt: 'a converted industrial loft with steel beams and tall factory windows' },
    { id: 'graffiti-wall', label: 'Graffiti Wall', icon: '🎨', group: 'City', prompt: 'a vibrant street-art mural wall in an urban laneway' },
    // ── Nature (14) ──────────────────────────────────────────────────────────
    { id: 'outdoor-golden', label: 'Golden Hour', icon: '🌤️', group: 'Nature', prompt: 'an outdoor golden-hour background with soft natural light and gentle bokeh' },
    { id: 'prairie-dusk', label: 'Prairie Dusk', icon: '🌅', group: 'Nature', prompt: 'a golden prairie at dusk' },
    { id: 'forest-path', label: 'Forest Path', icon: '🌲', group: 'Nature', prompt: 'a sun-dappled forest path with light shafts through tall trees' },
    { id: 'autumn-park', label: 'Autumn Park', icon: '🍁', group: 'Nature', prompt: 'a park ablaze with autumn reds and golds, leaves drifting' },
    { id: 'cherry-blossoms', label: 'Cherry Blossoms', icon: '🌸', group: 'Nature', prompt: 'an avenue of cherry trees in full pink blossom' },
    { id: 'lavender-field', label: 'Lavender Field', icon: '💜', group: 'Nature', prompt: 'endless rows of purple lavender under a Provencal sky' },
    { id: 'mountain-peak', label: 'Mountain Peak', icon: '🏔️', group: 'Nature', prompt: 'a dramatic alpine ridgeline with snow-capped peaks behind' },
    { id: 'alpine-lake', label: 'Alpine Lake', icon: '🏞️', group: 'Nature', prompt: 'a mirror-still alpine lake reflecting pines and peaks' },
    { id: 'desert-dunes', label: 'Desert Dunes', icon: '🏜️', group: 'Nature', prompt: 'sweeping golden desert dunes with long evening shadows' },
    { id: 'waterfall', label: 'Waterfall', icon: '💦', group: 'Nature', prompt: 'a misty waterfall cascading into a fern-lined gorge' },
    { id: 'wildflower-meadow', label: 'Wildflower Meadow', icon: '🌼', group: 'Nature', prompt: 'a meadow thick with wildflowers under a big summer sky' },
    { id: 'snowy-pines', label: 'Snowy Pines', icon: '❄️', group: 'Nature', prompt: 'a hushed snowfall over frosted pine trees' },
    { id: 'ocean-cliff', label: 'Ocean Cliff', icon: '🌊', group: 'Nature', prompt: 'a windswept headland above a crashing turquoise sea' },
    { id: 'tropical-beach', label: 'Tropical Beach', icon: '🏝️', group: 'Nature', prompt: 'a white-sand beach with leaning palms and clear shallows' },
    // ── Home & Life (13) ─────────────────────────────────────────────────────
    { id: 'home-kitchen', label: 'Home Kitchen', icon: '🍳', group: 'Home & Life', prompt: 'a warm farmhouse-style home kitchen with morning light on open shelves' },
    { id: 'living-room', label: 'Living Room', icon: '🛋️', group: 'Home & Life', prompt: 'a cozy living room with a linen sofa, plants and soft lamplight' },
    { id: 'reading-nook', label: 'Reading Nook', icon: '📖', group: 'Home & Life', prompt: 'a window-seat reading nook stacked with well-loved books' },
    { id: 'front-porch', label: 'Front Porch', icon: '🏡', group: 'Home & Life', prompt: 'a wooden front porch with a swing and hanging ferns at golden hour' },
    { id: 'backyard-bbq', label: 'Backyard BBQ', icon: '🍔', group: 'Home & Life', prompt: 'a backyard barbecue with string lights and drifting grill smoke' },
    { id: 'cozy-cafe', label: 'Cozy Café', icon: '🥐', group: 'Home & Life', prompt: 'a snug neighborhood café with latte art and rain on the window' },
    { id: 'bookstore', label: 'Bookstore', icon: '📚', group: 'Home & Life', prompt: 'a labyrinthine secondhand bookstore with ladders and warm lamps' },
    { id: 'greenhouse', label: 'Greenhouse', icon: '🪴', group: 'Home & Life', prompt: 'a glass greenhouse lush with tomatoes, herbs and hazy sunbeams' },
    { id: 'art-studio', label: 'Art Studio', icon: '🖌️', group: 'Home & Life', prompt: 'a paint-splattered artist studio with canvases and north light' },
    { id: 'music-room', label: 'Music Room', icon: '🎹', group: 'Home & Life', prompt: 'a home music room with an upright piano and framed records' },
    { id: 'garage-workshop', label: 'Garage Workshop', icon: '🔧', group: 'Home & Life', prompt: 'a tidy garage workshop with pegboard tools and sawdust in the light' },
    { id: 'holiday-hearth', label: 'Holiday Hearth', icon: '🎄', group: 'Home & Life', prompt: 'a decorated hearth with stockings, garlands and firelight' },
    { id: 'farmers-market', label: 'Farmers Market', icon: '🥕', group: 'Home & Life', prompt: 'a Saturday farmers market with canvas stalls and crates of produce' },
    // ── Work Environments (20) ───────────────────────────────────────────────
    { id: 'steel-mill', label: 'Steel Mill', icon: '🏭', group: 'Work', prompt: 'a steel-mill interior with sparks and molten furnace light' },
    { id: 'kitchen', label: 'Pro Kitchen', icon: '🍳', group: 'Work', prompt: 'a stainless-steel professional kitchen, softly blurred' },
    { id: 'hospital-ward', label: 'Hospital Ward', icon: '🏥', group: 'Work', prompt: 'a bright modern hospital corridor with soft clinical light' },
    { id: 'operating-room', label: 'Operating Room', icon: '🩻', group: 'Work', prompt: 'a state-of-the-art operating theater under cool surgical lights' },
    { id: 'fire-station', label: 'Fire Station', icon: '🚒', group: 'Work', prompt: 'a fire station bay with a gleaming red engine behind' },
    { id: 'police-precinct', label: 'Precinct', icon: '🚓', group: 'Work', prompt: 'a police precinct with flags and a duty board, softly blurred' },
    { id: 'cockpit', label: 'Cockpit', icon: '✈️', group: 'Work', prompt: 'an airliner cockpit aglow with instrument panels' },
    { id: 'airport-tarmac', label: 'Tarmac', icon: '🛫', group: 'Work', prompt: 'an airport tarmac at sunrise with a jet silhouetted behind' },
    { id: 'classroom', label: 'Classroom', icon: '🏫', group: 'Work', prompt: 'a cheerful classroom with a chalkboard full of diagrams' },
    { id: 'lecture-hall', label: 'Lecture Hall', icon: '🎓', group: 'Work', prompt: 'a tiered university lecture hall with equations on the boards' },
    { id: 'laboratory', label: 'Laboratory', icon: '🧪', group: 'Work', prompt: 'a research laboratory with glassware, pipettes and cool blue light' },
    { id: 'server-room', label: 'Server Room', icon: '🖥️', group: 'Work', prompt: 'rows of server racks with blinking status lights in cool air' },
    { id: 'construction-site', label: 'Construction Site', icon: '🏗️', group: 'Work', prompt: 'a high-rise construction site with cranes against the sky' },
    { id: 'wood-shop', label: 'Wood Shop', icon: '🪚', group: 'Work', prompt: 'a carpentry shop with workbenches, clamps and curls of shavings' },
    { id: 'auto-garage', label: 'Auto Garage', icon: '🚗', group: 'Work', prompt: 'an auto garage with a car on the lift and rolling tool chests' },
    { id: 'farm-barn', label: 'Farm Barn', icon: '🐄', group: 'Work', prompt: 'a timber barn with hay bales and morning light through the boards' },
    { id: 'orchard', label: 'Orchard', icon: '🍏', group: 'Work', prompt: 'an apple orchard heavy with fruit, ladders against the trees' },
    { id: 'fishing-harbor', label: 'Fishing Harbor', icon: '⛵', group: 'Work', prompt: 'a working fishing harbor with nets, floats and moored boats' },
    { id: 'newsroom', label: 'Newsroom', icon: '📰', group: 'Work', prompt: 'a buzzing newsroom of monitors and headlines, softly blurred' },
    { id: 'courtroom', label: 'Courtroom', icon: '🏛️', group: 'Work', prompt: 'a wood-paneled courtroom with the bench and flags behind' },
    // ── Historical (13) ──────────────────────────────────────────────────────
    { id: 'castle-hall', label: 'Castle Hall', icon: '🏰', group: 'Historical', prompt: 'a stone castle hall with heraldic banners and torchlight' },
    { id: 'stormy-harbor', label: 'Stormy Harbor', icon: '🌊', group: 'Historical', prompt: 'a weathered harbor under a stormy sea sky' },
    { id: 'fireside-study', label: 'Fireside Study', icon: '🕯️', group: 'Historical', prompt: 'a candlelit study with a stone fireplace' },
    { id: 'library', label: 'Library', icon: '📚', group: 'Historical', prompt: 'a wood-paneled library with shelves of leather-bound books in warm lamplight' },
    { id: 'farmhouse', label: 'Farmhouse', icon: '🌾', group: 'Historical', prompt: 'a white wooden farmhouse with a gothic window under a plain midwestern sky' },
    { id: 'throne-room', label: 'Throne Room', icon: '👑', group: 'Historical', prompt: 'a gilded throne room with velvet drapes and marble columns' },
    { id: 'cathedral', label: 'Cathedral', icon: '⛪', group: 'Historical', prompt: 'a gothic cathedral nave with stained-glass light pooling on stone' },
    { id: 'roman-forum', label: 'Roman Forum', icon: '🏺', group: 'Historical', prompt: 'marble columns and laurels of a Roman forum at midday' },
    { id: 'egyptian-temple', label: 'Egyptian Temple', icon: '𓂀', group: 'Historical', prompt: 'a torch-lit Egyptian temple wall carved with hieroglyphs' },
    { id: 'viking-longhouse', label: 'Viking Longhouse', icon: '🛡️', group: 'Historical', prompt: 'a smoky viking longhouse with carved beams and firelight' },
    { id: 'samurai-dojo', label: 'Samurai Dojo', icon: '🏯', group: 'Historical', prompt: 'a serene dojo with paper screens, tatami and a raked garden beyond' },
    { id: 'speakeasy', label: 'Speakeasy', icon: '🥃', group: 'Historical', prompt: 'a 1920s speakeasy with tufted leather, brass and low amber light' },
    { id: 'victorian-parlor', label: 'Victorian Parlor', icon: '🕰️', group: 'Historical', prompt: 'a Victorian parlor with damask wallpaper and a mantel clock' },
    // ── Fantasy & Fun (10) ───────────────────────────────────────────────────
    { id: 'stage', label: 'Concert Stage', icon: '🎤', group: 'Fantasy & Fun', prompt: 'a concert stage with haze and colored lights' },
    { id: 'starfield', label: 'Space', icon: '🌌', group: 'Fantasy & Fun', prompt: 'a spacecraft interior with Earth and stars visible through a porthole' },
    { id: 'pirate-deck', label: 'Pirate Deck', icon: '🏴‍☠️', group: 'Fantasy & Fun', prompt: 'the deck of a tall ship with rigging, cannon and open sea' },
    { id: 'enchanted-forest', label: 'Enchanted Forest', icon: '🧚', group: 'Fantasy & Fun', prompt: 'a twilight forest aglow with fireflies and luminous mushrooms' },
    { id: 'dragon-lair', label: 'Dragon Lair', icon: '🐉', group: 'Fantasy & Fun', prompt: 'a cavern hoard of gold coins with distant dragon-fire glow' },
    { id: 'airship-deck', label: 'Airship Deck', icon: '🎈', group: 'Fantasy & Fun', prompt: 'the brass-railed deck of a steampunk airship above the clouds' },
    { id: 'neon-arcade', label: 'Neon Arcade', icon: '🕹️', group: 'Fantasy & Fun', prompt: 'a retro arcade glowing with cabinet screens and neon grids' },
    { id: 'circus-ring', label: 'Circus Ring', icon: '🎪', group: 'Fantasy & Fun', prompt: 'a big-top circus ring with sawdust and a spotlight beam' },
    { id: 'moon-base', label: 'Moon Base', icon: '🌕', group: 'Fantasy & Fun', prompt: 'a lunar base window overlooking gray craters and the blue Earth' },
    { id: 'underwater-reef', label: 'Coral Reef', icon: '🐠', group: 'Fantasy & Fun', prompt: 'a sunlit coral reef teeming with fish, shafts of light from above' },
    // ── Sun & Sea (15) ───────────────────────────────────────────────────────
    { id: 'sunny-boardwalk', label: 'Sunny Boardwalk', icon: '🌞', group: 'Sun & Sea', prompt: 'a sunlit seaside boardwalk with striped umbrellas and a bright blue sky' },
    { id: 'tide-pools', label: 'Tide Pools', icon: '🦀', group: 'Sun & Sea', prompt: 'rocky tide pools at low tide glittering in midday sun' },
    { id: 'surf-break', label: 'Surf Break', icon: '🌊', group: 'Sun & Sea', prompt: 'a sun-drenched beach with a rolling surf break and sea spray behind' },
    { id: 'sailboat-deck', label: 'Sailboat Deck', icon: '⛵', group: 'Sun & Sea', prompt: 'the teak deck of a sailboat under full sail on a bright blue sea' },
    { id: 'pool-deck', label: 'Resort Pool', icon: '🏊', group: 'Sun & Sea', prompt: 'a resort pool deck with turquoise water, loungers and palm shadows' },
    { id: 'tiki-bar', label: 'Tiki Bar', icon: '🍹', group: 'Sun & Sea', prompt: 'a thatched beach tiki bar strung with lights at golden hour' },
    { id: 'lighthouse-point', label: 'Lighthouse Point', icon: '🗼', group: 'Sun & Sea', prompt: 'a white lighthouse on a sunny headland with gulls and whitecaps' },
    { id: 'pier-noon', label: 'Pier at Noon', icon: '🎣', group: 'Sun & Sea', prompt: 'a long wooden pier stretching into sparkling water under high noon sun' },
    { id: 'palm-promenade', label: 'Palm Promenade', icon: '🌴', group: 'Sun & Sea', prompt: 'a palm-lined seaside promenade in bright tropical light' },
    { id: 'catamaran-bow', label: 'Catamaran Bow', icon: '🛥️', group: 'Sun & Sea', prompt: 'the bow netting of a catamaran over clear turquoise shallows' },
    { id: 'beach-bonfire', label: 'Beach Bonfire', icon: '🔥', group: 'Sun & Sea', prompt: 'a beach bonfire at sunset with an orange sky and lapping waves' },
    { id: 'dune-grass', label: 'Dune Grass', icon: '🌾', group: 'Sun & Sea', prompt: 'wind-blown dune grass and a pale sandy path down to the sea' },
    { id: 'snorkel-lagoon', label: 'Snorkel Lagoon', icon: '🐠', group: 'Sun & Sea', prompt: 'a shallow tropical lagoon of glassy turquoise water and white sand' },
    { id: 'fishing-pier-dawn', label: 'Pier at Dawn', icon: '🌅', group: 'Sun & Sea', prompt: 'a quiet fishing pier at dawn with a pink sky and calm water' },
    { id: 'marina-sunset', label: 'Marina Sunset', icon: '🌇', group: 'Sun & Sea', prompt: 'a marina of moored yachts glowing in warm sunset light' },
    // ── Sports & Action (15) ─────────────────────────────────────────────────
    { id: 'stadium-lights', label: 'Stadium Lights', icon: '🏟️', group: 'Sports & Action', prompt: 'a packed stadium under floodlights with a roaring blurred crowd' },
    { id: 'boxing-ring', label: 'Boxing Ring', icon: '🥊', group: 'Sports & Action', prompt: 'a boxing ring under a hard overhead light, ropes in the foreground' },
    { id: 'basketball-court', label: 'Basketball Court', icon: '🏀', group: 'Sports & Action', prompt: 'a polished hardwood basketball court with a hoop and arena lights behind' },
    { id: 'baseball-dugout', label: 'Baseball Dugout', icon: '⚾', group: 'Sports & Action', prompt: 'a baseball dugout rail with the green diamond and stands beyond' },
    { id: 'pit-lane', label: 'Pit Lane', icon: '🏁', group: 'Sports & Action', prompt: 'a race-track pit lane with garages, tire stacks and grandstands behind' },
    { id: 'ski-slope', label: 'Ski Slope', icon: '⛷️', group: 'Sports & Action', prompt: 'a sunlit alpine ski slope with fresh powder and jagged peaks' },
    { id: 'skate-park', label: 'Skate Park', icon: '🛹', group: 'Sports & Action', prompt: 'a concrete skate park bowl with graffiti and afternoon sun' },
    { id: 'climbing-wall', label: 'Climbing Wall', icon: '🧗', group: 'Sports & Action', prompt: 'an indoor climbing wall of bright holds and chalk dust' },
    { id: 'hockey-rink', label: 'Hockey Rink', icon: '🏒', group: 'Sports & Action', prompt: 'a hockey rink of bright white ice, boards and glass, arena lights above' },
    { id: 'golf-fairway', label: 'Golf Fairway', icon: '⛳', group: 'Sports & Action', prompt: 'a manicured golf fairway at golden hour with a flag on the green beyond' },
    { id: 'tennis-court', label: 'Tennis Court', icon: '🎾', group: 'Sports & Action', prompt: 'a clay tennis court in bright sun with a low net and white lines' },
    { id: 'iron-gym', label: 'Iron Gym', icon: '🏋️', group: 'Sports & Action', prompt: 'a gritty iron gym of racks, chalk and shafts of window light' },
    { id: 'velodrome', label: 'Velodrome', icon: '🚴', group: 'Sports & Action', prompt: 'a steep wooden velodrome track curving under bright lights' },
    { id: 'marathon-finish', label: 'Marathon Finish', icon: '🏃', group: 'Sports & Action', prompt: 'a marathon finish line with banners, confetti and a cheering crowd' },
    { id: 'night-football', label: 'Friday Night Lights', icon: '🏈', group: 'Sports & Action', prompt: 'a football field at night under stadium lights with fog on the grass' },
    // ── World & Travel (15) ──────────────────────────────────────────────────
    { id: 'tokyo-crossing', label: 'Tokyo Crossing', icon: '🗼', group: 'World & Travel', prompt: 'a neon-lit Tokyo crossing at night, crowds and signs softly blurred' },
    { id: 'paris-cafe', label: 'Paris Café', icon: '🥐', group: 'World & Travel', prompt: 'a Parisian café terrace with wicker chairs and a boulevard of stone façades' },
    { id: 'santorini-terrace', label: 'Santorini', icon: '🇬🇷', group: 'World & Travel', prompt: 'a whitewashed Santorini terrace with blue domes over the caldera' },
    { id: 'venice-canal', label: 'Venice Canal', icon: '🚣', group: 'World & Travel', prompt: 'a Venetian canal with gondolas, ochre walls and a stone bridge' },
    { id: 'moroccan-souk', label: 'Moroccan Souk', icon: '🏮', group: 'World & Travel', prompt: 'a Moroccan souk of hanging lanterns, spice sacks and patterned rugs' },
    { id: 'black-sand-beach', label: 'Black Sand Beach', icon: '🌑', group: 'World & Travel', prompt: 'an Icelandic black-sand beach with basalt stacks and grey surf' },
    { id: 'kyoto-gate', label: 'Kyoto Torii', icon: '⛩️', group: 'World & Travel', prompt: 'a vermilion Kyoto shrine gate in a tunnel of torii with maple leaves' },
    { id: 'inca-terraces', label: 'Cloud Terraces', icon: '🏔️', group: 'World & Travel', prompt: 'misty green mountain terraces of ancient stone under drifting cloud' },
    { id: 'desert-oasis', label: 'Desert Oasis', icon: '🏜️', group: 'World & Travel', prompt: 'a palm-fringed desert oasis with a still pool and golden dunes beyond' },
    { id: 'havana-street', label: 'Havana Street', icon: '🚗', group: 'World & Travel', prompt: 'a pastel Havana street with vintage cars and peeling colonial balconies' },
    { id: 'alpine-village', label: 'Alpine Village', icon: '🏘️', group: 'World & Travel', prompt: 'a wooden alpine village with flower boxes and snowy peaks behind' },
    { id: 'highland-glen', label: 'Highland Glen', icon: '🏴', group: 'World & Travel', prompt: 'a Scottish highland glen of heather, mist and a distant loch' },
    { id: 'great-wall', label: 'The Great Wall', icon: '🧱', group: 'World & Travel', prompt: 'a stone wall winding over green ridges under a hazy sky' },
    { id: 'amalfi-cliffs', label: 'Amalfi Cliffs', icon: '🍋', group: 'World & Travel', prompt: 'pastel cliffside villages tumbling to a turquoise Amalfi sea' },
    { id: 'safari-savanna', label: 'Safari Savanna', icon: '🦁', group: 'World & Travel', prompt: 'a golden savanna at dusk with acacia trees and distant herds' },
    // ── Season & Weather (10) ────────────────────────────────────────────────
    { id: 'first-snow', label: 'First Snow', icon: '🌨️', group: 'Season & Weather', prompt: 'a quiet street under the first snowfall, streetlamps glowing' },
    { id: 'summer-storm', label: 'Summer Storm', icon: '⛈️', group: 'Season & Weather', prompt: 'a dramatic summer thunderstorm sky over open fields, lightning far off' },
    { id: 'fog-harbor', label: 'Fog Harbor', icon: '🌫️', group: 'Season & Weather', prompt: 'a fog-bound harbor at dawn, masts fading into the mist' },
    { id: 'monsoon-street', label: 'Monsoon Street', icon: '🌧️', group: 'Season & Weather', prompt: 'a rain-slick street in warm monsoon rain with glowing reflections' },
    { id: 'midnight-sun', label: 'Midnight Sun', icon: '🌞', group: 'Season & Weather', prompt: 'a midnight-sun coastline of low gold light and pastel sky' },
    { id: 'aurora-sky', label: 'Aurora', icon: '🌌', group: 'Season & Weather', prompt: 'a green and violet aurora rippling over a snowy night landscape' },
    { id: 'harvest-moon', label: 'Harvest Moon', icon: '🌕', group: 'Season & Weather', prompt: 'a huge orange harvest moon rising over stubble fields' },
    { id: 'spring-rain', label: 'Spring Rain', icon: '🌸', group: 'Season & Weather', prompt: 'a blossoming garden in soft spring rain, petals on wet stone' },
    { id: 'indian-summer', label: 'Indian Summer', icon: '🍂', group: 'Season & Weather', prompt: 'a hazy late-summer afternoon of golden leaves and long shadows' },
    { id: 'winter-market', label: 'Winter Market', icon: '🎄', group: 'Season & Weather', prompt: 'a snowy Christmas market of wooden stalls, lights and steam' },
    // ── Sci-Fi & Space (12) ──────────────────────────────────────────────────
    { id: 'starship-bridge', label: 'Starship Bridge', icon: '🖖', group: 'Sci-Fi & Space', prompt: 'the bridge of a starship with glowing consoles and a viewport of stars' },
    { id: 'cyberpunk-alley', label: 'Cyberpunk Alley', icon: '🌆', group: 'Sci-Fi & Space', prompt: 'a rain-soaked cyberpunk alley of neon signs, holograms and steam' },
    { id: 'hangar-bay', label: 'Hangar Bay', icon: '🚀', group: 'Sci-Fi & Space', prompt: 'a cavernous spacecraft hangar bay with landing lights and mist' },
    { id: 'alien-jungle', label: 'Alien Jungle', icon: '🪐', group: 'Sci-Fi & Space', prompt: 'an alien jungle of bioluminescent plants under twin moons' },
    { id: 'orbital-window', label: 'Orbital Window', icon: '🌍', group: 'Sci-Fi & Space', prompt: 'a space station observation window with Earth curving below' },
    { id: 'mech-hangar', label: 'Mech Hangar', icon: '🤖', group: 'Sci-Fi & Space', prompt: 'a hangar of towering mechs, scaffolding and welding sparks' },
    { id: 'desert-planet', label: 'Desert Planet', icon: '🪐', group: 'Sci-Fi & Space', prompt: 'a wind-carved desert planet with rust-red rock and two suns' },
    { id: 'cryo-lab', label: 'Cryo Lab', icon: '🧊', group: 'Sci-Fi & Space', prompt: 'a frosted cryogenic laboratory of glowing pods and cold blue light' },
    { id: 'neo-tokyo', label: 'Neo Megacity', icon: '🏙️', group: 'Sci-Fi & Space', prompt: 'a futuristic megacity skyline of floating ads and flying vehicles' },
    { id: 'mars-dome', label: 'Mars Dome', icon: '🔴', group: 'Sci-Fi & Space', prompt: 'a Mars colony dome with red terrain outside the glass' },
    { id: 'asteroid-outpost', label: 'Asteroid Outpost', icon: '☄️', group: 'Sci-Fi & Space', prompt: 'a mining outpost on an asteroid with drilling rigs and a starry void' },
    { id: 'holodeck-grid', label: 'Holo Grid', icon: '🟩', group: 'Sci-Fi & Space', prompt: 'a glowing holographic grid room dissolving into a simulated vista' },
    // ── Fantasy Realms (12) ──────────────────────────────────────────────────
    { id: 'wizard-tower', label: 'Wizard Tower', icon: '🔮', group: 'Fantasy Realms', prompt: 'the top of a wizard tower crowded with books, orreries and stained glass' },
    { id: 'elven-glade', label: 'Elven Glade', icon: '🧝', group: 'Fantasy Realms', prompt: 'a sunlit elven glade of silver trees and drifting motes' },
    { id: 'dwarven-forge', label: 'Dwarven Forge', icon: '⚒️', group: 'Fantasy Realms', prompt: 'a vast dwarven forge hall of pillars, molten channels and anvils' },
    { id: 'floating-islands', label: 'Floating Islands', icon: '☁️', group: 'Fantasy Realms', prompt: 'floating sky islands with waterfalls pouring into the clouds' },
    { id: 'crystal-cave', label: 'Crystal Cave', icon: '💎', group: 'Fantasy Realms', prompt: 'a cavern of glowing violet and teal crystals' },
    { id: 'haunted-manor', label: 'Haunted Manor', icon: '🕯️', group: 'Fantasy Realms', prompt: 'a moonlit haunted manor hall with cobwebs and flickering candles' },
    { id: 'faerie-ring', label: 'Faerie Ring', icon: '🍄', group: 'Fantasy Realms', prompt: 'a moonlit faerie ring of mushrooms and fireflies in a mossy wood' },
    { id: 'ice-palace', label: 'Ice Palace', icon: '❄️', group: 'Fantasy Realms', prompt: 'a shimmering ice palace hall of frozen pillars and blue light' },
    { id: 'volcano-forge', label: 'Volcano Forge', icon: '🌋', group: 'Fantasy Realms', prompt: 'a lava-lit volcanic forge with rivers of magma below' },
    { id: 'mushroom-forest', label: 'Mushroom Forest', icon: '🍄', group: 'Fantasy Realms', prompt: 'a forest of giant glowing mushrooms in a misty twilight' },
    { id: 'sky-temple', label: 'Sky Temple', icon: '🛕', group: 'Fantasy Realms', prompt: 'a temple above the clouds with golden spires and prayer flags' },
    { id: 'underworld-river', label: 'Underworld River', icon: '⚰️', group: 'Fantasy Realms', prompt: 'a dark underworld river with a lantern-lit boat and mist' },
    // ── Retro & Pop (10) ─────────────────────────────────────────────────────
    { id: 'fifties-diner', label: '50s Diner', icon: '🍔', group: 'Retro & Pop', prompt: 'a chrome 1950s diner with red booths, checkerboard floor and neon' },
    { id: 'disco-floor', label: 'Disco Floor', icon: '🪩', group: 'Retro & Pop', prompt: 'a 1970s disco with a mirror ball, light-up floor and haze' },
    { id: 'eighties-mall', label: '80s Mall', icon: '📼', group: 'Retro & Pop', prompt: 'a 1980s shopping mall of neon signs, palms and pastel tile' },
    { id: 'drive-in', label: 'Drive-In', icon: '🎬', group: 'Retro & Pop', prompt: 'a drive-in movie lot at dusk with a glowing screen and classic cars' },
    { id: 'roller-rink', label: 'Roller Rink', icon: '🛼', group: 'Retro & Pop', prompt: 'a roller rink of colored lights, wooden floor and disco haze' },
    { id: 'jukebox-bar', label: 'Jukebox Corner', icon: '🎶', group: 'Retro & Pop', prompt: 'a dim bar corner with a glowing jukebox and vinyl booths' },
    { id: 'vintage-gas-station', label: 'Vintage Gas Station', icon: '⛽', group: 'Retro & Pop', prompt: 'a retro roadside gas station with round pumps at sunset' },
    { id: 'soda-fountain', label: 'Soda Fountain', icon: '🥤', group: 'Retro & Pop', prompt: 'a vintage soda fountain counter with chrome stools and glass jars' },
    { id: 'record-store', label: 'Record Store', icon: '💿', group: 'Retro & Pop', prompt: 'a crowded record store of vinyl crates and gig posters' },
    { id: 'boardwalk-arcade', label: 'Boardwalk Arcade', icon: '🎯', group: 'Retro & Pop', prompt: 'a boardwalk arcade of flashing cabinets and prize counters' },
    // ── Grand & Formal (11) ──────────────────────────────────────────────────
    { id: 'opera-box', label: 'Opera Box', icon: '🎭', group: 'Grand & Formal', prompt: 'a gilded opera house box with velvet drapes and the glowing hall beyond' },
    { id: 'grand-staircase', label: 'Grand Staircase', icon: '🪜', group: 'Grand & Formal', prompt: 'a sweeping marble grand staircase under a crystal chandelier' },
    { id: 'ballroom', label: 'Ballroom', icon: '💃', group: 'Grand & Formal', prompt: 'a glittering ballroom of chandeliers, mirrors and parquet floor' },
    { id: 'museum-hall', label: 'Museum Hall', icon: '🖼️', group: 'Grand & Formal', prompt: 'a grand art museum hall of marble columns and framed masterpieces' },
    { id: 'palace-garden', label: 'Palace Garden', icon: '🌹', group: 'Grand & Formal', prompt: 'a formal palace garden of clipped hedges, fountains and gravel paths' },
    { id: 'embassy-reception', label: 'Embassy Reception', icon: '🏳️', group: 'Grand & Formal', prompt: 'an embassy reception room with flags, gilt frames and chandeliers' },
    { id: 'yacht-club', label: 'Yacht Club', icon: '⚓', group: 'Grand & Formal', prompt: 'a yacht club veranda with white railings and moored sailboats' },
    { id: 'wine-cellar', label: 'Wine Cellar', icon: '🍷', group: 'Grand & Formal', prompt: 'a vaulted stone wine cellar of oak barrels and candlelight' },
    { id: 'rooftop-gala', label: 'Rooftop Gala', icon: '🥂', group: 'Grand & Formal', prompt: 'a rooftop gala at night with string lights and a glittering skyline' },
    { id: 'cloister', label: 'Cloister', icon: '⛪', group: 'Grand & Formal', prompt: 'a Gothic cathedral cloister of stone arches and a sunlit garth' },
    { id: 'conservatory', label: 'Conservatory', icon: '🪴', group: 'Grand & Formal', prompt: 'a Victorian glass conservatory of ferns, palms and iron tracery' },
];
/** @description 70 interchangeable clothing styles (test-enforced). */
exports.CLOTHING = [
    // ── Business (12) ────────────────────────────────────────────────────────
    { id: 'keep', label: 'Keep My Clothes', icon: '👕', group: 'Business', prompt: 'the same clothing as in the photo, neatened up' },
    { id: 'dark-suit', label: 'Dark Suit', icon: '🤵', group: 'Business', prompt: 'a tailored dark business suit with a crisp shirt' },
    { id: 'navy-suit', label: 'Navy Suit', icon: '💼', group: 'Business', prompt: 'a sharp navy suit with a white shirt and understated tie' },
    { id: 'gray-suit', label: 'Gray Suit', icon: '🩶', group: 'Business', prompt: 'a light-gray suit with an open-collar white shirt' },
    { id: 'pinstripe', label: 'Pinstripe', icon: '📊', group: 'Business', prompt: 'a classic pinstripe suit with a silk pocket square' },
    { id: 'three-piece', label: 'Three-Piece', icon: '🎩', group: 'Business', prompt: 'a three-piece suit with a buttoned waistcoat and watch chain' },
    { id: 'power-blazer', label: 'Power Blazer', icon: '🔴', group: 'Business', prompt: 'a bold structured blazer over a silk shell top' },
    { id: 'silk-blouse', label: 'Silk Blouse', icon: '🎀', group: 'Business', prompt: 'an elegant silk blouse with tailored trousers' },
    { id: 'pencil-suit', label: 'Tailored Skirt Suit', icon: '👩‍💼', group: 'Business', prompt: 'a tailored skirt suit with a fitted jacket' },
    { id: 'turtleneck-blazer', label: 'Turtleneck + Blazer', icon: '🖤', group: 'Business', prompt: 'a fine black turtleneck under an unstructured blazer' },
    { id: 'overcoat', label: 'Wool Overcoat', icon: '🧥', group: 'Business', prompt: 'a long camel wool overcoat over business attire with a scarf' },
    { id: 'trench-coat', label: 'Trench Coat', icon: '🕵️‍♀️', group: 'Business', prompt: 'a belted khaki trench coat over smart clothes' },
    // ── Business Casual (10) ─────────────────────────────────────────────────
    { id: 'business-casual', label: 'Blazer Casual', icon: '👔', group: 'Business Casual', prompt: 'smart business-casual attire, a blazer over an open-collar shirt' },
    { id: 'smart-creative', label: 'Smart Creative', icon: '🎨', group: 'Business Casual', prompt: 'smart-creative attire, a dark knit under an unstructured jacket' },
    { id: 'knit-polo', label: 'Knit Polo', icon: '🐎', group: 'Business Casual', prompt: 'a fine-knit polo with tailored chinos' },
    { id: 'oxford-chinos', label: 'Oxford + Chinos', icon: '🧵', group: 'Business Casual', prompt: 'a rolled-sleeve oxford shirt with chinos' },
    { id: 'cardigan', label: 'Cardigan', icon: '🧶', group: 'Business Casual', prompt: 'a merino cardigan over a collared shirt' },
    { id: 'denim-blazer', label: 'Denim + Blazer', icon: '👖', group: 'Business Casual', prompt: 'dark selvedge denim with a soft knit tee and blazer' },
    { id: 'linen-shirt', label: 'Linen Shirt', icon: '🌾', group: 'Business Casual', prompt: 'a relaxed linen shirt with the sleeves rolled' },
    { id: 'sweater-vest', label: 'Sweater Vest', icon: '🦺', group: 'Business Casual', prompt: 'a fine sweater vest over a crisp shirt' },
    { id: 'quarter-zip', label: 'Quarter-Zip', icon: '🧊', group: 'Business Casual', prompt: 'a merino quarter-zip pullover over a collared shirt' },
    { id: 'wrap-dress', label: 'Wrap Dress', icon: '💃', group: 'Business Casual', prompt: 'a polished jersey wrap dress' },
    // ── Casual & Life (12) ───────────────────────────────────────────────────
    { id: 'hoodie', label: 'Hoodie', icon: '🧢', group: 'Casual & Life', prompt: 'a clean heavyweight hoodie' },
    { id: 'denim-jacket', label: 'Denim Jacket', icon: '🤠', group: 'Casual & Life', prompt: 'a classic denim jacket over a white tee' },
    { id: 'plain-tee', label: 'Plain Tee', icon: '👕', group: 'Casual & Life', prompt: 'a well-fitted plain t-shirt' },
    { id: 'summer-dress', label: 'Summer Dress', icon: '🌻', group: 'Casual & Life', prompt: 'a breezy floral summer dress' },
    { id: 'flannel', label: 'Flannel', icon: '🪵', group: 'Casual & Life', prompt: 'a soft plaid flannel shirt' },
    { id: 'raincoat', label: 'Raincoat', icon: '🌧️', group: 'Casual & Life', prompt: 'a bright rubberized raincoat with the hood down' },
    { id: 'parka', label: 'Winter Parka', icon: '🧣', group: 'Casual & Life', prompt: 'a fur-trimmed winter parka with a chunky scarf' },
    { id: 'hiking-gear', label: 'Hiking Gear', icon: '🥾', group: 'Casual & Life', prompt: 'technical hiking layers with a daypack strap across the chest' },
    { id: 'hawaiian-shirt', label: 'Hawaiian Shirt', icon: '🌺', group: 'Casual & Life', prompt: 'a vintage hawaiian print shirt' },
    { id: 'cozy-sweater', label: 'Cozy Sweater', icon: '☕', group: 'Casual & Life', prompt: 'an oversized cable-knit sweater' },
    { id: 'tracksuit', label: 'Retro Tracksuit', icon: '🏃', group: 'Casual & Life', prompt: 'a retro striped tracksuit jacket' },
    { id: 'cycling-jersey', label: 'Cycling Jersey', icon: '🚴', group: 'Casual & Life', prompt: 'a bold team cycling jersey' },
    // ── Uniforms & Work (18) ─────────────────────────────────────────────────
    { id: 'scrubs', label: 'Scrubs', icon: '🩺', group: 'Uniforms & Work', prompt: 'teal medical scrubs with a stethoscope around the neck' },
    { id: 'surgeon-gown', label: 'Surgical Gown', icon: '🩻', group: 'Uniforms & Work', prompt: 'a sterile surgical gown with a mask pulled down around the neck' },
    { id: 'doctor-coat', label: "Doctor's Coat", icon: '🥼', group: 'Uniforms & Work', prompt: "a crisp white doctor's coat with a stethoscope around the neck" },
    { id: 'lab-coat', label: 'Lab Coat', icon: '🧪', group: 'Uniforms & Work', prompt: 'a white laboratory coat with safety glasses pushed up' },
    { id: 'firefighter-turnout', label: 'Turnout Gear', icon: '🚒', group: 'Uniforms & Work', prompt: 'firefighter turnout gear with reflective stripes, jacket open' },
    { id: 'police-uniform', label: 'Police Uniform', icon: '👮', group: 'Uniforms & Work', prompt: 'a pressed police uniform with badge and radio' },
    { id: 'pilot-uniform', label: 'Pilot Uniform', icon: '✈️', group: 'Uniforms & Work', prompt: 'an airline captain uniform with four gold stripes' },
    { id: 'flight-suit', label: 'Flight Suit', icon: '🛩️', group: 'Uniforms & Work', prompt: 'an olive aviator flight suit with squadron patches' },
    { id: 'coveralls', label: 'Mechanic Coveralls', icon: '🔧', group: 'Uniforms & Work', prompt: 'workshop coveralls with a shop rag in the pocket' },
    { id: 'hi-vis', label: 'Hi-Vis + Harness', icon: '🦺', group: 'Uniforms & Work', prompt: 'a hi-vis vest over work clothes with a safety harness' },
    { id: 'work-canvas', label: 'Work Jacket', icon: '🧰', group: 'Uniforms & Work', prompt: 'a rugged canvas work jacket with leather work gloves' },
    { id: 'barista-apron', label: 'Barista Apron', icon: '☕', group: 'Uniforms & Work', prompt: 'a denim barista apron over a rolled-sleeve shirt' },
    { id: 'leather-apron', label: 'Leather Apron', icon: '🔨', group: 'Uniforms & Work', prompt: 'a heavy leather smith apron over a work shirt' },
    { id: 'fisherman-slicker', label: 'Fisherman Slicker', icon: '🎣', group: 'Uniforms & Work', prompt: 'yellow fisherman bib overalls and slicker' },
    { id: 'conductor-uniform', label: 'Train Conductor', icon: '🚂', group: 'Uniforms & Work', prompt: 'a classic train conductor uniform with brass buttons' },
    { id: 'park-ranger', label: 'Park Ranger', icon: '🌲', group: 'Uniforms & Work', prompt: 'a park ranger uniform with shoulder patches' },
    { id: 'chef-whites', label: "Chef's Whites", icon: '👨‍🍳', group: 'Uniforms & Work', prompt: "crisp chef's whites with a knotted neckerchief" },
    { id: 'farmer-overalls', label: 'Farmer', icon: '🌾', group: 'Uniforms & Work', prompt: 'a black jacket over a collarless shirt and denim overalls' },
    // ── Occasion (8) ─────────────────────────────────────────────────────────
    { id: 'tuxedo', label: 'Tuxedo', icon: '🥂', group: 'Occasion', prompt: 'a classic black tuxedo with a bow tie' },
    { id: 'evening-gown', label: 'Evening Gown', icon: '💎', group: 'Occasion', prompt: 'an elegant formal evening gown' },
    { id: 'academic-gown', label: 'Graduation Gown', icon: '🎓', group: 'Occasion', prompt: 'a black academic graduation gown with a colored hood' },
    { id: 'judge-robe', label: 'Judicial Robes', icon: '⚖️', group: 'Occasion', prompt: 'formal black judicial robes with a white collar' },
    { id: 'dress-uniform', label: 'Dress Uniform', icon: '🎖️', group: 'Occasion', prompt: 'a decorated military dress uniform with medals and epaulettes' },
    { id: 'kilt', label: 'Highland Kilt', icon: '🏴', group: 'Occasion', prompt: 'full highland dress with tartan kilt and sporran' },
    { id: 'kimono', label: 'Formal Kimono', icon: '🎎', group: 'Occasion', prompt: 'an exquisite formal silk kimono with an obi sash' },
    { id: 'sari', label: 'Silk Sari', icon: '🪔', group: 'Occasion', prompt: 'a richly embroidered silk sari with gold border' },
    // ── Costume & History (10) ───────────────────────────────────────────────
    { id: 'renaissance-doublet', label: 'Renaissance Doublet', icon: '👑', group: 'Costume & History', prompt: 'an ornate velvet Renaissance doublet with a white ruff collar and a gold chain of office' },
    { id: 'spacesuit', label: 'Spacesuit', icon: '🚀', group: 'Costume & History', prompt: 'a white NASA-style spacesuit' },
    { id: 'peacoat', label: 'Navy Peacoat', icon: '⚓', group: 'Costume & History', prompt: 'a navy wool peacoat' },
    { id: 'wizard-robes', label: 'Wizard Robes', icon: '🧙', group: 'Costume & History', prompt: 'deep blue wizard robes embroidered with silver thread' },
    { id: 'leather-jacket', label: 'Leather Jacket', icon: '🎸', group: 'Costume & History', prompt: 'a worn black leather jacket over a band tee' },
    { id: 'duster-coat', label: 'Western Duster', icon: '🤠', group: 'Costume & History', prompt: 'a long western duster coat' },
    { id: 'plate-armor', label: 'Plate Armor', icon: '⚔️', group: 'Costume & History', prompt: 'polished steel plate armor' },
    { id: 'toga', label: 'Roman Toga', icon: '🏺', group: 'Costume & History', prompt: 'a draped white toga with a purple senatorial stripe' },
    { id: 'pirate-coat', label: 'Pirate Coat', icon: '🏴‍☠️', group: 'Costume & History', prompt: 'a weathered captain frock coat with a wide leather baldric' },
    { id: 'gatsby-tux', label: '1920s Tux', icon: '🥃', group: 'Costume & History', prompt: 'a 1920s white-tie tuxedo with slicked styling' },
    // ── Sun & Sport (15) ─────────────────────────────────────────────────────
    { id: 'rash-guard', label: 'Surf Rash Guard', icon: '🏄', group: 'Sun & Sport', prompt: 'a fitted surf rash guard and board shorts' },
    { id: 'linen-open-shirt', label: 'Open Linen Shirt', icon: '🌴', group: 'Sun & Sport', prompt: 'an open linen shirt over a white tee and board shorts' },
    { id: 'sailing-jacket', label: 'Sailing Jacket', icon: '⛵', group: 'Sun & Sport', prompt: 'a red sailing jacket with white trim' },
    { id: 'tennis-whites', label: 'Tennis Whites', icon: '🎾', group: 'Sun & Sport', prompt: 'crisp tennis whites with a collared polo' },
    { id: 'basketball-jersey', label: 'Basketball Jersey', icon: '🏀', group: 'Sun & Sport', prompt: 'a basketball jersey over a warm-up shirt, no logos' },
    { id: 'baseball-uniform', label: 'Baseball Uniform', icon: '⚾', group: 'Sun & Sport', prompt: 'a pinstriped baseball uniform with no logos' },
    { id: 'hockey-jersey', label: 'Hockey Jersey', icon: '🏒', group: 'Sun & Sport', prompt: 'a hockey jersey with shoulder pads beneath, no logos' },
    { id: 'racing-suit', label: 'Racing Suit', icon: '🏁', group: 'Sun & Sport', prompt: 'a plain racing driver fire suit with no sponsor logos' },
    { id: 'ski-jacket', label: 'Ski Jacket', icon: '⛷️', group: 'Sun & Sport', prompt: 'a bright insulated ski jacket' },
    { id: 'boxing-robe', label: 'Boxing Robe', icon: '🥊', group: 'Sun & Sport', prompt: 'a satin boxing robe with the hood down' },
    { id: 'karate-gi', label: 'Martial Arts Gi', icon: '🥋', group: 'Sun & Sport', prompt: 'a crisp white martial-arts gi with a black belt' },
    { id: 'wetsuit', label: 'Scuba Wetsuit', icon: '🤿', group: 'Sun & Sport', prompt: 'a sleek black scuba wetsuit, unzipped at the collar' },
    { id: 'rugby-kit', label: 'Rugby Kit', icon: '🏉', group: 'Sun & Sport', prompt: 'a striped rugby jersey with a raised collar' },
    { id: 'jockey-silks', label: 'Jockey Silks', icon: '🏇', group: 'Sun & Sport', prompt: 'bright jockey racing silks' },
    { id: 'fencing-whites', label: 'Fencing Whites', icon: '🤺', group: 'Sun & Sport', prompt: 'fencing whites with a padded jacket' },
    // ── Warriors & Sci-Fi (12) ───────────────────────────────────────────────
    { id: 'samurai-armor', label: 'Samurai Armor', icon: '🏯', group: 'Warriors & Sci-Fi', prompt: 'lacquered samurai o-yoroi armor with silk cords' },
    { id: 'kung-fu-silk', label: 'Kung Fu Silk', icon: '🐉', group: 'Warriors & Sci-Fi', prompt: 'a mandarin-collar silk kung-fu jacket with frog buttons' },
    { id: 'ninja-shozoku', label: 'Ninja Shozoku', icon: '🥷', group: 'Warriors & Sci-Fi', prompt: 'a dark ninja shozoku with wrapped forearms' },
    { id: 'superhero-suit', label: 'Superhero Suit', icon: '🦸', group: 'Warriors & Sci-Fi', prompt: 'a sleek superhero suit with a bold two-tone chest emblem and a short cape' },
    { id: 'team-supersuit', label: 'Team Super Suit', icon: '🦸‍♀️', group: 'Warriors & Sci-Fi', prompt: 'a matching team superhero uniform with a chest emblem and gauntlets' },
    { id: 'paladin-armor', label: 'Paladin Armor', icon: '✨', group: 'Warriors & Sci-Fi', prompt: 'gleaming paladin armor with a white tabard' },
    { id: 'space-marine', label: 'Power Armor', icon: '🛡️', group: 'Warriors & Sci-Fi', prompt: 'heavy sci-fi power armor with glowing seams' },
    { id: 'cyberpunk-jacket', label: 'Cyberpunk Jacket', icon: '🌆', group: 'Warriors & Sci-Fi', prompt: 'a neon-trimmed cyberpunk jacket with tech details' },
    { id: 'starfleet-tunic', label: 'Starship Tunic', icon: '🖖', group: 'Warriors & Sci-Fi', prompt: 'a fitted sci-fi crew tunic with a metallic collar insignia' },
    { id: 'bomber-jacket', label: 'Bomber Jacket', icon: '🧥', group: 'Warriors & Sci-Fi', prompt: 'a shearling-collared leather bomber jacket' },
    { id: 'safari-khakis', label: 'Safari Khakis', icon: '🦁', group: 'Warriors & Sci-Fi', prompt: 'a khaki safari shirt with rolled sleeves and a belt' },
    { id: 'expedition-parka', label: 'Expedition Parka', icon: '🧊', group: 'Warriors & Sci-Fi', prompt: 'a heavy fur-trimmed expedition parka' },
    // ── Retro & Occasion (13) ────────────────────────────────────────────────
    { id: 'letterman-jacket', label: 'Letterman Jacket', icon: '🏫', group: 'Retro & Occasion', prompt: 'a 1950s wool letterman jacket' },
    { id: 'flapper-dress', label: 'Flapper Dress', icon: '💃', group: 'Retro & Occasion', prompt: 'a beaded 1920s flapper dress with a feather trim' },
    { id: 'disco-suit', label: 'Disco Suit', icon: '🕺', group: 'Retro & Occasion', prompt: 'a white 1970s disco suit with a wide-collared black shirt' },
    { id: 'neon-windbreaker', label: 'Neon Windbreaker', icon: '📼', group: 'Retro & Occasion', prompt: 'a color-block 1980s neon windbreaker' },
    { id: 'grunge-denim', label: '90s Denim', icon: '🎸', group: 'Retro & Occasion', prompt: 'an oversized 1990s denim jacket over a plain tee' },
    { id: 'victorian-gown', label: 'Victorian Gown', icon: '🕰️', group: 'Retro & Occasion', prompt: 'a high-collared Victorian gown with lace' },
    { id: 'tailcoat', label: 'White-Tie Tailcoat', icon: '🎩', group: 'Retro & Occasion', prompt: 'a formal white-tie tailcoat with a wing collar' },
    { id: 'ballgown', label: 'Ballgown', icon: '👗', group: 'Retro & Occasion', prompt: 'a sweeping satin ballgown' },
    { id: 'mariachi-suit', label: 'Mariachi Suit', icon: '🎺', group: 'Retro & Occasion', prompt: 'an embroidered charro mariachi suit' },
    { id: 'matador-suit', label: 'Matador Suit', icon: '🌹', group: 'Retro & Occasion', prompt: 'a gold-embroidered matador traje de luces' },
    { id: 'steampunk-waistcoat', label: 'Steampunk Waistcoat', icon: '⚙️', group: 'Retro & Occasion', prompt: 'a brass-buttoned steampunk waistcoat with goggles on a strap' },
    { id: 'elven-leathers', label: 'Elven Leathers', icon: '🧝', group: 'Retro & Occasion', prompt: 'fitted green elven leather armor with leaf tooling' },
    { id: 'royal-robes', label: 'Royal Robes', icon: '👑', group: 'Retro & Occasion', prompt: 'ermine-trimmed crimson royal robes' },
];
/** @description 30 interchangeable headwear items (test-enforced). 'none' composes to nothing. */
exports.HEADWEAR = [
    { id: 'none', label: 'No Hat', icon: '🚫', group: 'Everyday', prompt: '' },
    { id: 'baseball-cap', label: 'Baseball Cap', icon: '🧢', group: 'Everyday', prompt: 'a clean baseball cap' },
    { id: 'beanie', label: 'Beanie', icon: '🧶', group: 'Everyday', prompt: 'a snug knit beanie' },
    { id: 'flat-cap', label: 'Flat Cap', icon: '🍂', group: 'Everyday', prompt: 'a tweed flat cap' },
    { id: 'sun-hat', label: 'Sun Hat', icon: '🌞', group: 'Everyday', prompt: 'a wide-brim woven sun hat' },
    { id: 'fedora', label: 'Fedora', icon: '🕵️', group: 'Everyday', prompt: 'a classic felt fedora' },
    { id: 'beret', label: 'Beret', icon: '🎨', group: 'Everyday', prompt: 'a wool beret' },
    { id: 'bowler', label: 'Bowler', icon: '🎩', group: 'Everyday', prompt: 'a black bowler hat' },
    { id: 'boater', label: 'Straw Boater', icon: '🛶', group: 'Everyday', prompt: 'a straw boater with a striped band' },
    { id: 'top-hat', label: 'Top Hat', icon: '🎩', group: 'Everyday', prompt: 'a black silk top hat' },
    { id: 'hard-hat', label: 'Hard Hat', icon: '👷', group: 'Work', prompt: 'a yellow hard hat' },
    { id: 'chef-toque', label: 'Chef Toque', icon: '👨‍🍳', group: 'Work', prompt: "a tall white chef's toque" },
    { id: 'captains-cap', label: "Captain's Cap", icon: '⚓', group: 'Work', prompt: "a sea captain's peaked cap" },
    { id: 'peaked-cap', label: 'Military Cap', icon: '🎖️', group: 'Work', prompt: 'a military peaked cap with gold braid' },
    { id: 'police-cap', label: 'Police Cap', icon: '👮', group: 'Work', prompt: 'a police duty cap with badge' },
    { id: 'firefighter-helmet', label: 'Fire Helmet', icon: '🚒', group: 'Work', prompt: 'a firefighter helmet with the shield up' },
    { id: 'surgical-cap', label: 'Surgical Cap', icon: '🩻', group: 'Work', prompt: 'a patterned surgical cap' },
    { id: 'aviator-cap', label: 'Aviator Cap', icon: '🛩️', group: 'Work', prompt: 'a leather aviator cap with goggles pushed up' },
    { id: 'cowboy-hat', label: 'Cowboy Hat', icon: '🤠', group: 'Work', prompt: 'a wide-brim cowboy hat' },
    { id: 'pith-helmet', label: 'Explorer Pith', icon: '🧭', group: 'Work', prompt: 'a khaki explorer pith helmet' },
    { id: 'graduation-cap', label: 'Graduation Cap', icon: '🎓', group: 'Occasion', prompt: 'a mortarboard graduation cap with a tassel' },
    { id: 'crown', label: 'Crown', icon: '👑', group: 'Occasion', prompt: 'a golden jeweled crown' },
    { id: 'flower-crown', label: 'Flower Crown', icon: '🌸', group: 'Occasion', prompt: 'a delicate flower crown' },
    { id: 'laurel-wreath', label: 'Laurel Wreath', icon: '🏺', group: 'Occasion', prompt: 'a golden laurel wreath' },
    { id: 'wizard-hat', label: 'Wizard Hat', icon: '🧙', group: 'Fantasy & History', prompt: 'a tall pointed wizard hat' },
    { id: 'viking-helm', label: 'Viking Helm', icon: '🛡️', group: 'Fantasy & History', prompt: 'a riveted iron viking helm' },
    { id: 'kabuto', label: 'Samurai Kabuto', icon: '🏯', group: 'Fantasy & History', prompt: 'a lacquered samurai kabuto helmet' },
    { id: 'tricorn', label: 'Pirate Tricorn', icon: '🏴‍☠️', group: 'Fantasy & History', prompt: 'a weathered leather tricorn hat' },
    { id: 'deerstalker', label: 'Deerstalker', icon: '🔎', group: 'Fantasy & History', prompt: 'a checked deerstalker cap' },
    { id: 'nemes', label: 'Pharaoh Nemes', icon: '𓂀', group: 'Fantasy & History', prompt: 'a striped gold-and-lapis pharaoh nemes headdress' },
    // ── Sun & Sport (10) ─────────────────────────────────────────────────────
    { id: 'sombrero', label: 'Sombrero', icon: '🎺', group: 'Sun & Sport', prompt: 'a wide embroidered sombrero' },
    { id: 'bucket-hat', label: 'Bucket Hat', icon: '🪣', group: 'Sun & Sport', prompt: 'a canvas bucket hat' },
    { id: 'visor', label: 'Sports Visor', icon: '🎾', group: 'Sun & Sport', prompt: 'a sports visor' },
    { id: 'bandana', label: 'Bandana', icon: '🏴‍☠️', group: 'Sun & Sport', prompt: 'a folded bandana tied over the head' },
    { id: 'headband', label: 'Headband', icon: '🏃', group: 'Sun & Sport', prompt: 'a sweat headband' },
    { id: 'snapback', label: 'Snapback', icon: '🧢', group: 'Sun & Sport', prompt: 'a flat-brim snapback cap' },
    { id: 'motorcycle-helmet', label: 'Motorcycle Helmet', icon: '🏍️', group: 'Sun & Sport', prompt: 'a glossy motorcycle helmet with the visor up' },
    { id: 'racing-helmet', label: 'Racing Helmet', icon: '🏁', group: 'Sun & Sport', prompt: 'a racing helmet with the visor raised' },
    { id: 'ski-goggles', label: 'Beanie + Goggles', icon: '⛷️', group: 'Sun & Sport', prompt: 'a knit beanie with ski goggles pushed up' },
    { id: 'sailor-cap', label: 'Sailor Cap', icon: '⚓', group: 'Sun & Sport', prompt: 'a white sailor cap' },
    // ── World & Story (10) ───────────────────────────────────────────────────
    { id: 'panama-hat', label: 'Panama Hat', icon: '🌴', group: 'World & Story', prompt: 'a straw panama hat with a black band' },
    { id: 'ushanka', label: 'Ushanka', icon: '🧊', group: 'World & Story', prompt: 'a fur ushanka with the flaps up' },
    { id: 'conical-hat', label: 'Conical Straw Hat', icon: '🎋', group: 'World & Story', prompt: 'a woven conical straw hat' },
    { id: 'fez', label: 'Fez', icon: '🏮', group: 'World & Story', prompt: 'a maroon felt fez with a black tassel' },
    { id: 'ninja-hood', label: 'Ninja Hood', icon: '🥷', group: 'World & Story', prompt: 'a dark ninja hood leaving the face visible' },
    { id: 'domino-mask', label: 'Domino Mask', icon: '🦸', group: 'World & Story', prompt: 'a slim superhero domino mask that leaves the face fully recognizable' },
    { id: 'space-helmet-open', label: 'Space Helmet (open)', icon: '🚀', group: 'World & Story', prompt: 'a space helmet with the visor open' },
    { id: 'cavalier-hat', label: 'Cavalier Hat', icon: '🪶', group: 'World & Story', prompt: 'a feathered cavalier hat' },
    { id: 'ice-crown', label: 'Ice Crown', icon: '❄️', group: 'World & Story', prompt: 'a crown of glittering ice crystals' },
    { id: 'hooded-cloak', label: 'Hooded Cloak', icon: '🕯️', group: 'World & Story', prompt: 'a deep hooded cloak with the hood up and the face lit' },
];
/** @description 26 interchangeable props — each is a full hands/pose line (test-enforced). */
exports.PROPS = [
    { id: 'none', label: 'No Prop', icon: '🚫', group: 'Everyday', prompt: '' },
    { id: 'coffee-mug', label: 'Coffee Mug', icon: '☕', group: 'Everyday', prompt: 'both hands wrapped around a steaming coffee mug' },
    { id: 'open-book', label: 'Open Book', icon: '📖', group: 'Everyday', prompt: 'an open book held in both hands' },
    { id: 'newspaper', label: 'Newspaper', icon: '📰', group: 'Everyday', prompt: 'a folded broadsheet newspaper held in one hand' },
    { id: 'laptop', label: 'Laptop', icon: '💻', group: 'Everyday', prompt: 'a slim laptop cradled against one arm, the other hand resting on it' },
    { id: 'briefcase', label: 'Briefcase', icon: '💼', group: 'Everyday', prompt: 'a leather briefcase held at the side in one hand' },
    { id: 'umbrella', label: 'Umbrella', icon: '☂️', group: 'Everyday', prompt: 'a furled umbrella planted like a cane under one hand' },
    { id: 'bouquet', label: 'Bouquet', icon: '💐', group: 'Everyday', prompt: 'a fresh bouquet of flowers cradled in both arms' },
    { id: 'trophy', label: 'Trophy', icon: '🏆', group: 'Everyday', prompt: 'a gleaming trophy held proudly in both hands' },
    { id: 'walking-cane', label: 'Cane', icon: '🦯', group: 'Everyday', prompt: 'both hands resting on a silver-topped cane' },
    { id: 'pocket-watch', label: 'Pocket Watch', icon: '⌚', group: 'Everyday', prompt: 'one hand consulting a gold pocket watch on a chain' },
    { id: 'magnifying-glass', label: 'Magnifier', icon: '🔎', group: 'Everyday', prompt: 'a brass magnifying glass raised in one hand' },
    { id: 'globe', label: 'Globe', icon: '🌍', group: 'Scholarly', prompt: 'one hand resting on an antique desk globe' },
    { id: 'telescope', label: 'Telescope', icon: '🔭', group: 'Scholarly', prompt: 'a brass spyglass telescope held in both hands' },
    { id: 'quill', label: 'Quill', icon: '🪶', group: 'Scholarly', prompt: 'a feather quill poised in one hand over parchment' },
    { id: 'lantern', label: 'Lantern', icon: '🏮', group: 'Scholarly', prompt: 'a glowing iron lantern raised in one hand' },
    { id: 'violin', label: 'Violin', icon: '🎻', group: 'Music & Craft', prompt: 'a violin tucked under the chin, bow poised in the other hand' },
    { id: 'electric-guitar', label: 'Electric Guitar', icon: '🎸', group: 'Music & Craft', prompt: 'an electric guitar held with both hands' },
    { id: 'microphone', label: 'Microphone', icon: '🎤', group: 'Music & Craft', prompt: 'a vintage microphone gripped in one hand' },
    { id: 'chef-knife', label: "Chef's Knife", icon: '🔪', group: 'Music & Craft', prompt: "a chef's knife held at rest over a cutting board, other hand steadying it" },
    { id: 'fishing-rod', label: 'Fishing Rod', icon: '🎣', group: 'Trades & Adventure', prompt: 'a fishing rod shouldered in one hand' },
    { id: 'pitchfork', label: 'Pitchfork', icon: '🌾', group: 'Trades & Adventure', prompt: 'one hand gripping a pitchfork upright, the other at the lapel' },
    { id: 'felling-axe', label: 'Felling Axe', icon: '🪓', group: 'Trades & Adventure', prompt: 'a felling axe resting across one shoulder, gripped in one hand' },
    { id: 'smith-hammer', label: 'Smith Hammer', icon: '🔨', group: 'Trades & Adventure', prompt: 'a blacksmith hammer resting head-down under one hand like a gavel' },
    { id: 'longsword', label: 'Longsword', icon: '⚔️', group: 'Trades & Adventure', prompt: 'both hands resting on the pommel of a point-down longsword' },
    { id: 'wizard-staff', label: 'Wizard Staff', icon: '🧙', group: 'Trades & Adventure', prompt: 'one hand holding a carved wooden staff, the other cradling a faintly glowing orb' },
    // ── Sun & Sport (15) ─────────────────────────────────────────────────────
    { id: 'surfboard', label: 'Surfboard', icon: '🏄', group: 'Sun & Sport', prompt: 'a surfboard tucked under one arm' },
    { id: 'beach-ball', label: 'Beach Ball', icon: '🏐', group: 'Sun & Sport', prompt: 'a striped beach ball held on one hip' },
    { id: 'snorkel-mask', label: 'Snorkel + Fins', icon: '🤿', group: 'Sun & Sport', prompt: 'a snorkel mask and fins held in one hand' },
    { id: 'fishing-net', label: 'Fishing Net', icon: '🕸️', group: 'Sun & Sport', prompt: 'a fishing net gathered over one shoulder' },
    { id: 'tropical-drink', label: 'Tropical Drink', icon: '🍹', group: 'Sun & Sport', prompt: 'a tall tropical drink with a paper umbrella raised in one hand' },
    { id: 'ice-cream', label: 'Ice Cream Cone', icon: '🍦', group: 'Sun & Sport', prompt: 'an ice cream cone held in one hand' },
    { id: 'basketball', label: 'Basketball', icon: '🏀', group: 'Sun & Sport', prompt: 'a basketball spun on one fingertip' },
    { id: 'baseball-bat', label: 'Baseball Bat', icon: '⚾', group: 'Sun & Sport', prompt: 'a baseball bat resting across the shoulders' },
    { id: 'hockey-stick', label: 'Hockey Stick', icon: '🏒', group: 'Sun & Sport', prompt: 'a hockey stick held upright in both hands' },
    { id: 'tennis-racket', label: 'Tennis Racket', icon: '🎾', group: 'Sun & Sport', prompt: 'a tennis racket resting on one shoulder' },
    { id: 'golf-club', label: 'Golf Club', icon: '⛳', group: 'Sun & Sport', prompt: 'a golf club planted like a cane under both hands' },
    { id: 'boxing-gloves', label: 'Boxing Gloves', icon: '🥊', group: 'Sun & Sport', prompt: 'gloved fists raised in a boxing guard' },
    { id: 'football', label: 'Football', icon: '🏈', group: 'Sun & Sport', prompt: 'a football tucked under one arm' },
    { id: 'skateboard', label: 'Skateboard', icon: '🛹', group: 'Sun & Sport', prompt: 'a skateboard held upright at the side' },
    { id: 'ski-poles', label: 'Ski Poles', icon: '⛷️', group: 'Sun & Sport', prompt: 'ski poles planted in both hands' },
    // ── Warriors & Magic (9) ─────────────────────────────────────────────────
    { id: 'katana-sheathed', label: 'Sheathed Katana', icon: '🏯', group: 'Warriors & Magic', prompt: 'a sheathed katana held at the side in one hand' },
    { id: 'bo-staff', label: 'Bo Staff', icon: '🎋', group: 'Warriors & Magic', prompt: 'a wooden bo staff held upright in one hand' },
    { id: 'round-shield', label: 'Round Shield', icon: '🛡️', group: 'Warriors & Magic', prompt: 'a painted round shield on one arm' },
    { id: 'longbow', label: 'Longbow', icon: '🏹', group: 'Warriors & Magic', prompt: 'a longbow held at the side, one hand at the quiver' },
    { id: 'crystal-orb', label: 'Crystal Orb', icon: '🔮', group: 'Warriors & Magic', prompt: 'a glowing crystal orb cradled in both hands' },
    { id: 'spellbook', label: 'Spellbook', icon: '📖', group: 'Warriors & Magic', prompt: 'an open spellbook held in one hand, the other hand raised' },
    { id: 'potion-flask', label: 'Potion Flask', icon: '🧪', group: 'Warriors & Magic', prompt: 'a glowing potion flask raised in one hand' },
    { id: 'dragon-egg', label: 'Dragon Egg', icon: '🥚', group: 'Warriors & Magic', prompt: 'a large scaled dragon egg cradled in both arms' },
    { id: 'plasma-blade', label: 'Energy Blade', icon: '⚡', group: 'Warriors & Magic', prompt: 'a glowing energy blade held upright in one hand' },
    // ── Sci-Fi & Friends (3) ─────────────────────────────────────────────────
    { id: 'ray-gun', label: 'Retro Ray Gun', icon: '🔫', group: 'Sci-Fi & Friends', prompt: 'a chrome retro toy ray gun held at the hip' },
    { id: 'robot-buddy', label: 'Robot Buddy', icon: '🤖', group: 'Sci-Fi & Friends', prompt: 'a small hovering robot companion perched on one hand' },
    { id: 'puppy', label: 'Puppy', icon: '🐶', group: 'Sci-Fi & Friends', prompt: 'a small puppy cradled in both arms' },
    // ── Music & Craft II (7) ─────────────────────────────────────────────────
    { id: 'acoustic-guitar', label: 'Acoustic Guitar', icon: '🎸', group: 'Music & Craft', prompt: 'an acoustic guitar held across the body' },
    { id: 'saxophone', label: 'Saxophone', icon: '🎷', group: 'Music & Craft', prompt: 'a saxophone held in both hands' },
    { id: 'drumsticks', label: 'Drumsticks', icon: '🥁', group: 'Music & Craft', prompt: 'a pair of drumsticks crossed in one hand' },
    { id: 'vintage-camera', label: 'Vintage Camera', icon: '📷', group: 'Music & Craft', prompt: 'a vintage film camera raised in both hands' },
    { id: 'paint-palette', label: 'Paint Palette', icon: '🎨', group: 'Music & Craft', prompt: 'a paint palette in one hand and a brush in the other' },
    { id: 'champagne-flute', label: 'Champagne Flute', icon: '🥂', group: 'Music & Craft', prompt: 'a champagne flute raised in one hand' },
    { id: 'megaphone', label: 'Megaphone', icon: '📣', group: 'Music & Craft', prompt: 'a megaphone raised in one hand' },
];
/** @description 12 interchangeable finishes (test-enforced). */
exports.FINISHES = [
    { id: 'photo', label: 'Photograph', icon: '📷', group: 'Photographic', prompt: 'a realistic professional photograph, high resolution' },
    { id: 'cinematic', label: 'Cinematic', icon: '🎬', group: 'Photographic', prompt: 'a cinematic photograph with shallow depth of field and gentle teal-orange grading' },
    { id: 'bw', label: 'Editorial B&W', icon: '⬛', group: 'Photographic', prompt: 'a dramatic black-and-white editorial photograph with deep shadows and crisp highlights' },
    { id: 'noir', label: 'Film Noir', icon: '🌒', group: 'Photographic', prompt: 'a moody film-noir photograph with hard shadows and slatted venetian-blind light' },
    { id: 'tintype', label: 'Vintage Tintype', icon: '🎞️', group: 'Photographic', prompt: 'a vintage sepia tintype photograph with period vignetting' },
    { id: 'polaroid', label: 'Instant Film', icon: '📸', group: 'Photographic', prompt: 'a warm instant-film photograph with soft focus and a subtle border vignette' },
    { id: 'oil', label: 'Oil Painting', icon: '🖼️', group: 'Painterly', prompt: 'a classic oil painting on canvas with Rembrandt lighting' },
    { id: 'regionalist', label: '1930s Painting', icon: '🌾', group: 'Painterly', prompt: 'a flat, meticulous 1930s American Regionalist oil painting' },
    { id: 'watercolor', label: 'Watercolor', icon: '🖌️', group: 'Painterly', prompt: 'a soft watercolor portrait with loose washes' },
    { id: 'pastel', label: 'Pastel', icon: '🌸', group: 'Painterly', prompt: 'a soft pastel illustration with gentle grain' },
    { id: 'charcoal', label: 'Charcoal Sketch', icon: '✏️', group: 'Painterly', prompt: 'a charcoal portrait sketch with bold strokes on toned paper' },
    { id: 'pop-art', label: 'Pop Art', icon: '🟡', group: 'Painterly', prompt: 'a bold pop-art illustration with flat colors and halftone dots' },
    // ── Illustrated (6) + Photographic II (2) ────────────────────────────────
    { id: 'comic-ink', label: 'Comic Book', icon: '💥', group: 'Illustrated', prompt: 'a bold comic-book illustration with ink outlines and flat dynamic color' },
    { id: 'anime-cel', label: 'Anime Cel', icon: '🎌', group: 'Illustrated', prompt: 'a clean anime cel-shaded illustration with crisp lines' },
    { id: 'claymation', label: 'Claymation', icon: '🧱', group: 'Illustrated', prompt: 'a charming stop-motion claymation render with fingerprint texture' },
    { id: 'storybook', label: 'Storybook', icon: '📚', group: 'Illustrated', prompt: 'a warm children\'s storybook illustration with soft gouache texture' },
    { id: 'stained-glass', label: 'Stained Glass', icon: '⛪', group: 'Illustrated', prompt: 'a luminous stained-glass window composition with leaded outlines' },
    { id: 'graphic-poster', label: 'Screen-Print Poster', icon: '🖨️', group: 'Illustrated', prompt: 'a bold screen-printed poster with limited colors and halftone shading' },
    { id: 'film-70s', label: '70s Film', icon: '🎞️', group: 'Photographic', prompt: 'a warm 1970s film photograph with faded color and soft grain' },
    { id: 'cyanotype', label: 'Cyanotype', icon: '🟦', group: 'Photographic', prompt: 'a deep Prussian-blue cyanotype print' },
];
/** @description 4 interchangeable framings (test-enforced). */
exports.FRAMINGS = [
    { id: 'headshot', label: 'Headshot', icon: '🙂', group: 'Framing', prompt: 'head-and-shoulders headshot framing' },
    { id: 'half-body', label: 'Half Body', icon: '🧍', group: 'Framing', prompt: 'half-body framing from the waist up with hands relaxed and visible' },
    { id: 'three-quarter', label: 'Three-Quarter', icon: '🖼️', group: 'Framing', prompt: 'three-quarter-length framing with hands visible' },
    { id: 'full-length', label: 'Full Length', icon: '🚶', group: 'Framing', prompt: 'full-length framing, the entire figure visible with hands in frame' },
    { id: 'wide', label: 'Wide Scene', icon: '🎬', group: 'Framing', prompt: 'wide cinematic framing with the full scene visible and the subjects prominent in the foreground, hands in frame' },
];
