"use strict";
/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * DATE/TIME           | AUTHOR                                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 2026-07-17 20:10:00 | roger.murphy@emeraldcoastsystemsgroup.com   | The big catalog (operator request: "100 profiles, 100 backdrops, 10000 permutations"): EXACTLY 100 backgrounds across 8 groups (studio, corporate, city, nature, home & life, work environments, historical, fantasy), 70 clothing styles, 30 headwear, 26 props (NEW interchangeable layer — pitchfork to espresso cup), 12 finishes, 4 framings. Every entry grouped for optgroup pickers. Counts are ENFORCED by the package test suite so the catalog can't silently decay.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FRAMINGS = exports.FINISHES = exports.PROPS = exports.HEADWEAR = exports.CLOTHING = exports.BACKGROUNDS = void 0;
/** @description EXACTLY 100 interchangeable backgrounds (test-enforced). */
exports.BACKGROUNDS = [
    // ── Studio (10) ──────────────────────────────────────────────────────────
    { id: 'studio-gray', label: 'Studio Gray', icon: '🎞️', group: 'Studio', prompt: 'a seamless neutral gray studio backdrop with a soft vignette' },
    { id: 'corporate-navy', label: 'Corporate Navy', icon: '🏛️', group: 'Studio', prompt: 'a deep navy studio backdrop with a subtle rim light' },
    { id: 'clean-white', label: 'Clean White', icon: '⬜', group: 'Studio', prompt: 'a bright clean white backdrop with high-key lighting' },
    { id: 'charcoal-studio', label: 'Charcoal', icon: '⬛', group: 'Studio', prompt: 'a near-black charcoal studio backdrop with a single dramatic key light' },
    { id: 'cream-studio', label: 'Warm Cream', icon: '🤍', group: 'Studio', prompt: 'a warm cream seamless backdrop with soft window-style light' },
    { id: 'gradient-blue', label: 'Blue Gradient', icon: '🌀', group: 'Studio', prompt: 'a smooth blue-to-teal gradient studio backdrop' },
    { id: 'brick-studio', label: 'Exposed Brick', icon: '🧱', group: 'Studio', prompt: 'a warmly lit exposed-brick studio wall' },
    { id: 'spotlight-black', label: 'Spotlight', icon: '🔦', group: 'Studio', prompt: 'a black void with a single theatrical spotlight from above' },
    { id: 'sage-studio', label: 'Sage Green', icon: '🌿', group: 'Studio', prompt: 'a muted sage-green seamless backdrop with gentle diffusion' },
    { id: 'terracotta-studio', label: 'Terracotta', icon: '🧡', group: 'Studio', prompt: 'a sun-washed terracotta plaster wall with Mediterranean light' },
    // ── Corporate (10) ───────────────────────────────────────────────────────
    { id: 'office-bokeh', label: 'Modern Office', icon: '🏢', group: 'Corporate', prompt: 'a modern bright office background, softly blurred with creamy bokeh' },
    { id: 'boardroom', label: 'Boardroom', icon: '🌆', group: 'Corporate', prompt: 'floor-to-ceiling boardroom windows with a city skyline behind' },
    { id: 'glass-lobby', label: 'Glass Lobby', icon: '🏬', group: 'Corporate', prompt: 'a soaring corporate glass lobby with polished stone floors, softly blurred' },
    { id: 'corner-office', label: 'Corner Office', icon: '🪟', group: 'Corporate', prompt: 'a corner office with two window walls and warm late-afternoon light' },
    { id: 'conference-stage', label: 'Keynote Stage', icon: '🎤', group: 'Corporate', prompt: 'a conference keynote stage with a large blurred presentation screen behind' },
    { id: 'trading-floor', label: 'Trading Floor', icon: '📈', group: 'Corporate', prompt: 'a busy trading floor of glowing market screens, softly out of focus' },
    { id: 'law-library', label: 'Law Library', icon: '⚖️', group: 'Corporate', prompt: 'a stately law library with leather-bound case reports and green desk lamps' },
    { id: 'bank-hall', label: 'Bank Hall', icon: '🏦', group: 'Corporate', prompt: 'a grand marble bank hall with brass fixtures, softly blurred' },
    { id: 'rooftop-terrace', label: 'Rooftop Terrace', icon: '🌇', group: 'Corporate', prompt: 'a skyscraper rooftop terrace at dusk with city lights below' },
    { id: 'coworking', label: 'Co-working Loft', icon: '💻', group: 'Corporate', prompt: 'a bright co-working loft with plants, whiteboards and Edison bulbs, softly blurred' },
    // ── City (10) ────────────────────────────────────────────────────────────
    { id: 'city-street', label: 'City Street', icon: '🚕', group: 'City', prompt: 'a lively downtown street with softly blurred traffic and storefronts' },
    { id: 'cobblestone-alley', label: 'Cobblestone Alley', icon: '🏘️', group: 'City', prompt: 'an old-world cobblestone alley with ivy and iron lanterns' },
    { id: 'neon-night', label: 'Neon Night', icon: '🌃', group: 'City', prompt: 'a rain-slicked night street glowing with colorful neon signs' },
    { id: 'cafe-terrace', label: 'Café Terrace', icon: '☕', group: 'City', prompt: 'a Parisian-style café terrace with woven chairs and striped awning' },
    { id: 'metro-platform', label: 'Metro Platform', icon: '🚇', group: 'City', prompt: 'a tiled metro platform with a motion-blurred train passing' },
    { id: 'market-street', label: 'Market Street', icon: '🍎', group: 'City', prompt: 'a bustling open-air market street with colorful produce stalls' },
    { id: 'riverside', label: 'Riverside Walk', icon: '🌉', group: 'City', prompt: 'a riverside promenade with a grand bridge softly blurred behind' },
    { id: 'old-town-square', label: 'Old Town Square', icon: '⛲', group: 'City', prompt: 'a historic town square with a fountain and pastel facades' },
    { id: 'industrial-loft', label: 'Industrial Loft', icon: '🏭', group: 'City', prompt: 'a converted industrial loft with steel beams and tall factory windows' },
    { id: 'graffiti-wall', label: 'Graffiti Wall', icon: '🎨', group: 'City', prompt: 'a vibrant street-art mural wall in an urban laneway' },
    // ── Nature (14) ──────────────────────────────────────────────────────────
    { id: 'outdoor-golden', label: 'Golden Hour', icon: '🌤️', group: 'Nature', prompt: 'an outdoor golden-hour background with soft natural light and gentle bokeh' },
    { id: 'prairie-dusk', label: 'Prairie Dusk', icon: '🌅', group: 'Nature', prompt: 'a golden prairie at dusk' },
    { id: 'forest-path', label: 'Forest Path', icon: '🌲', group: 'Nature', prompt: 'a sun-dappled forest path with light shafts through tall trees' },
    { id: 'autumn-park', label: 'Autumn Park', icon: '🍁', group: 'Nature', prompt: 'a park ablaze with autumn reds and golds, leaves drifting' },
    { id: 'cherry-blossoms', label: 'Cherry Blossoms', icon: '🌸', group: 'Nature', prompt: 'an avenue of cherry trees in full pink blossom' },
    { id: 'lavender-field', label: 'Lavender Field', icon: '💜', group: 'Nature', prompt: 'endless rows of purple lavender under a Provencal sky' },
    { id: 'mountain-peak', label: 'Mountain Peak', icon: '🏔️', group: 'Nature', prompt: 'a dramatic alpine ridgeline with snow-capped peaks behind' },
    { id: 'alpine-lake', label: 'Alpine Lake', icon: '🏞️', group: 'Nature', prompt: 'a mirror-still alpine lake reflecting pines and peaks' },
    { id: 'desert-dunes', label: 'Desert Dunes', icon: '🏜️', group: 'Nature', prompt: 'sweeping golden desert dunes with long evening shadows' },
    { id: 'waterfall', label: 'Waterfall', icon: '💦', group: 'Nature', prompt: 'a misty waterfall cascading into a fern-lined gorge' },
    { id: 'wildflower-meadow', label: 'Wildflower Meadow', icon: '🌼', group: 'Nature', prompt: 'a meadow thick with wildflowers under a big summer sky' },
    { id: 'snowy-pines', label: 'Snowy Pines', icon: '❄️', group: 'Nature', prompt: 'a hushed snowfall over frosted pine trees' },
    { id: 'ocean-cliff', label: 'Ocean Cliff', icon: '🌊', group: 'Nature', prompt: 'a windswept headland above a crashing turquoise sea' },
    { id: 'tropical-beach', label: 'Tropical Beach', icon: '🏝️', group: 'Nature', prompt: 'a white-sand beach with leaning palms and clear shallows' },
    // ── Home & Life (13) ─────────────────────────────────────────────────────
    { id: 'home-kitchen', label: 'Home Kitchen', icon: '🍳', group: 'Home & Life', prompt: 'a warm farmhouse-style home kitchen with morning light on open shelves' },
    { id: 'living-room', label: 'Living Room', icon: '🛋️', group: 'Home & Life', prompt: 'a cozy living room with a linen sofa, plants and soft lamplight' },
    { id: 'reading-nook', label: 'Reading Nook', icon: '📖', group: 'Home & Life', prompt: 'a window-seat reading nook stacked with well-loved books' },
    { id: 'front-porch', label: 'Front Porch', icon: '🏡', group: 'Home & Life', prompt: 'a wooden front porch with a swing and hanging ferns at golden hour' },
    { id: 'backyard-bbq', label: 'Backyard BBQ', icon: '🍔', group: 'Home & Life', prompt: 'a backyard barbecue with string lights and drifting grill smoke' },
    { id: 'cozy-cafe', label: 'Cozy Café', icon: '🥐', group: 'Home & Life', prompt: 'a snug neighborhood café with latte art and rain on the window' },
    { id: 'bookstore', label: 'Bookstore', icon: '📚', group: 'Home & Life', prompt: 'a labyrinthine secondhand bookstore with ladders and warm lamps' },
    { id: 'greenhouse', label: 'Greenhouse', icon: '🪴', group: 'Home & Life', prompt: 'a glass greenhouse lush with tomatoes, herbs and hazy sunbeams' },
    { id: 'art-studio', label: 'Art Studio', icon: '🖌️', group: 'Home & Life', prompt: 'a paint-splattered artist studio with canvases and north light' },
    { id: 'music-room', label: 'Music Room', icon: '🎹', group: 'Home & Life', prompt: 'a home music room with an upright piano and framed records' },
    { id: 'garage-workshop', label: 'Garage Workshop', icon: '🔧', group: 'Home & Life', prompt: 'a tidy garage workshop with pegboard tools and sawdust in the light' },
    { id: 'holiday-hearth', label: 'Holiday Hearth', icon: '🎄', group: 'Home & Life', prompt: 'a decorated hearth with stockings, garlands and firelight' },
    { id: 'farmers-market', label: 'Farmers Market', icon: '🥕', group: 'Home & Life', prompt: 'a Saturday farmers market with canvas stalls and crates of produce' },
    // ── Work Environments (20) ───────────────────────────────────────────────
    { id: 'steel-mill', label: 'Steel Mill', icon: '🏭', group: 'Work', prompt: 'a steel-mill interior with sparks and molten furnace light' },
    { id: 'kitchen', label: 'Pro Kitchen', icon: '🍳', group: 'Work', prompt: 'a stainless-steel professional kitchen, softly blurred' },
    { id: 'hospital-ward', label: 'Hospital Ward', icon: '🏥', group: 'Work', prompt: 'a bright modern hospital corridor with soft clinical light' },
    { id: 'operating-room', label: 'Operating Room', icon: '🩻', group: 'Work', prompt: 'a state-of-the-art operating theater under cool surgical lights' },
    { id: 'fire-station', label: 'Fire Station', icon: '🚒', group: 'Work', prompt: 'a fire station bay with a gleaming red engine behind' },
    { id: 'police-precinct', label: 'Precinct', icon: '🚓', group: 'Work', prompt: 'a police precinct with flags and a duty board, softly blurred' },
    { id: 'cockpit', label: 'Cockpit', icon: '✈️', group: 'Work', prompt: 'an airliner cockpit aglow with instrument panels' },
    { id: 'airport-tarmac', label: 'Tarmac', icon: '🛫', group: 'Work', prompt: 'an airport tarmac at sunrise with a jet silhouetted behind' },
    { id: 'classroom', label: 'Classroom', icon: '🏫', group: 'Work', prompt: 'a cheerful classroom with a chalkboard full of diagrams' },
    { id: 'lecture-hall', label: 'Lecture Hall', icon: '🎓', group: 'Work', prompt: 'a tiered university lecture hall with equations on the boards' },
    { id: 'laboratory', label: 'Laboratory', icon: '🧪', group: 'Work', prompt: 'a research laboratory with glassware, pipettes and cool blue light' },
    { id: 'server-room', label: 'Server Room', icon: '🖥️', group: 'Work', prompt: 'rows of server racks with blinking status lights in cool air' },
    { id: 'construction-site', label: 'Construction Site', icon: '🏗️', group: 'Work', prompt: 'a high-rise construction site with cranes against the sky' },
    { id: 'wood-shop', label: 'Wood Shop', icon: '🪚', group: 'Work', prompt: 'a carpentry shop with workbenches, clamps and curls of shavings' },
    { id: 'auto-garage', label: 'Auto Garage', icon: '🚗', group: 'Work', prompt: 'an auto garage with a car on the lift and rolling tool chests' },
    { id: 'farm-barn', label: 'Farm Barn', icon: '🐄', group: 'Work', prompt: 'a timber barn with hay bales and morning light through the boards' },
    { id: 'orchard', label: 'Orchard', icon: '🍏', group: 'Work', prompt: 'an apple orchard heavy with fruit, ladders against the trees' },
    { id: 'fishing-harbor', label: 'Fishing Harbor', icon: '⛵', group: 'Work', prompt: 'a working fishing harbor with nets, floats and moored boats' },
    { id: 'newsroom', label: 'Newsroom', icon: '📰', group: 'Work', prompt: 'a buzzing newsroom of monitors and headlines, softly blurred' },
    { id: 'courtroom', label: 'Courtroom', icon: '🏛️', group: 'Work', prompt: 'a wood-paneled courtroom with the bench and flags behind' },
    // ── Historical (13) ──────────────────────────────────────────────────────
    { id: 'castle-hall', label: 'Castle Hall', icon: '🏰', group: 'Historical', prompt: 'a stone castle hall with heraldic banners and torchlight' },
    { id: 'stormy-harbor', label: 'Stormy Harbor', icon: '🌊', group: 'Historical', prompt: 'a weathered harbor under a stormy sea sky' },
    { id: 'fireside-study', label: 'Fireside Study', icon: '🕯️', group: 'Historical', prompt: 'a candlelit study with a stone fireplace' },
    { id: 'library', label: 'Library', icon: '📚', group: 'Historical', prompt: 'a wood-paneled library with shelves of leather-bound books in warm lamplight' },
    { id: 'farmhouse', label: 'Farmhouse', icon: '🌾', group: 'Historical', prompt: 'a white wooden farmhouse with a gothic window under a plain midwestern sky' },
    { id: 'throne-room', label: 'Throne Room', icon: '👑', group: 'Historical', prompt: 'a gilded throne room with velvet drapes and marble columns' },
    { id: 'cathedral', label: 'Cathedral', icon: '⛪', group: 'Historical', prompt: 'a gothic cathedral nave with stained-glass light pooling on stone' },
    { id: 'roman-forum', label: 'Roman Forum', icon: '🏺', group: 'Historical', prompt: 'marble columns and laurels of a Roman forum at midday' },
    { id: 'egyptian-temple', label: 'Egyptian Temple', icon: '𓂀', group: 'Historical', prompt: 'a torch-lit Egyptian temple wall carved with hieroglyphs' },
    { id: 'viking-longhouse', label: 'Viking Longhouse', icon: '🛡️', group: 'Historical', prompt: 'a smoky viking longhouse with carved beams and firelight' },
    { id: 'samurai-dojo', label: 'Samurai Dojo', icon: '🏯', group: 'Historical', prompt: 'a serene dojo with paper screens, tatami and a raked garden beyond' },
    { id: 'speakeasy', label: 'Speakeasy', icon: '🥃', group: 'Historical', prompt: 'a 1920s speakeasy with tufted leather, brass and low amber light' },
    { id: 'victorian-parlor', label: 'Victorian Parlor', icon: '🕰️', group: 'Historical', prompt: 'a Victorian parlor with damask wallpaper and a mantel clock' },
    // ── Fantasy & Fun (10) ───────────────────────────────────────────────────
    { id: 'stage', label: 'Concert Stage', icon: '🎤', group: 'Fantasy & Fun', prompt: 'a concert stage with haze and colored lights' },
    { id: 'starfield', label: 'Space', icon: '🌌', group: 'Fantasy & Fun', prompt: 'a spacecraft interior with Earth and stars visible through a porthole' },
    { id: 'pirate-deck', label: 'Pirate Deck', icon: '🏴‍☠️', group: 'Fantasy & Fun', prompt: 'the deck of a tall ship with rigging, cannon and open sea' },
    { id: 'enchanted-forest', label: 'Enchanted Forest', icon: '🧚', group: 'Fantasy & Fun', prompt: 'a twilight forest aglow with fireflies and luminous mushrooms' },
    { id: 'dragon-lair', label: 'Dragon Lair', icon: '🐉', group: 'Fantasy & Fun', prompt: 'a cavern hoard of gold coins with distant dragon-fire glow' },
    { id: 'airship-deck', label: 'Airship Deck', icon: '🎈', group: 'Fantasy & Fun', prompt: 'the brass-railed deck of a steampunk airship above the clouds' },
    { id: 'neon-arcade', label: 'Neon Arcade', icon: '🕹️', group: 'Fantasy & Fun', prompt: 'a retro arcade glowing with cabinet screens and neon grids' },
    { id: 'circus-ring', label: 'Circus Ring', icon: '🎪', group: 'Fantasy & Fun', prompt: 'a big-top circus ring with sawdust and a spotlight beam' },
    { id: 'moon-base', label: 'Moon Base', icon: '🌕', group: 'Fantasy & Fun', prompt: 'a lunar base window overlooking gray craters and the blue Earth' },
    { id: 'underwater-reef', label: 'Coral Reef', icon: '🐠', group: 'Fantasy & Fun', prompt: 'a sunlit coral reef teeming with fish, shafts of light from above' },
];
/** @description 70 interchangeable clothing styles (test-enforced). */
exports.CLOTHING = [
    // ── Business (12) ────────────────────────────────────────────────────────
    { id: 'keep', label: 'Keep My Clothes', icon: '👕', group: 'Business', prompt: 'the same clothing as in the photo, neatened up' },
    { id: 'dark-suit', label: 'Dark Suit', icon: '🤵', group: 'Business', prompt: 'a tailored dark business suit with a crisp shirt' },
    { id: 'navy-suit', label: 'Navy Suit', icon: '💼', group: 'Business', prompt: 'a sharp navy suit with a white shirt and understated tie' },
    { id: 'gray-suit', label: 'Gray Suit', icon: '🩶', group: 'Business', prompt: 'a light-gray suit with an open-collar white shirt' },
    { id: 'pinstripe', label: 'Pinstripe', icon: '📊', group: 'Business', prompt: 'a classic pinstripe suit with a silk pocket square' },
    { id: 'three-piece', label: 'Three-Piece', icon: '🎩', group: 'Business', prompt: 'a three-piece suit with a buttoned waistcoat and watch chain' },
    { id: 'power-blazer', label: 'Power Blazer', icon: '🔴', group: 'Business', prompt: 'a bold structured blazer over a silk shell top' },
    { id: 'silk-blouse', label: 'Silk Blouse', icon: '🎀', group: 'Business', prompt: 'an elegant silk blouse with tailored trousers' },
    { id: 'pencil-suit', label: 'Tailored Skirt Suit', icon: '👩‍💼', group: 'Business', prompt: 'a tailored skirt suit with a fitted jacket' },
    { id: 'turtleneck-blazer', label: 'Turtleneck + Blazer', icon: '🖤', group: 'Business', prompt: 'a fine black turtleneck under an unstructured blazer' },
    { id: 'overcoat', label: 'Wool Overcoat', icon: '🧥', group: 'Business', prompt: 'a long camel wool overcoat over business attire with a scarf' },
    { id: 'trench-coat', label: 'Trench Coat', icon: '🕵️‍♀️', group: 'Business', prompt: 'a belted khaki trench coat over smart clothes' },
    // ── Business Casual (10) ─────────────────────────────────────────────────
    { id: 'business-casual', label: 'Blazer Casual', icon: '👔', group: 'Business Casual', prompt: 'smart business-casual attire, a blazer over an open-collar shirt' },
    { id: 'smart-creative', label: 'Smart Creative', icon: '🎨', group: 'Business Casual', prompt: 'smart-creative attire, a dark knit under an unstructured jacket' },
    { id: 'knit-polo', label: 'Knit Polo', icon: '🐎', group: 'Business Casual', prompt: 'a fine-knit polo with tailored chinos' },
    { id: 'oxford-chinos', label: 'Oxford + Chinos', icon: '🧵', group: 'Business Casual', prompt: 'a rolled-sleeve oxford shirt with chinos' },
    { id: 'cardigan', label: 'Cardigan', icon: '🧶', group: 'Business Casual', prompt: 'a merino cardigan over a collared shirt' },
    { id: 'denim-blazer', label: 'Denim + Blazer', icon: '👖', group: 'Business Casual', prompt: 'dark selvedge denim with a soft knit tee and blazer' },
    { id: 'linen-shirt', label: 'Linen Shirt', icon: '🌾', group: 'Business Casual', prompt: 'a relaxed linen shirt with the sleeves rolled' },
    { id: 'sweater-vest', label: 'Sweater Vest', icon: '🦺', group: 'Business Casual', prompt: 'a fine sweater vest over a crisp shirt' },
    { id: 'quarter-zip', label: 'Quarter-Zip', icon: '🧊', group: 'Business Casual', prompt: 'a merino quarter-zip pullover over a collared shirt' },
    { id: 'wrap-dress', label: 'Wrap Dress', icon: '💃', group: 'Business Casual', prompt: 'a polished jersey wrap dress' },
    // ── Casual & Life (12) ───────────────────────────────────────────────────
    { id: 'hoodie', label: 'Hoodie', icon: '🧢', group: 'Casual & Life', prompt: 'a clean heavyweight hoodie' },
    { id: 'denim-jacket', label: 'Denim Jacket', icon: '🤠', group: 'Casual & Life', prompt: 'a classic denim jacket over a white tee' },
    { id: 'plain-tee', label: 'Plain Tee', icon: '👕', group: 'Casual & Life', prompt: 'a well-fitted plain t-shirt' },
    { id: 'summer-dress', label: 'Summer Dress', icon: '🌻', group: 'Casual & Life', prompt: 'a breezy floral summer dress' },
    { id: 'flannel', label: 'Flannel', icon: '🪵', group: 'Casual & Life', prompt: 'a soft plaid flannel shirt' },
    { id: 'raincoat', label: 'Raincoat', icon: '🌧️', group: 'Casual & Life', prompt: 'a bright rubberized raincoat with the hood down' },
    { id: 'parka', label: 'Winter Parka', icon: '🧣', group: 'Casual & Life', prompt: 'a fur-trimmed winter parka with a chunky scarf' },
    { id: 'hiking-gear', label: 'Hiking Gear', icon: '🥾', group: 'Casual & Life', prompt: 'technical hiking layers with a daypack strap across the chest' },
    { id: 'hawaiian-shirt', label: 'Hawaiian Shirt', icon: '🌺', group: 'Casual & Life', prompt: 'a vintage hawaiian print shirt' },
    { id: 'cozy-sweater', label: 'Cozy Sweater', icon: '☕', group: 'Casual & Life', prompt: 'an oversized cable-knit sweater' },
    { id: 'tracksuit', label: 'Retro Tracksuit', icon: '🏃', group: 'Casual & Life', prompt: 'a retro striped tracksuit jacket' },
    { id: 'cycling-jersey', label: 'Cycling Jersey', icon: '🚴', group: 'Casual & Life', prompt: 'a bold team cycling jersey' },
    // ── Uniforms & Work (18) ─────────────────────────────────────────────────
    { id: 'scrubs', label: 'Scrubs', icon: '🩺', group: 'Uniforms & Work', prompt: 'teal medical scrubs with a stethoscope around the neck' },
    { id: 'surgeon-gown', label: 'Surgical Gown', icon: '🩻', group: 'Uniforms & Work', prompt: 'a sterile surgical gown with a mask pulled down around the neck' },
    { id: 'doctor-coat', label: "Doctor's Coat", icon: '🥼', group: 'Uniforms & Work', prompt: "a crisp white doctor's coat with a stethoscope around the neck" },
    { id: 'lab-coat', label: 'Lab Coat', icon: '🧪', group: 'Uniforms & Work', prompt: 'a white laboratory coat with safety glasses pushed up' },
    { id: 'firefighter-turnout', label: 'Turnout Gear', icon: '🚒', group: 'Uniforms & Work', prompt: 'firefighter turnout gear with reflective stripes, jacket open' },
    { id: 'police-uniform', label: 'Police Uniform', icon: '👮', group: 'Uniforms & Work', prompt: 'a pressed police uniform with badge and radio' },
    { id: 'pilot-uniform', label: 'Pilot Uniform', icon: '✈️', group: 'Uniforms & Work', prompt: 'an airline captain uniform with four gold stripes' },
    { id: 'flight-suit', label: 'Flight Suit', icon: '🛩️', group: 'Uniforms & Work', prompt: 'an olive aviator flight suit with squadron patches' },
    { id: 'coveralls', label: 'Mechanic Coveralls', icon: '🔧', group: 'Uniforms & Work', prompt: 'workshop coveralls with a shop rag in the pocket' },
    { id: 'hi-vis', label: 'Hi-Vis + Harness', icon: '🦺', group: 'Uniforms & Work', prompt: 'a hi-vis vest over work clothes with a safety harness' },
    { id: 'work-canvas', label: 'Work Jacket', icon: '🧰', group: 'Uniforms & Work', prompt: 'a rugged canvas work jacket with leather work gloves' },
    { id: 'barista-apron', label: 'Barista Apron', icon: '☕', group: 'Uniforms & Work', prompt: 'a denim barista apron over a rolled-sleeve shirt' },
    { id: 'leather-apron', label: 'Leather Apron', icon: '🔨', group: 'Uniforms & Work', prompt: 'a heavy leather smith apron over a work shirt' },
    { id: 'fisherman-slicker', label: 'Fisherman Slicker', icon: '🎣', group: 'Uniforms & Work', prompt: 'yellow fisherman bib overalls and slicker' },
    { id: 'conductor-uniform', label: 'Train Conductor', icon: '🚂', group: 'Uniforms & Work', prompt: 'a classic train conductor uniform with brass buttons' },
    { id: 'park-ranger', label: 'Park Ranger', icon: '🌲', group: 'Uniforms & Work', prompt: 'a park ranger uniform with shoulder patches' },
    { id: 'chef-whites', label: "Chef's Whites", icon: '👨‍🍳', group: 'Uniforms & Work', prompt: "crisp chef's whites with a knotted neckerchief" },
    { id: 'farmer-overalls', label: 'Farmer', icon: '🌾', group: 'Uniforms & Work', prompt: 'a black jacket over a collarless shirt and denim overalls' },
    // ── Occasion (8) ─────────────────────────────────────────────────────────
    { id: 'tuxedo', label: 'Tuxedo', icon: '🥂', group: 'Occasion', prompt: 'a classic black tuxedo with a bow tie' },
    { id: 'evening-gown', label: 'Evening Gown', icon: '💎', group: 'Occasion', prompt: 'an elegant formal evening gown' },
    { id: 'academic-gown', label: 'Graduation Gown', icon: '🎓', group: 'Occasion', prompt: 'a black academic graduation gown with a colored hood' },
    { id: 'judge-robe', label: 'Judicial Robes', icon: '⚖️', group: 'Occasion', prompt: 'formal black judicial robes with a white collar' },
    { id: 'dress-uniform', label: 'Dress Uniform', icon: '🎖️', group: 'Occasion', prompt: 'a decorated military dress uniform with medals and epaulettes' },
    { id: 'kilt', label: 'Highland Kilt', icon: '🏴', group: 'Occasion', prompt: 'full highland dress with tartan kilt and sporran' },
    { id: 'kimono', label: 'Formal Kimono', icon: '🎎', group: 'Occasion', prompt: 'an exquisite formal silk kimono with an obi sash' },
    { id: 'sari', label: 'Silk Sari', icon: '🪔', group: 'Occasion', prompt: 'a richly embroidered silk sari with gold border' },
    // ── Costume & History (10) ───────────────────────────────────────────────
    { id: 'renaissance-doublet', label: 'Renaissance Doublet', icon: '👑', group: 'Costume & History', prompt: 'an ornate velvet Renaissance doublet with a white ruff collar and a gold chain of office' },
    { id: 'spacesuit', label: 'Spacesuit', icon: '🚀', group: 'Costume & History', prompt: 'a white NASA-style spacesuit' },
    { id: 'peacoat', label: 'Navy Peacoat', icon: '⚓', group: 'Costume & History', prompt: 'a navy wool peacoat' },
    { id: 'wizard-robes', label: 'Wizard Robes', icon: '🧙', group: 'Costume & History', prompt: 'deep blue wizard robes embroidered with silver thread' },
    { id: 'leather-jacket', label: 'Leather Jacket', icon: '🎸', group: 'Costume & History', prompt: 'a worn black leather jacket over a band tee' },
    { id: 'duster-coat', label: 'Western Duster', icon: '🤠', group: 'Costume & History', prompt: 'a long western duster coat' },
    { id: 'plate-armor', label: 'Plate Armor', icon: '⚔️', group: 'Costume & History', prompt: 'polished steel plate armor' },
    { id: 'toga', label: 'Roman Toga', icon: '🏺', group: 'Costume & History', prompt: 'a draped white toga with a purple senatorial stripe' },
    { id: 'pirate-coat', label: 'Pirate Coat', icon: '🏴‍☠️', group: 'Costume & History', prompt: 'a weathered captain frock coat with a wide leather baldric' },
    { id: 'gatsby-tux', label: '1920s Tux', icon: '🥃', group: 'Costume & History', prompt: 'a 1920s white-tie tuxedo with slicked styling' },
];
/** @description 30 interchangeable headwear items (test-enforced). 'none' composes to nothing. */
exports.HEADWEAR = [
    { id: 'none', label: 'No Hat', icon: '🚫', group: 'Everyday', prompt: '' },
    { id: 'baseball-cap', label: 'Baseball Cap', icon: '🧢', group: 'Everyday', prompt: 'a clean baseball cap' },
    { id: 'beanie', label: 'Beanie', icon: '🧶', group: 'Everyday', prompt: 'a snug knit beanie' },
    { id: 'flat-cap', label: 'Flat Cap', icon: '🍂', group: 'Everyday', prompt: 'a tweed flat cap' },
    { id: 'sun-hat', label: 'Sun Hat', icon: '🌞', group: 'Everyday', prompt: 'a wide-brim woven sun hat' },
    { id: 'fedora', label: 'Fedora', icon: '🕵️', group: 'Everyday', prompt: 'a classic felt fedora' },
    { id: 'beret', label: 'Beret', icon: '🎨', group: 'Everyday', prompt: 'a wool beret' },
    { id: 'bowler', label: 'Bowler', icon: '🎩', group: 'Everyday', prompt: 'a black bowler hat' },
    { id: 'boater', label: 'Straw Boater', icon: '🛶', group: 'Everyday', prompt: 'a straw boater with a striped band' },
    { id: 'top-hat', label: 'Top Hat', icon: '🎩', group: 'Everyday', prompt: 'a black silk top hat' },
    { id: 'hard-hat', label: 'Hard Hat', icon: '👷', group: 'Work', prompt: 'a yellow hard hat' },
    { id: 'chef-toque', label: 'Chef Toque', icon: '👨‍🍳', group: 'Work', prompt: "a tall white chef's toque" },
    { id: 'captains-cap', label: "Captain's Cap", icon: '⚓', group: 'Work', prompt: "a sea captain's peaked cap" },
    { id: 'peaked-cap', label: 'Military Cap', icon: '🎖️', group: 'Work', prompt: 'a military peaked cap with gold braid' },
    { id: 'police-cap', label: 'Police Cap', icon: '👮', group: 'Work', prompt: 'a police duty cap with badge' },
    { id: 'firefighter-helmet', label: 'Fire Helmet', icon: '🚒', group: 'Work', prompt: 'a firefighter helmet with the shield up' },
    { id: 'surgical-cap', label: 'Surgical Cap', icon: '🩻', group: 'Work', prompt: 'a patterned surgical cap' },
    { id: 'aviator-cap', label: 'Aviator Cap', icon: '🛩️', group: 'Work', prompt: 'a leather aviator cap with goggles pushed up' },
    { id: 'cowboy-hat', label: 'Cowboy Hat', icon: '🤠', group: 'Work', prompt: 'a wide-brim cowboy hat' },
    { id: 'pith-helmet', label: 'Explorer Pith', icon: '🧭', group: 'Work', prompt: 'a khaki explorer pith helmet' },
    { id: 'graduation-cap', label: 'Graduation Cap', icon: '🎓', group: 'Occasion', prompt: 'a mortarboard graduation cap with a tassel' },
    { id: 'crown', label: 'Crown', icon: '👑', group: 'Occasion', prompt: 'a golden jeweled crown' },
    { id: 'flower-crown', label: 'Flower Crown', icon: '🌸', group: 'Occasion', prompt: 'a delicate flower crown' },
    { id: 'laurel-wreath', label: 'Laurel Wreath', icon: '🏺', group: 'Occasion', prompt: 'a golden laurel wreath' },
    { id: 'wizard-hat', label: 'Wizard Hat', icon: '🧙', group: 'Fantasy & History', prompt: 'a tall pointed wizard hat' },
    { id: 'viking-helm', label: 'Viking Helm', icon: '🛡️', group: 'Fantasy & History', prompt: 'a riveted iron viking helm' },
    { id: 'kabuto', label: 'Samurai Kabuto', icon: '🏯', group: 'Fantasy & History', prompt: 'a lacquered samurai kabuto helmet' },
    { id: 'tricorn', label: 'Pirate Tricorn', icon: '🏴‍☠️', group: 'Fantasy & History', prompt: 'a weathered leather tricorn hat' },
    { id: 'deerstalker', label: 'Deerstalker', icon: '🔎', group: 'Fantasy & History', prompt: 'a checked deerstalker cap' },
    { id: 'nemes', label: 'Pharaoh Nemes', icon: '𓂀', group: 'Fantasy & History', prompt: 'a striped gold-and-lapis pharaoh nemes headdress' },
];
/** @description 26 interchangeable props — each is a full hands/pose line (test-enforced). */
exports.PROPS = [
    { id: 'none', label: 'No Prop', icon: '🚫', group: 'Everyday', prompt: '' },
    { id: 'coffee-mug', label: 'Coffee Mug', icon: '☕', group: 'Everyday', prompt: 'both hands wrapped around a steaming coffee mug' },
    { id: 'open-book', label: 'Open Book', icon: '📖', group: 'Everyday', prompt: 'an open book held in both hands' },
    { id: 'newspaper', label: 'Newspaper', icon: '📰', group: 'Everyday', prompt: 'a folded broadsheet newspaper held in one hand' },
    { id: 'laptop', label: 'Laptop', icon: '💻', group: 'Everyday', prompt: 'a slim laptop cradled against one arm, the other hand resting on it' },
    { id: 'briefcase', label: 'Briefcase', icon: '💼', group: 'Everyday', prompt: 'a leather briefcase held at the side in one hand' },
    { id: 'umbrella', label: 'Umbrella', icon: '☂️', group: 'Everyday', prompt: 'a furled umbrella planted like a cane under one hand' },
    { id: 'bouquet', label: 'Bouquet', icon: '💐', group: 'Everyday', prompt: 'a fresh bouquet of flowers cradled in both arms' },
    { id: 'trophy', label: 'Trophy', icon: '🏆', group: 'Everyday', prompt: 'a gleaming trophy held proudly in both hands' },
    { id: 'walking-cane', label: 'Cane', icon: '🦯', group: 'Everyday', prompt: 'both hands resting on a silver-topped cane' },
    { id: 'pocket-watch', label: 'Pocket Watch', icon: '⌚', group: 'Everyday', prompt: 'one hand consulting a gold pocket watch on a chain' },
    { id: 'magnifying-glass', label: 'Magnifier', icon: '🔎', group: 'Everyday', prompt: 'a brass magnifying glass raised in one hand' },
    { id: 'globe', label: 'Globe', icon: '🌍', group: 'Scholarly', prompt: 'one hand resting on an antique desk globe' },
    { id: 'telescope', label: 'Telescope', icon: '🔭', group: 'Scholarly', prompt: 'a brass spyglass telescope held in both hands' },
    { id: 'quill', label: 'Quill', icon: '🪶', group: 'Scholarly', prompt: 'a feather quill poised in one hand over parchment' },
    { id: 'lantern', label: 'Lantern', icon: '🏮', group: 'Scholarly', prompt: 'a glowing iron lantern raised in one hand' },
    { id: 'violin', label: 'Violin', icon: '🎻', group: 'Music & Craft', prompt: 'a violin tucked under the chin, bow poised in the other hand' },
    { id: 'electric-guitar', label: 'Electric Guitar', icon: '🎸', group: 'Music & Craft', prompt: 'an electric guitar held with both hands' },
    { id: 'microphone', label: 'Microphone', icon: '🎤', group: 'Music & Craft', prompt: 'a vintage microphone gripped in one hand' },
    { id: 'chef-knife', label: "Chef's Knife", icon: '🔪', group: 'Music & Craft', prompt: "a chef's knife held at rest over a cutting board, other hand steadying it" },
    { id: 'fishing-rod', label: 'Fishing Rod', icon: '🎣', group: 'Trades & Adventure', prompt: 'a fishing rod shouldered in one hand' },
    { id: 'pitchfork', label: 'Pitchfork', icon: '🌾', group: 'Trades & Adventure', prompt: 'one hand gripping a pitchfork upright, the other at the lapel' },
    { id: 'felling-axe', label: 'Felling Axe', icon: '🪓', group: 'Trades & Adventure', prompt: 'a felling axe resting across one shoulder, gripped in one hand' },
    { id: 'smith-hammer', label: 'Smith Hammer', icon: '🔨', group: 'Trades & Adventure', prompt: 'a blacksmith hammer resting head-down under one hand like a gavel' },
    { id: 'longsword', label: 'Longsword', icon: '⚔️', group: 'Trades & Adventure', prompt: 'both hands resting on the pommel of a point-down longsword' },
    { id: 'wizard-staff', label: 'Wizard Staff', icon: '🧙', group: 'Trades & Adventure', prompt: 'one hand holding a carved wooden staff, the other cradling a faintly glowing orb' },
];
/** @description 12 interchangeable finishes (test-enforced). */
exports.FINISHES = [
    { id: 'photo', label: 'Photograph', icon: '📷', group: 'Photographic', prompt: 'a realistic professional photograph, high resolution' },
    { id: 'cinematic', label: 'Cinematic', icon: '🎬', group: 'Photographic', prompt: 'a cinematic photograph with shallow depth of field and gentle teal-orange grading' },
    { id: 'bw', label: 'Editorial B&W', icon: '⬛', group: 'Photographic', prompt: 'a dramatic black-and-white editorial photograph with deep shadows and crisp highlights' },
    { id: 'noir', label: 'Film Noir', icon: '🌒', group: 'Photographic', prompt: 'a moody film-noir photograph with hard shadows and slatted venetian-blind light' },
    { id: 'tintype', label: 'Vintage Tintype', icon: '🎞️', group: 'Photographic', prompt: 'a vintage sepia tintype photograph with period vignetting' },
    { id: 'polaroid', label: 'Instant Film', icon: '📸', group: 'Photographic', prompt: 'a warm instant-film photograph with soft focus and a subtle border vignette' },
    { id: 'oil', label: 'Oil Painting', icon: '🖼️', group: 'Painterly', prompt: 'a classic oil painting on canvas with Rembrandt lighting' },
    { id: 'regionalist', label: '1930s Painting', icon: '🌾', group: 'Painterly', prompt: 'a flat, meticulous 1930s American Regionalist oil painting' },
    { id: 'watercolor', label: 'Watercolor', icon: '🖌️', group: 'Painterly', prompt: 'a soft watercolor portrait with loose washes' },
    { id: 'pastel', label: 'Pastel', icon: '🌸', group: 'Painterly', prompt: 'a soft pastel illustration with gentle grain' },
    { id: 'charcoal', label: 'Charcoal Sketch', icon: '✏️', group: 'Painterly', prompt: 'a charcoal portrait sketch with bold strokes on toned paper' },
    { id: 'pop-art', label: 'Pop Art', icon: '🟡', group: 'Painterly', prompt: 'a bold pop-art illustration with flat colors and halftone dots' },
];
/** @description 4 interchangeable framings (test-enforced). */
exports.FRAMINGS = [
    { id: 'headshot', label: 'Headshot', icon: '🙂', group: 'Framing', prompt: 'head-and-shoulders headshot framing' },
    { id: 'half-body', label: 'Half Body', icon: '🧍', group: 'Framing', prompt: 'half-body framing from the waist up with hands relaxed and visible' },
    { id: 'three-quarter', label: 'Three-Quarter', icon: '🖼️', group: 'Framing', prompt: 'three-quarter-length framing with hands visible' },
    { id: 'full-length', label: 'Full Length', icon: '🚶', group: 'Framing', prompt: 'full-length framing, the entire figure visible with hands in frame' },
];
//# sourceMappingURL=portrait-layers.js.map